In [1]:
from pathlib import Path

PROJECT_ROOT = Path(
    "/Users/jamesjr/Documents/SemiconductorPatentRAG"
)

CORPUS_ROOT = PROJECT_ROOT / "semiconductor_patents"

RAW_ROOT = CORPUS_ROOT / "raw"
CANONICAL_ROOT = CORPUS_ROOT / "canonical"

RAW_ROOT.mkdir(parents=True, exist_ok=True)
CANONICAL_ROOT.mkdir(parents=True, exist_ok=True)

print("=" * 80)
print("SEMICONDUCTOR PATENT CORPUS")
print("=" * 80)

print("Project:")
print(PROJECT_ROOT)

print("\nCorpus:")
print(CORPUS_ROOT)

print("\nRaw:")
print(RAW_ROOT)

print("\nCanonical:")
print(CANONICAL_ROOT)

print("\nExisting files:")
for path in sorted(CORPUS_ROOT.iterdir()):
    print(" ", path.name)

================================================================================
SEMICONDUCTOR PATENT CORPUS
================================================================================
Project:
/Users/jamesjr/Documents/SemiconductorPatentRAG

Corpus:
/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents

Raw:
/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/raw

Canonical:
/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/canonical

Existing files:
  01_manufacturing
  02_transistors_devices
  03_memory
  04_advanced_packaging
  05_power_semiconductors
  06_photonics
  07_ai_semiconductors
  advanced_packaging
  ai_advanced_semiconductor
  ai_advanced_semiconductors
  canonical
  csv
  memory
  metadata.csv
  photonics
  power_semiconductors
  raw
  semiconductor_manufacturing
  transistor_device_technology

In [2]:
from pathlib import Path

CORPUS_ROOT = Path(
    "/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents"
)

print("=" * 80)
print("CURRENT CORPUS INVENTORY")
print("=" * 80)

for directory in sorted(CORPUS_ROOT.iterdir()):
    if not directory.is_dir():
        continue

    files = [
        p for p in directory.rglob("*")
        if p.is_file()
    ]

    print(f"\n{directory.name}")
    print(f"  Files: {len(files):,}")

    if files:
        for f in files[:3]:
            print(f"    {f.relative_to(directory)}")

        if len(files) > 3:
            print(f"    ... ({len(files)-3:,} more)")

================================================================================
CURRENT CORPUS INVENTORY
================================================================================

01_manufacturing
  Files: 0

02_transistors_devices
  Files: 0

03_memory
  Files: 0

04_advanced_packaging
  Files: 0

05_power_semiconductors
  Files: 0

06_photonics
  Files: 0

07_ai_semiconductors
  Files: 0

advanced_packaging
  Files: 75
    patent_23ebeda5c273212c3bcd.txt
    patent_d6b919ccb69b6b48ba28.txt
    patent_77ef8db797ce48c60943.txt
    ... (72 more)

ai_advanced_semiconductor
  Files: 50
    patent_974383439b73ac49.txt
    patent_21481e06bf68d6b0.txt
    patent_6294fc102d314418.txt
    ... (47 more)

ai_advanced_semiconductors
  Files: 0

canonical
  Files: 0

csv
  Files: 0

memory
  Files: 75
    patent_2a65b7f115a263fa.txt
    patent_407e4f14a64cafca.txt
    patent_ac5cdd791fc4f412.txt
    ... (72 more)

photonics
  Files: 50
    patent_47dd6eb7e6eae8ab.txt
    patent_eb54814596981097.txt
    patent_98cb2fd1b732cc19.txt
    ... (47 more)

power_semiconductors
  Files: 50
    patent_f4f37be1a1dcf4c4.txt
    patent_acef934600e2200be285.txt
    patent_752bf09847b4d6e0c893.txt
    ... (47 more)

raw
  Files: 0

semiconductor_manufacturing
  Files: 100
    patent_5ad88c636ecc0add.txt
    patent_e4781bcd50e6fff6.txt
    patent_1bf06fee96763105.txt
    ... (97 more)

transistor_device_technology
  Files: 100
    patent_f25e95d6e030dc83.txt
    patent_bdc00048a7b080f5.txt
    patent_9ea45e3b200fe614.txt
    ... (97 more)

In [3]:
from pathlib import Path

CORPUS_ROOT = Path(
    "/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents"
)

samples = [
    CORPUS_ROOT / "semiconductor_manufacturing" / "patent_5ad88c636ecc0add.txt",
    CORPUS_ROOT / "transistor_device_technology" / "patent_f25e95d6e030dc83.txt",
]

for path in samples:
    print("\n" + "=" * 100)
    print(path)
    print("=" * 100)

    text = path.read_text(errors="ignore")

    print(text[:5000])

====================================================================================================
/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/semiconductor_manufacturing/patent_5ad88c636ecc0add.txt
====================================================================================================
PATENT DOCUMENT
DOCUMENT_ID: 5ad88c636ecc0add
CATEGORY: semiconductor_manufacturing
DATASET: BIGPATENT

ABSTRACT
========
Method, components, design and fabrication process of a advanced X-ray flat panel detector (FPD), with built-in anti-scattering grid to reduce the X-ray scattering are disclosed. We further disclose two methods in the new X-ray detector: In the first method, the grid is placed on top of X-ray scintillator layer of a FPD, the pixels of X-ray FPD underneath are aligned with the hole structures of anti-scatter grids. The high performance anti-scatter grid applied and aligned to the flat panel detector (FPD) pixel-by-pixel can significantly reduce the noise from the scattered X-rays. The key advantages of the improved art are substantial reduction of grid shadow, improved image contrast-to-noise ratio (CNR) and minimized attenuation of direct X-rays. The new FPD with built-in grid may significantly enhance X-ray imaging system performance for a FPD based digital detection system with high image quality, high throughput and low cost for many X-ray imaging applications. In the second method, the grid may be fully or partially filled with X-ray scintillators and the combined sensor plate can be applied as X-ray sensor on a FPD. This plate integrates X-ray scintillator with anti-scatter grid. Using this scintillator plate on FPD, the key X-ray detector performances, such as image contrast-to-noise ratio (CNR), modulation transfer function (MTF), and detective quantum efficiency (DQE) may be improved significantly. The design of the detector plate allows flexible choices of the various scintillators to meet specific requirements of an X-ray imaging system, without sacrificing the detector performances such as the scattering X-ray rejection and MTF.

DESCRIPTION
===========
[0001] This application claims priority to the provisional application entitled “Advanced X-ray Detectors”, Ser. No. 60/478,500, filed by the same subject inventors and assignee as the subject invention on Jun. 14, 2003. BACKGROUND OF THE INVENTION [0002] 1. Field of the Invention [0003] The present invention relates generally to X-ray detectors and more particularly to a system and a method for integrating an anti-scattering grid with scintillators to significantly enhance the performance of flat panel X-ray detector. [0004] 2. Background Art [0005] Over the last several years, digital X-ray flat-panel detectors (FPD) based on the combination of amorphous silicon thin film transistor and photodiode with X-ray scintillators technology have been successfully developed by several major medical imaging equipment company (GEMS-PerkinElmer Optoelectronics Inc., Phillips-Varian-dPix and Hologic Inc. etc.). These digital detectors, in general, have much better dynamic range and detection quantum efficiency (DQE) than conventional X-ray films. Due to fast market growth of flat-panel based digital X-ray imaging systems and continuous improvement in large panel manufacturing technology and yield, performance-to-price ratio of FPD is improving rapidly. [0006] The existing digital X-ray FPD technology can be divided into 2 categories: direct and indirect conversion. In direct conversion X-ray FPD (e.g., Hologic Inc.), Selenium (Se) photoconductor is used to directly convert X-rays into free electrons. Selenium detectors have very high Modular Transfer Function (MTF), but suffer low X-ray quantum efficiency (for X-ray energy &gt;40 keV) and low X-ray absorption. It also has high image lag and low detection quantum efficiency (DQE) at low spatial frequencies. Most indirect conversion detectors use either CsI or Gd 2 O 2 S as X-ray scintillator and amorphous silicon photodiode array as light sensor. Indirect conversion detectors have high quantum efficiency (for X-ray photons above 40 keV), low image lag and high DQE at low spatial frequencies. However, the existing indirect X-ray FPD suffers low MTF and low DQE at high spatial frequency. The present invention provides an improvement on the existing indirect X-ray FPD by introducing a registered anti-scatter grid in the FPD, resulting structured scintillators in registry to pixels of underlying photon detector array in FPD. The improvements will significantly reduce X-ray scattering and improve the MTF and DQE of existing indirect digital X-ray FPD. [0007] There are several key challenges in building a high performance FPD for medical X-ray diagnostic imaging applications. One of the challenges is the need for higher resolution and higher sensitivity with the FPD for imaging small bones and soft tissues. There is a continues improvements by various major manufactures of medical systems (e.g. Perkin Elmer, Varian, GE) to enhance resolution. The other challenge is the reduced image contrast of scatter-to-direct X-rays, which is a serious issue particularly for Computed Tomography (CT) detector applications. The scattering issue needs to be resolved before the FPD may become a viable detector fo

====================================================================================================
/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/transistor_device_technology/patent_f25e95d6e030dc83.txt
====================================================================================================
PATENT DOCUMENT
DOCUMENT_ID: f25e95d6e030dc83
CATEGORY: transistor_device_technology
DATASET: BIGPATENT

ABSTRACT
========
An improved apparatus for examining the crystal lattice of a semiconductor wafer utilizing x-ray diffraction techniques. The apparatus is employed in a method which includes the step of recording the image of a wafer supported in a bent configuration conforming to a compound curve, produced through the use of a vaccum chuck provided for an x-ray camera while the entire surface thereof is illuminated simultaneously by a beam of incident x-rays which are projected from a distant point-source and satisfy conditions of the Bragg Law for all points on the surface of the wafer.

DESCRIPTION
===========
ORIGIN OF THE INVENTION The invention described herein was made in the performance of work under a NASA contract and is subject to the provisions of Section 305 of the National Aeronautics and Space Act of 1958, Public Law 85-568 (72 Stat. 435; 42 U.S.C. 2457). BACKGROUND OF THE INVENTION 1. Field of the Invention This invention relates to an apparatus for evaluating semiconductor devices and more particularly to an apparatus which facilitates rapid, nondestructive identification of lattice defects, including strains generated in crystalline semiconductor wafers during the fabrication of semiconductor devices. As can readily be understood by those familiar with the fabrication of semiconductor devices, each semiconductor wafer is subjected to numerous processing steps during fabrication which tend to introduce defects in the crystalline lattice thereof. These steps include subjecting the wafers to relatively high temperatures in the presence of controlled environments for purposes of enhancing oxide growth, impurity deposition, impurity diffusion, and/or annealing. Lattice defects thus introduced have a predictable effect, to a greater or lesser degree, on the probability that a properly functioning device will be produced, as well as on the overall reliability of that device. It is therefore advantageous for a manufacturer of semiconductor devices to know which of the processing steps tend to produce lattice defects, and to what degree such defects influence performance so that each processing step which produces lattice defects can be modified to correct improper procedures. 2. Description of the Prior Art Most presently known techniques employed in determining the degree, distribution, and type of lattice defects present in a given semiconductor wafer are destructive. Consequently, any study relying upon such techniques to determine the effects of lattice defects on the performance of semiconductor devices is necessarily highly statistical. Thus, in order to obtain useful data when employing destructive evaluation techniques, large numbers of wafers must be sacrificed for analysis purposes and considerable effort must be devoted to correlating the resulting data. Hence, it can be appreciated that nondestructive techniques are preferred over those techniques in which a destruction of specimens is required. One technique heretofore employed in examining semiconductor wafers is a technique referred to as x-ray topography. When employing such a technique it is possible to determine the degree, distribution, and type of existing lattice defect, while no permanent change in the physical, chemical or electrical properties of the semiconductor wafer is introduced. Studies using this technique, unfortunately, also are statistical in nature. However, the number of specimen samples required for a given confidence level is considerably reduced, since knowledge relating to lattice defects in a given semiconductor wafer may be obtained before and after each processing step. Although numerous attempts have been made to identify lattice defects using x-ray diffraction, no totally satisfactory solution has resulted from these efforts. For example, the Berg-Barrett technique was first introduced about 1945 in which diffracted rays are caused to leave specimens on the same side as the incoming rays enter. In most current applications of this technique, the specimen and the film are supported in a stationary relationship during exposure. Another technique is the so-called Lang method which was first introduced in 1959 in which the diffracted rays travel through the specimen in reaching a photographic plate. This technique normally requires the specimen and photographic plate be translated to and fro during exposure in order to form an image of a relatively large portion of the specimen. In each of the aforementioned techniques, only an extremely small portion of the total radiation from a small x-ray source is used in the production of an x-ray topograph, thus the costs per x-ray topograph are undesirably high. Of course, one of the major reasons that x-ray topography is not more widely used as an analytical tool for detection of lattice defects in semiconductor wafers is the high cost per x-ray topograph. In a

In [4]:
from pathlib import Path
import re
import pandas as pd

CORPUS_ROOT = Path(
    "/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents"
)

# Only the seven actual category directories
CATEGORIES = [
    "semiconductor_manufacturing",
    "transistor_device_technology",
    "memory",
    "advanced_packaging",
    "power_semiconductors",
    "photonics",
    "ai_advanced_semiconductor",
]

records = []

for category in CATEGORIES:
    category_dir = CORPUS_ROOT / category

    for path in sorted(category_dir.glob("*.txt")):
        text = path.read_text(encoding="utf-8", errors="replace")

        # Extract sections
        abstract_match = re.search(
            r"\bABSTRACT\s*\n=+\s*\n(.*?)(?=\nDESCRIPTION\s*\n=+)",
            text,
            re.DOTALL | re.IGNORECASE,
        )

        description_match = re.search(
            r"\bDESCRIPTION\s*\n=+\s*\n(.*)",
            text,
            re.DOTALL | re.IGNORECASE,
        )

        document_id = re.search(
            r"DOCUMENT_ID:\s*(\S+)",
            text,
            re.IGNORECASE,
        )

        abstract = abstract_match.group(1).strip() if abstract_match else ""
        description = description_match.group(1).strip() if description_match else ""

        records.append({
            "category": category,
            "filename": path.name,
            "document_id": document_id.group(1) if document_id else "",
            "abstract_present": bool(abstract),
            "description_present": bool(description),
            "abstract_words": len(abstract.split()),
            "description_words": len(description.split()),
            "total_words": len(text.split()),
            "paragraph_count": len(
                re.findall(r"(?m)^\[\d{4}\]", description)
            ),
        })

audit = pd.DataFrame(records)

print("=" * 70)
print("CORPUS AUDIT")
print("=" * 70)

print(f"\nTotal files: {len(audit)}")

print("\nCategory counts:")
print(audit["category"].value_counts().sort_index())

print("\nMissing abstracts:", (~audit["abstract_present"]).sum())
print("Missing descriptions:", (~audit["description_present"]).sum())
print("Missing document IDs:", (audit["document_id"] == "").sum())

print("\nDuplicate document IDs:",
      audit["document_id"].duplicated().sum())

print("\nDuplicate filenames:",
      audit["filename"].duplicated().sum())

print("\nParagraph statistics:")
print(audit["paragraph_count"].describe())

print("\nWord-count statistics:")
print(audit[["abstract_words", "description_words", "total_words"]].describe())

print("\nFiles with no paragraph markers:")
print((audit["paragraph_count"] == 0).sum())

print("\nFiles with very short descriptions (<100 words):")
print((audit["description_words"] < 100).sum())

print("\nFiles with potential problems:")
problems = audit[
    (~audit["abstract_present"]) |
    (~audit["description_present"]) |
    (audit["document_id"] == "") |
    (audit["paragraph_count"] == 0)
]

print(problems[
    [
        "category",
        "filename",
        "document_id",
        "abstract_present",
        "description_present",
        "paragraph_count",
        "description_words",
    ]
].to_string(index=False))

======================================================================
CORPUS AUDIT
======================================================================

Total files: 500

Category counts:
category
advanced_packaging               75
ai_advanced_semiconductor        50
memory                           75
photonics                        50
power_semiconductors             50
semiconductor_manufacturing     100
transistor_device_technology    100
Name: count, dtype: int64

Missing abstracts: 69
Missing descriptions: 0
Missing document IDs: 69

Duplicate document IDs: 68

Duplicate filenames: 0

Paragraph statistics:
count    500.000000
mean       0.034000
std        0.181411
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000
Name: paragraph_count, dtype: float64

Word-count statistics:
       abstract_words  description_words   total_words
count      500.000000         500.000000    500.000000
mean        97.936000        5325.346000   5451.196000
std         56.146315        3361.827365   3368.696184
min          0.000000        1116.000000   1185.000000
25%         64.000000        3342.500000   3464.000000
50%        102.500000        4637.500000   4769.000000
75%        137.000000        6309.750000   6426.000000
max        266.000000       36025.000000  36127.000000

Files with no paragraph markers:
483

Files with very short descriptions (<100 words):
0

Files with potential problems:
                    category                        filename      document_id  abstract_present  description_present  paragraph_count  description_words
 semiconductor_manufacturing     patent_035ed7683a8cf2c3.txt 035ed7683a8cf2c3              True                 True                0               3385
 semiconductor_manufacturing     patent_08064dc5e6a41c78.txt 08064dc5e6a41c78              True                 True                0               6281
 semiconductor_manufacturing     patent_095d694dbb617b65.txt 095d694dbb617b65              True                 True                0              12288
 semiconductor_manufacturing     patent_0bf59cde519a6316.txt 0bf59cde519a6316              True                 True                0               1855
 semiconductor_manufacturing     patent_0c3c5540a4fd4e21.txt 0c3c5540a4fd4e21              True                 True                0               6182
 semiconductor_manufacturing     patent_0de7bd74babd84ad.txt 0de7bd74babd84ad              True                 True                0               4320
 semiconductor_manufacturing     patent_1100870c16e735b7.txt 1100870c16e735b7              True                 True                0               6723
 semiconductor_manufacturing     patent_1282abd57d11596d.txt 1282abd57d11596d              True                 True                0               2373
 semiconductor_manufacturing     patent_1578a5246a7954e8.txt 1578a5246a7954e8              True                 True                0               6545
 semiconductor_manufacturing     patent_16404fefd5f074ce.txt 16404fefd5f074ce              True                 True                0               2720
 semiconductor_manufacturing     patent_17e4201e1f86c8e5.txt 17e4201e1f86c8e5              True                 True                0               5238
 semiconductor_manufacturing     patent_18f91dc4b80d8fd1.txt 18f91dc4b80d8fd1              True                 True                0               6031
 semiconductor_manufacturing     patent_19caaa6bc34a70c6.txt 19caaa6bc34a70c6              True                 True                0               3365
 semiconductor_manufacturing     patent_1bb8000b82dd6a58.txt 1bb8000b82dd6a58              True                 True                0               4342
 semiconductor_manufacturing     patent_1bc765dc24dc5424.txt 1bc765dc24dc5424              True                 True                0              36025
 semiconductor_manufacturing     patent_1bf06fee96763105.txt 1bf06fee96763105              True                 True                0              15353
 semiconductor_manufacturing     patent_212cd02192d57c99.txt 212cd02192d57c99              True                 True                0               5732
 semiconductor_manufacturing     patent_262bd73a2676a8e0.txt 262bd73a2676a8e0              True                 True                0               6611
 semiconductor_manufacturing     patent_269632ad34ad43bc.txt 269632ad34ad43bc              True                 True                0               7245
 semiconductor_manufacturing     patent_2827574589b53c92.txt 2827574589b53c92              True                 True                0               6370
 semiconductor_manufacturing     patent_28dd2ac99a639b83.txt 28dd2ac99a639b83              True                 True                0               6141
 semiconductor_manufacturing     patent_2bc457097e510e45.txt 2bc457097e510e45              True                 True                0               3254
 semiconductor_manufacturing     patent_2cab2d48e88b2445.txt 2cab2d48e88b2445              True                 True                0               2113
 semiconductor_manufacturing     patent_2cf1556a6b03be0b.txt 2cf1556a6b03be0b              True                 True                0               5097
 semiconductor_manufacturing     patent_3131f76550dd5651.txt 3131f76550dd5651              True                 True                0               4444
 semiconductor_manufacturing     patent_314e6fbf36ed8c71.txt 314e6fbf36ed8c71              True                 True                0               6201
 semiconductor_manufacturing     patent_31887fd9b9e5f8e0.txt 31887fd9b9e5f8e0              True                 True                0               2175
 semiconductor_manufacturing     patent_36650e42d7965c99.txt 36650e42d7965c99              True                 True                0               4684
 semiconductor_manufacturing     patent_37ba118829e41c40.txt 37ba118829e41c40              True                 True                0               4414
 semiconductor_manufacturing     patent_3b079a6eafd904bb.txt 3b079a6eafd904bb              True                 True                0               5149
 semiconductor_manufacturing     patent_3c868c9fef5f6f4d.txt 3c868c9fef5f6f4d              True                 True                0               3774
 semiconductor_manufacturing     patent_3ecc56a344f0b78d.txt 3ecc56a344f0b78d              True                 True                0               9790
 semiconductor_manufacturing     patent_43c5972ffc804044.txt 43c5972ffc804044              True                 True                0               4525
 semiconductor_manufacturing     patent_47bec6d9eb0dae35.txt 47bec6d9eb0dae35              True                 True                0              10370
 semiconductor_manufacturing     patent_485eee39877d3c8f.txt 485eee39877d3c8f              True                 True                0               4647
 semiconductor_manufacturing     patent_48af976909bb2edf.txt 48af976909bb2edf              True                 True                0               7165
 semiconductor_manufacturing     patent_48f16381a2efaae4.txt 48f16381a2efaae4              True                 True                0               6214
 semiconductor_manufacturing     patent_49ba0ce3f3bb776d.txt 49ba0ce3f3bb776d              True                 True                0               3258
 semiconductor_manufacturing     patent_4b7ba1429b2c767d.txt 4b7ba1429b2c767d              True                 True                0               4420
 semiconductor_manufacturing     patent_4ffa11fa311196cb.txt 4ffa11fa311196cb              True                 True                0               6810
 semiconductor_manufacturing     patent_563cfb834a86b476.txt 563cfb834a86b476              True                 True                0               4660
 semiconductor_manufacturing     patent_57a2154e1432fa6a.txt 57a2154e1432fa6a              True                 True                0               4989
 semiconductor_manufacturing     patent_5ef2ecdfd4a2573b.txt 5ef2ecdfd4a2573b              True                 True                0               3345
 semiconductor_manufacturing     patent_617d979429b246c3.txt 617d979429b246c3              True                 True                0               2718
 semiconductor_manufacturing     patent_678e9b7f28681857.txt 678e9b7f28681857              True                 True                0               2618
 semiconductor_manufacturing     patent_6850d7fe493a62bc.txt 6850d7fe493a62bc              True                 True                0               8299
 semiconductor_manufacturing     patent_6965a8e689c9bc2d.txt 6965a8e689c9bc2d              True                 True                0               3294
 semiconductor_manufacturing     patent_700200523f2a9683.txt 700200523f2a9683              True                 True                0               7003
 semiconductor_manufacturing     patent_705e4ab08d381edd.txt 705e4ab08d381edd              True                 True                0               1913
 semiconductor_manufacturing     patent_7158af7d72b65b38.txt 7158af7d72b65b38              True                 True                0               6506
 semiconductor_manufacturing     patent_71f3e926e9b0e7dc.txt 71f3e926e9b0e7dc              True                 True                0               5249
 semiconductor_manufacturing     patent_74d4361534064d4e.txt 74d4361534064d4e              True                 True                0               3701
 semiconductor_manufacturing     patent_7a624e78d2ae6904.txt 7a624e78d2ae6904              True                 True                0               4421
 semiconductor_manufacturing     patent_7c37045f028763e9.txt 7c37045f028763e9              True                 True                0               2708
 semiconductor_manufacturing     patent_8443327a796a0dba.txt 8443327a796a0dba              True                 True                0               5299
 semiconductor_manufacturing     patent_84cd2c67ce6d4de8.txt 84cd2c67ce6d4de8              True                 True                0               5530
 semiconductor_manufacturing     patent_86487f0381ff631b.txt 86487f0381ff631b              True                 True                0               6252
 semiconductor_manufacturing     patent_8b3f6bc5b8c49ab6.txt 8b3f6bc5b8c49ab6              True                 True                0               3660
 semiconductor_manufacturing     patent_8d94ed3a7a5f4d05.txt 8d94ed3a7a5f4d05              True                 True                0               2176
 semiconductor_manufacturing     patent_8f70b816c3396a3b.txt 8f70b816c3396a3b              True                 True                0               3210
 semiconductor_manufacturing     patent_900361500e61fa81.txt 900361500e61fa81              True                 True                0               4622
 semiconductor_manufacturing     patent_92c94cf0ccd129cf.txt 92c94cf0ccd129cf              True                 True                0               6838
 semiconductor_manufacturing     patent_933c615956cd4cdc.txt 933c615956cd4cdc              True                 True                0               4468
 semiconductor_manufacturing     patent_9366f86074a14be0.txt 9366f86074a14be0              True                 True                0               3778
 semiconductor_manufacturing     patent_9531987ed27d67c4.txt 9531987ed27d67c4              True                 True                0               4491
 semiconductor_manufacturing     patent_96ac3c571e069c3e.txt 96ac3c571e069c3e              True                 True                0               2885
 semiconductor_manufacturing     patent_983e23132a178038.txt 983e23132a178038              True                 True                0               3163
 semiconductor_manufacturing     patent_9ab14745880632e7.txt 9ab14745880632e7              True                 True                0               3494
 semiconductor_manufacturing     patent_9b7d69d3737a9814.txt 9b7d69d3737a9814              True                 True                0               6105
 semiconductor_manufacturing     patent_a3a8ea361a3306b2.txt a3a8ea361a3306b2              True                 True                0               6332
 semiconductor_manufacturing     patent_a85cdd8341138002.txt a85cdd8341138002              True                 True                0               7418
 semiconductor_manufacturing     patent_b5566216549f458c.txt b5566216549f458c              True                 True                0               2351
 semiconductor_manufacturing     patent_b595d46abf3a238c.txt b595d46abf3a238c              True                 True                0               5228
 semiconductor_manufacturing     patent_b73cb9627eaa5a7b.txt b73cb9627eaa5a7b              True                 True                0               3710
 semiconductor_manufacturing     patent_b9e096d7d6789b90.txt b9e096d7d6789b90              True                 True                0               4702
 semiconductor_manufacturing     patent_bb74c7e53c942153.txt bb74c7e53c942153              True                 True                0               4441
 semiconductor_manufacturing     patent_be2d4e0e99639efa.txt be2d4e0e99639efa              True                 True                0               3936
 semiconductor_manufacturing     patent_be621f8e4e74dca0.txt be621f8e4e74dca0              True                 True                0               2773
 semiconductor_manufacturing     patent_c61971e471702770.txt c61971e471702770              True                 True                0               5462
 semiconductor_manufacturing     patent_cbf25749cea5a310.txt cbf25749cea5a310              True                 True                0               3250
 semiconductor_manufacturing     patent_d1d573436c19f0ae.txt d1d573436c19f0ae              True                 True                0              23219
 semiconductor_manufacturing     patent_d1f78ddc274c68b5.txt d1f78ddc274c68b5              True                 True                0               5730
 semiconductor_manufacturing     patent_d345057c118bb519.txt d345057c118bb519              True                 True                0               6844
 semiconductor_manufacturing     patent_d3ead82de489632b.txt d3ead82de489632b              True                 True                0               4787
 semiconductor_manufacturing     patent_d7c35a862fab77fc.txt d7c35a862fab77fc              True                 True                0               5704
 semiconductor_manufacturing     patent_e217d3e85851599b.txt e217d3e85851599b              True                 True                0               6044
 semiconductor_manufacturing     patent_e3fd905cfcd24b3e.txt e3fd905cfcd24b3e              True                 True                0               4027
 semiconductor_manufacturing     patent_e4781bcd50e6fff6.txt e4781bcd50e6fff6              True                 True                0               9210
 semiconductor_manufacturing     patent_efb67f1f99252cc1.txt efb67f1f99252cc1              True                 True                0               6850
 semiconductor_manufacturing     patent_f11b8856dd9777f7.txt f11b8856dd9777f7              True                 True                0               3485
 semiconductor_manufacturing     patent_f76d125c1bdeabc3.txt f76d125c1bdeabc3              True                 True                0              17462
 semiconductor_manufacturing     patent_fc6dd23f9fc2efc1.txt fc6dd23f9fc2efc1              True                 True                0               3283
 semiconductor_manufacturing     patent_fd20a12f885f4999.txt fd20a12f885f4999              True                 True                0               1766
 semiconductor_manufacturing     patent_fe6e3f2bd87fa7a7.txt fe6e3f2bd87fa7a7              True                 True                0               6321
 semiconductor_manufacturing     patent_feaad1791128e631.txt feaad1791128e631              True                 True                0               4442
transistor_device_technology     patent_000a442355b67fd1.txt 000a442355b67fd1              True                 True                0               6328
transistor_device_technology     patent_0091d26ac8fe4c88.txt 0091d26ac8fe4c88              True                 True                0               5751
transistor_device_technology     patent_034501f4ef2b8771.txt 034501f4ef2b8771              True                 True                0               6977
transistor_device_technology     patent_03cea21e92af4a21.txt 03cea21e92af4a21              True                 True                0               3428
transistor_device_technology     patent_04bffbe04ecf8ecb.txt 04bffbe04ecf8ecb              True                 True                0               3284
transistor_device_technology     patent_04f3ff1757654ed5.txt 04f3ff1757654ed5              True                 True                0               4972
transistor_device_technology     patent_0e56e9f3b7366655.txt 0e56e9f3b7366655              True                 True                0               4034
transistor_device_technology     patent_0ea0b2561ae3c665.txt 0ea0b2561ae3c665              True                 True                0               1907
transistor_device_technology     patent_0f118c8506dcf2de.txt 0f118c8506dcf2de              True                 True                0               2003
transistor_device_technology     patent_0fa825489db5d695.txt 0fa825489db5d695              True                 True                0               6149
transistor_device_technology     patent_14e546e1f6d1159f.txt 14e546e1f6d1159f              True                 True                0               2839
transistor_device_technology     patent_1649dcd349240c6c.txt 1649dcd349240c6c              True                 True                0               2469
transistor_device_technology     patent_16534c99ec1e19e6.txt 16534c99ec1e19e6              True                 True                0               4808
transistor_device_technology     patent_1e81f683906b557a.txt 1e81f683906b557a              True                 True                0               6589
transistor_device_technology     patent_1ff4c7ed0c45851c.txt 1ff4c7ed0c45851c              True                 True                0               5234
transistor_device_technology     patent_20780eaa18a2d624.txt 20780eaa18a2d624              True                 True                0               5247
transistor_device_technology     patent_20a9d819944a261d.txt 20a9d819944a261d              True                 True                0               3351
transistor_device_technology     patent_21b5b7040a36f013.txt 21b5b7040a36f013              True                 True                0               5743
transistor_device_technology     patent_2d885192c4ace0d2.txt 2d885192c4ace0d2              True                 True                0               5264
transistor_device_technology     patent_2ee33d15576ff547.txt 2ee33d15576ff547              True                 True                0               2526
transistor_device_technology     patent_310f724d5a565e2c.txt 310f724d5a565e2c              True                 True                0               7680
transistor_device_technology     patent_31c8714a68d336e1.txt 31c8714a68d336e1              True                 True                0               2637
transistor_device_technology     patent_342ae1ca67f86878.txt 342ae1ca67f86878              True                 True                0               4313
transistor_device_technology     patent_36cbb2abaa55ff59.txt 36cbb2abaa55ff59              True                 True                0               3489
transistor_device_technology     patent_37651ad78d52b981.txt 37651ad78d52b981              True                 True                0               2542

In [5]:
missing_abstracts = audit[
    ~audit["abstract_present"]
]

print(missing_abstracts[
    ["category", "filename", "document_id"]
].to_string(index=False))

            category                        filename document_id
  advanced_packaging patent_01ea3f6e9244856597cb.txt
  advanced_packaging patent_03ca7ae1cca3f2ec2c26.txt
  advanced_packaging patent_04dc1c40cf1047041bea.txt
  advanced_packaging patent_0628719951bb1c732427.txt
  advanced_packaging patent_0b0ff476d868d28faab9.txt
  advanced_packaging patent_0c30900aee0b5eb4018e.txt
  advanced_packaging patent_0ee4a26e02799ad94449.txt
  advanced_packaging patent_11f96ffbb8a4144c74fd.txt
  advanced_packaging patent_1d665cb5eebdc0f2cea0.txt
  advanced_packaging patent_23ebeda5c273212c3bcd.txt
  advanced_packaging patent_24a95eaf36a613e9a7ec.txt
  advanced_packaging patent_26ba5ba2e4e5840b16e8.txt
  advanced_packaging patent_2d43ab40fc0eb9178499.txt
  advanced_packaging patent_313810c0b6e6e16b1b9b.txt
  advanced_packaging patent_348bc72dabfda8c4f30d.txt
  advanced_packaging patent_3afdad3d1f7343beec24.txt
  advanced_packaging patent_3d5e0281a6e4e66c129d.txt
  advanced_packaging patent_4003137b9f35e2eeed37.txt
  advanced_packaging patent_403a180868f181ccb1a0.txt
  advanced_packaging patent_44549d7b90b0b802940b.txt
  advanced_packaging patent_4850350772e589a84c1d.txt
  advanced_packaging patent_4df8da8c0de108b839d8.txt
  advanced_packaging patent_4f2d66a8ff98850380a6.txt
  advanced_packaging patent_516dbed38dec8d1cafee.txt
  advanced_packaging patent_51de540a07c2efbb0473.txt
  advanced_packaging patent_5469465e8f806fc2b1fe.txt
  advanced_packaging patent_56abec052abdcddc1635.txt
  advanced_packaging patent_5c06202f88b554e8144b.txt
  advanced_packaging patent_5f999f09718247ffaf8e.txt
  advanced_packaging patent_6001024cc3df05a76add.txt
  advanced_packaging patent_6412ebaec693a0105f28.txt
  advanced_packaging patent_65dfca353fb251a3aa39.txt
  advanced_packaging patent_6b565ef605bd2c8e8fb1.txt
  advanced_packaging patent_6ebfa06f472a9c0d84bc.txt
  advanced_packaging patent_7003d3f3c5a05c13a5f5.txt
  advanced_packaging patent_76434f47519817ba0c44.txt
  advanced_packaging patent_771bf7eb194ac469930b.txt
  advanced_packaging patent_77ef8db797ce48c60943.txt
  advanced_packaging patent_8b663cb7916ad2149bb5.txt
  advanced_packaging patent_8f954a54fe074893c736.txt
  advanced_packaging patent_95a68ed21542fb897275.txt
  advanced_packaging patent_96f7abd90e68e2663b9c.txt
  advanced_packaging patent_9bf8debd8e7fba4596e4.txt
  advanced_packaging patent_9fc9b5878271526481ab.txt
  advanced_packaging patent_a404be781c021e2050e3.txt
  advanced_packaging patent_a412f1b3ea8b5836df4b.txt
  advanced_packaging patent_a969f5fbe709d62ce477.txt
  advanced_packaging patent_aa0fc1c39468046ea250.txt
  advanced_packaging patent_b06f9329102f3dfb4662.txt
  advanced_packaging patent_b1aaa836bc3709df1d70.txt
  advanced_packaging patent_b4241cf376b4b042f00a.txt
  advanced_packaging patent_b5c72da07a4f6d3ca31c.txt
  advanced_packaging patent_b8ead524636a26d39526.txt
  advanced_packaging patent_be1f8e667484e2e2008a.txt
  advanced_packaging patent_cb770cd2bd4fad95a079.txt
  advanced_packaging patent_d6b919ccb69b6b48ba28.txt
  advanced_packaging patent_da2d58c881907dcfe7fc.txt
  advanced_packaging patent_e50c49015d5992d18558.txt
  advanced_packaging patent_e60f38aa7867952efa9d.txt
  advanced_packaging patent_eefc1d7d4aa24261c904.txt
  advanced_packaging patent_ef83713cbacd7d14b148.txt
  advanced_packaging patent_f129a885d93007f261b9.txt
  advanced_packaging patent_f2ada019c57f2835065e.txt
  advanced_packaging patent_fcb4c0a0a3276d0e7ea5.txt
power_semiconductors patent_752bf09847b4d6e0c893.txt
power_semiconductors patent_98f85369e3a2b0e19f3f.txt
power_semiconductors patent_acef934600e2200be285.txt
power_semiconductors patent_f35c2ceaa96390e72ec7.txt
power_semiconductors patent_fb8e9dd287fb2e8aa1d1.txt

In [6]:
print("\nActual duplicate non-empty IDs:")

dupes = audit[
    (audit["document_id"] != "") &
    audit["document_id"].duplicated(keep=False)
]

print(dupes[
    ["category", "filename", "document_id"]
].sort_values("document_id").to_string(index=False))

Actual duplicate non-empty IDs:
Empty DataFrame
Columns: [category, filename, document_id]
Index: []

In [7]:
path = CORPUS_ROOT / "advanced_packaging" / "patent_01ea3f6e9244856597cb.txt"

text = path.read_text(encoding="utf-8", errors="replace")

print(text[:5000])

PATENT DOCUMENT
================

DOCUMENT ID: 01ea3f6e9244856597cb
CPC SECTION: H
CATEGORY: advanced_packaging
SOURCE: BIGPATENT

ABSTRACT
========

Embodiments of the invention include a semiconductor integrated circuit package that includes a substrate having an integrated circuit die attached thereto. The package includes a ESD shield attached to the substrate. The ESD shield configured to increase the ESD hardness of the package. The ESD shield can further serve to stiffen the package to prevent warping and operate as a heat spreader.

DETAILED DESCRIPTION
====================

TECHNICAL FIELD
 The invention described herein relates generally to semiconductor device packaging. In particular, the invention relates to a method and package for a semiconductor device that is resistant to electrostatic discharge that can be caused by various factors.
 BACKGROUND
 The semiconductor industry makes wide use of standard BGA (ball grid array) type semiconductor packages. Such packages generally include a BT (bismaleimide triazine) core having various metallization and solder mask layers to form the substrate. A semiconductor die is attached to the substrate and electrically connected to various electrical connections of the substrate using ball attach or wire-bonding techniques. The wire bonds and the die are typically encapsulated with a protective layer of encapsulant. Such packages and the methods of their construction are well known to persons having ordinary skill in the semiconductor packaging arts. Additionally, ball attach arrangements are provided with an underfill encapsulant to protect the bonding arrangements of the solder balls.
 Commonly, the packages are then provided with a stiffener and a heat spreader to complete the packages. These completed packages are then subject to a series of tests used to qualify the packages to insure they meet all the necessary specifications prior to shipping.
 One such test subjects the package to a series of electrostatic discharge (ESD) events to determine the packages robustness and resistance to these ESD events. In the present art, each of the ball pins of a ball grid array type package are tested for charge coupled electrostatic discharge failures. To alleviate this problem each die includes shunt circuitry associated with each external connection. One purpose of this shunt circuitry is to provide a level of resistance to ESD events.
 Commonly, testing is done using a device specifically constructed for administering such testing. One example of such a tester is an Orion CDM Tester produced by Oryx Instruments Corporation of Fremont, Calif. Such equipment can be programmed to implement testing for compliance in accordance with a number of test standards. Typical examples being provided by the JEDEC, AEC, and ESDA standards as well as others. One particular standard being JEDEC No. JESD22-C101C.
 FIG. 1 is a simplified schematic cross-section view of a portion of a standard PBGA (plastic ball grid array) package 101 arranged on a tester. Commonly, such packages 101 include a substrate 102 or core. The core is typically sandwiched between two metallization layers which also include layers of solder mask. Most commonly, the core 102 is formed of fiber material suspended in a cured a BT resin material. This core 102 is then treated to form metallization layers. Commonly, copper materials or coated copper materials are used. Other conductive materials are also used. A solder mask layer is then formed over the metallization layers. Typically, the solder mask layer is photolithographically patterned to create a solder mask that can be used to define a corresponding pattern in the metallization layers. Such substrates are commonly very thin, for example, less than about 0.60 mm thick. The methods of accomplishing this are very well known to those having ordinary skill in the art
 With continued reference to FIG. 1 , the substrate 102 forms part of a semiconductor package 101 . Ball attach pads are typically formed on a backside 105 surface of the substrate 102 . Solder balls 115 are typically formed on the ball attach pads. Additionally, a semiconductor integrated circuit die 110 is mounted to the front side 106 surface of the substrate 102 . In many implementations, solder balls electrically connect the die 110 to associated electrical contact points on the substrate 101 . Vias (not shown in this simplified view) formed in and through the substrate 102 enable the electrical communication between circuitry of the die 110 and the solder balls 115 mounted on the backside 105 of the package 101 . The die and electrical connections at the interface between the die 110 and substrate 102 are commonly encapsulated in a protective layer 112 of encapsulating underfill material.
 Additionally, many prior art devices include a metal stiffener 103 and a heat spreaders 104 . Such elements are known to persons having ordinary skill in the art.
 With continued reference to

In [8]:
from pathlib import Path
import re
import pandas as pd

records = []

for category in CATEGORIES:
    category_dir = CORPUS_ROOT / category

    for path in sorted(category_dir.glob("*.txt")):
        text = path.read_text(encoding="utf-8", errors="replace")

        # Handle both BIGPATENT formats:
        # DOCUMENT_ID: xxx
        # DOCUMENT ID: xxx
        m = re.search(r"DOCUMENT[_ ]ID:\s*(\S+)", text, re.IGNORECASE)
        document_id = m.group(1).strip() if m else path.stem.replace("patent_", "")

        # CPC
        m = re.search(r"CPC(?:[_ ]SECTION)?:\s*(\S+)", text, re.IGNORECASE)
        cpc_section = m.group(1).strip() if m else ""

        # Source
        m = re.search(r"(?:DATASET|SOURCE):\s*(\S+)", text, re.IGNORECASE)
        source = m.group(1).strip() if m else "BIGPATENT"

        # Abstract
        abstract_match = re.search(
            r"ABSTRACT\s*\n=+\s*\n(.*?)(?=\n(?:DESCRIPTION|DETAILED DESCRIPTION)\s*\n=+)",
            text,
            re.DOTALL | re.IGNORECASE,
        )

        abstract = (
            abstract_match.group(1).strip()
            if abstract_match
            else ""
        )

        # Description
        description_match = re.search(
            r"(?:DESCRIPTION|DETAILED DESCRIPTION)\s*\n=+\s*\n(.*)",
            text,
            re.DOTALL | re.IGNORECASE,
        )

        description = (
            description_match.group(1).strip()
            if description_match
            else ""
        )

        records.append({
            "document_id": document_id,
            "category": category,
            "cpc_section": cpc_section,
            "source": source,
            "abstract": abstract,
            "description": description,
            "abstract_words": len(abstract.split()),
            "description_words": len(description.split()),
        })

normalized = pd.DataFrame(records)

print("=" * 70)
print("NORMALIZED CORPUS")
print("=" * 70)

print(f"\nRecords: {len(normalized)}")

print("\nMissing:")
print(normalized[[
    "document_id",
    "abstract",
    "description",
    "cpc_section"
]].isna().sum())

print("\nEmpty:")
print("Document IDs:", (normalized["document_id"] == "").sum())
print("Abstracts:", (normalized["abstract"] == "").sum())
print("Descriptions:", (normalized["description"] == "").sum())
print("CPC sections:", (normalized["cpc_section"] == "").sum())

print("\nDuplicate document IDs:")
print(
    normalized["document_id"].duplicated().sum()
)

print("\nCategory counts:")
print(normalized["category"].value_counts().sort_index())

======================================================================
NORMALIZED CORPUS
======================================================================

Records: 500

Missing:
document_id    0
abstract       0
description    0
cpc_section    0
dtype: int64

Empty:
Document IDs: 0
Abstracts: 0
Descriptions: 0
CPC sections: 431

Duplicate document IDs:
0

Category counts:
category
advanced_packaging               75
ai_advanced_semiconductor        50
memory                           75
photonics                        50
power_semiconductors             50
semiconductor_manufacturing     100
transistor_device_technology    100
Name: count, dtype: int64

In [123]:
NORMALIZED_FILE = CORPUS_ROOT / "normalized_patents.csv"

normalized.to_csv(
    NORMALIZED_FILE,
    index=False
)

print(f"Saved normalized corpus to:")
print(NORMALIZED_FILE)
print(f"Records saved: {len(normalized)}")

Saved normalized corpus to:
/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/normalized_patents.csv
Records saved: 500

In [124]:
print("\nSaved file exists:", NORMALIZED_FILE.exists())
print("File size:", round(NORMALIZED_FILE.stat().st_size / 1024**2, 2), "MB")

Saved file exists: True
File size: 15.59 MB

In [10]:
# STEP 2 — Inspect normalized patent corpus structure

import re
from collections import Counter

# ---------------------------------------------------------
# 1. BASIC DATASET INSPECTION
# ---------------------------------------------------------

print("=" * 100)
print("NORMALIZED DATASET")
print("=" * 100)

print("Shape:", normalized.shape)

print("\nColumns:")
print(normalized.columns.tolist())

print("\nData types:")
print(normalized.dtypes)

print("\nDescription word-count distribution:")
print(normalized["description_words"].describe())

print("\nAbstract word-count distribution:")
print(normalized["abstract_words"].describe())

print("\nCPC sections:")
print(normalized["cpc_section"].value_counts())

print("\nCategories:")
print(normalized["category"].value_counts())


# ---------------------------------------------------------
# 2. INSPECT REAL DOCUMENTS
# ---------------------------------------------------------

print("\n\n" + "=" * 100)
print("SAMPLE DOCUMENTS")
print("=" * 100)

sample_indices = [0, 100, 300]

for i in sample_indices:
    row = normalized.iloc[i]

    print("\n" + "=" * 100)
    print("DOCUMENT:", row["document_id"])
    print("CATEGORY:", row["category"])
    print("CPC:", row["cpc_section"])
    print("SOURCE:", row["source"])

    print("\nABSTRACT:")
    print(row["abstract"][:1500])

    print("\nDESCRIPTION START:")
    print(row["description"][:4000])


# ---------------------------------------------------------
# 3. DETECT APPARENT SECTION HEADINGS
# ---------------------------------------------------------

print("\n\n" + "=" * 100)
print("APPARENT SECTION HEADINGS")
print("=" * 100)

headings = Counter()

for text in normalized["description"]:
    matches = re.findall(
        r"(?im)^\s*([A-Z][A-Z0-9 ,/&()\-]{3,80})\s*$",
        text
    )

    for heading in matches:
        headings[heading.strip()] += 1

print("\nMost common apparent section headings:")

for heading, count in headings.most_common(30):
    print(f"{count:4}  {heading}")


# ---------------------------------------------------------
# 4. CHECK FOR PARAGRAPH MARKERS
# ---------------------------------------------------------

paragraph_marker_count = 0
documents_with_markers = 0

for text in normalized["description"]:
    matches = re.findall(r"\[\d{4}\]", text)

    if matches:
        documents_with_markers += 1
        paragraph_marker_count += len(matches)

print("\n\n" + "=" * 100)
print("PARAGRAPH MARKER CHECK")
print("=" * 100)

print("Documents with [0000]-style markers:", documents_with_markers)
print("Total paragraph markers:", paragraph_marker_count)


# ---------------------------------------------------------
# 5. IDENTIFY VERY LONG DOCUMENTS
# ---------------------------------------------------------

print("\n\n" + "=" * 100)
print("LONGEST DOCUMENTS")
print("=" * 100)

longest = normalized.nlargest(10, "description_words")[
    [
        "document_id",
        "category",
        "description_words"
    ]
]

print(longest.to_string(index=False))


# ---------------------------------------------------------
# 6. FINAL SUMMARY
# ---------------------------------------------------------

print("\n\n" + "=" * 100)
print("INSPECTION COMPLETE")
print("=" * 100)

print(f"Documents: {len(normalized)}")
print(f"Categories: {normalized['category'].nunique()}")
print(f"CPC sections: {normalized['cpc_section'].nunique()}")
print(
    f"Average description length: "
    f"{normalized['description_words'].mean():.0f} words"
)
print(
    f"Median description length: "
    f"{normalized['description_words'].median():.0f} words"
)
print(f"Documents with paragraph markers: {documents_with_markers}")
print(f"Detected heading patterns: {len(headings)}")

====================================================================================================
NORMALIZED DATASET
====================================================================================================
Shape: (500, 8)

Columns:
['document_id', 'category', 'cpc_section', 'source', 'abstract', 'description', 'abstract_words', 'description_words']

Data types:
document_id          object
category             object
cpc_section          object
source               object
abstract             object
description          object
abstract_words        int64
description_words     int64
dtype: object

Description word-count distribution:
count      500.000000
mean      5325.346000
std       3361.827365
min       1116.000000
25%       3342.500000
50%       4637.500000
75%       6309.750000
max      36025.000000
Name: description_words, dtype: float64

Abstract word-count distribution:
count    500.000000
mean     113.022000
std       42.585309
min       28.000000
25%       81.750000
50%      110.000000
75%      141.000000
max      266.000000
Name: abstract_words, dtype: float64

CPC sections:
cpc_section
     431
H     69
Name: count, dtype: int64

Categories:
category
semiconductor_manufacturing     100
transistor_device_technology    100
memory                           75
advanced_packaging               75
power_semiconductors             50
photonics                        50
ai_advanced_semiconductor        50
Name: count, dtype: int64


====================================================================================================
SAMPLE DOCUMENTS
====================================================================================================

====================================================================================================
DOCUMENT: 035ed7683a8cf2c3
CATEGORY: semiconductor_manufacturing
CPC:
SOURCE: BIGPATENT

ABSTRACT:
A method for semiconductor device feature development using a bi-layer photoresist including providing a non-silicon containing photoresist layer over a substrate; providing a silicon containing photoresist over the non-silicon containing photoresist layer; exposing said silicon containing photoresist layer to an activating light source an exposure surface defined by an overlying pattern according to a photolithographic process; developing said silicon containing photoresist layer according to a photolithographic process to reveal a portion the non-silicon containing photoresist layer; and, dry developing said non-silicon containing photoresist layer in a plasma reactor by igniting a plasma from an ambient mixture including at least oxygen, carbon monoxide, and argon.

DESCRIPTION START:
FIELD OF THE INVENTION [0001] This invention generally relates to photoresist methods for forming semiconductor features and more particularly to a bi-layer photoresist dry development method for high resolution features. BACKGROUND OF THE INVENTION [0002] In semiconductor fabrication, various layers of insulating material, semiconducting material and conducting material are formed to produce a multilayer semiconductor device. The layers are patterned to create features that taken together, form elements such as transistors, capacitors, and resistors. These elements are then interconnected to achieve a desired electrical function, thereby producing an integrated circuit (IC) device. The formation and patterning of the various device layers are achieved using conventional fabrication techniques, such as oxidation, implantation, deposition, epitaxial growth of silicon, lithography, etching, and planarization. [0003] As devices continue to shrink in size, the limits of processing technologies are reached requiring new and cost effective innovations. For example, acceptable photoresist imaging is one limiting technology that has required the adoption of new approaches as finer imaging resolutions are sought to meet the requirements of smaller device sizes. For example, single layer photoresist layers have the problem that they need both effective etching resistance and depth of focus (DOF) requirement. However, the former requirement calls for thicker photoresist layers while the latter requirement calls for thinner photoresist layers. One approach has been to move to bi-layer and tri-layer photoresist layers where the uppermost photoresist layer is used for imaging thereby allowing a thinner image layer and acceptable depth of focus (DOF) with a larger photo-window. Consequently, resolution, and pattern width control are enhanced. [0004] A corresponding requirement to achieve high resolution features and critical dimension control is an effective development process. Wet processing techniques have increasingly become inadequate due to several problems including photoresist poisoning of features by leaving undeveloped photoresist caused by either or both, step height limitations affecting the photo imaging process or by residual nitrogen contaminating species interfering with photoresist exposure and development processes. [0005] As such, dry development processes involving plasma etching have been increasingly adopted leading to improved etching profiles. However, dry etching (plasma etching) has demonstrated problems of its own including, for example, critical dimension bias between isolated and dense line areas where, due to microloading, isolated lines etch faster than dense lines leading to unacceptable differences in critical dimension. For example, in single layer photoresists, dry development of, for example, via holes, leads to roughened hole edges or “striation”. If a hard mask, such as a metal nitride, is used over the inter-layer dielectric (ILD) insulating layer, the via hole edges are tapered to wider dimension referred to as “top CD blow out”. Bi-layer approaches have led to some improvement in dry etching critical dimension control, however, further improvement is need in etching selectivity in dry development as resolution demands are increased, for example with 193 nm and 157 nm photoresists. [0006] For example, more recent shorter wavelength photoresist approaches have used a surface modification technique where the surface of a photoresist film is silylated after the exposure to light. Following exposure, a dry development process is used to form a pattern having good resolution and resistance to dry etching. According to this technique, an initial pattern is formed in a region of about 1000 Angstroms of thickness within of the photoresist film. The silylated surface layer is intended to protect the lower layer from premature etching thus resulting in better selectivity and smoother etching profiles following d

====================================================================================================
DOCUMENT: 000a442355b67fd1
CATEGORY: transistor_device_technology
CPC:
SOURCE: BIGPATENT

ABSTRACT:
To provide a magnetic sensor device which maintains accuracy thereof while reducing current consumption by switching drive power of a Hall element to two drive power. A magnetic sensor device is equipped with a driving circuit which supplies power to a sensor element, a switch changeover circuit which restricts the supply of the power from the driving circuit to the sensor element, a differential amplifier circuit which performs arithmetic processing on an output signal of the sensor element, a threshold voltage generating circuit which generates a threshold voltage used in magnetism determination, a comparison circuit which compares and determines a voltage of the differential amplifier circuit and the threshold voltage, and a logic circuit which according to the output of the comparison circuit, switches the power outputted from the driving circuit, switches the threshold voltage and controls on/off of the switch changeover circuit in a constant cycle.

DESCRIPTION START:
RELATED APPLICATIONS [0001] This application claims priority under 35 U.S.C. §119 to Japanese Patent Application Nos. 2014-131810 filed on Jun. 26, 2014 and 2015-056464 filed on Mar. 19, 2015, the entire content of which are hereby incorporated by reference. BACKGROUND OF THE INVENTION [0002] 1. Field of the Invention [0003] The present invention relates to a magnetic sensor device which converts a magnetic field intensity to an electric signal, and to a magnetic sensor device capable of attaining low power consumption while improving the accuracy of detecting a magnetic field. [0004] 2. Background Art [0005] FIG. 7 is a circuit diagram of a related art magnetic sensor device. The related art magnetic sensor device is equipped with a magnetic sensor circuit 710 , a CLK circuit 108 , an ONOFF control circuit 730 , and an output terminal 103 . The magnetic sensor circuit 710 is equipped with a sensor element 104 , a differential amplifier circuit 105 , a comparison circuit 106 , a latch circuit 704 , and an NMOS transistor 705 . [0006] FIG. 8 is a timing chart illustrating the operation of the related art magnetic sensor device. The CLK circuit 108 outputs a clock signal of such a certain cycle Tclk as illustrated in FIG. 8 . The ONOFF control circuit 730 generates a control signal having a cycle Tcycle from the clock signal and outputs it therefrom. The magnetic sensor circuit 710 performs an intermittent operation in a timing at which the control signal becomes H to realize low current consumption. [0007] The sensor element 104 outputs a Hall voltage according to a magnetic field or a magnetic flux density. The differential amplifier circuit 105 amplifies the Hall voltage, and the comparison circuit 106 outputs a detection/non-detection signal by comparing the Hall voltage and a certain voltage. The latch circuit 704 holds the detection/non-detection signal even during an off period of the intermittent operation. The NMOS transistor 705 is controlled in on/off by the output signal of the latch circuit 704 , which is inputted to a gate thereof. The output terminal 103 is connected with a pull-up resistor to thereby output an H/L signal corresponding to the presence or absence of the magnetic field or magnetic flux density, whereby the magnetic sensor circuit 710 of low current consumption is realized (refer to, for example, Patent Document 1, FIG. 2). [0008] [Patent Document 1] Japanese Patent Application Laid-Open No. 2006-153699 SUMMARY OF THE INVENTION [0009] The related art magnetic sensor device was however accompanied by a problem that when power consumption was further reduced after the execution of the intermittent operation, it was difficult to maintain the accuracy of the magnetic sensor device. [0010] The present invention has been invented to solve the foregoing problem and provides a magnetic sensor device which maintains accuracy thereof while reducing current consumption by switching drive power of a Hall element to two drive power. [0011] To solve the related art problem, a magnetic sensor device of the present invention is configured as follows: [0012] There is provided a magnetic sensor device which provides a logic output according to the intensity of a magnetic field applied to a sensor element and which is equipped with a driving circuit which supplies power to the sensor element, a switch changeover circuit which restricts the supply of the power from the driving circuit to the sensor element, a differential amplifier circuit which performs arithmetic processing on an output signal of the sensor element, a threshold voltage generating circuit which generates a threshold voltage corresponding to a predetermined intensity of applied magnetic field, which is used in magnetism determination, a comparison circuit which compares and determines the relationship of magnitude between a voltage of the differential amplifier circuit and the threshold voltage generated by the threshold voltage generating circuit, and

====================================================================================================
DOCUMENT: 516dbed38dec8d1cafee
CATEGORY: advanced_packaging
CPC: H
SOURCE: BIGPATENT

ABSTRACT:
A light emitting die package is disclosed. The die package includes a substrate, a reflector plate, and a lens. The substrate is made from thermally conductive but electrically insulating material. The substrate has traces for connecting an external electrical power source to a light emitting diode (LED) at a mounting pad. The reflector plate is coupled to the substrate and substantially surrounds the mounting pad. The lens is free to move relative to the reflector plate and is capable of being raised or lowered by the encapsulant that wets and adheres to it and is placed at an optimal distance from the LED chip(s). The lens can be coated with any optical system of chemical that affects the performance of the device. Heat generated by the LED during operation is drawn away from the LED by both the substrate (acting as a bottom heat sink) and the reflector plate (acting as a top heat sink). The reflector plate includes a reflective surface to direct light from the LED in a desired direction.

DESCRIPTION START:
PRIORITY
 [0001] This application claims the benefit of U.S. Provisional Patent Application No. 60/408,254 filed Sep. 4, 2002 entitled “Power-SMT, LED Package with Dual Heat-Sinks and an Optical System or Chemical-Coated Lens.”



 BACKGROUND
 [0002] The present invention relates to the field of packaging semiconductor devices, and more particularly to packaging light emitting diodes.
 [0003] Light emitting diodes (LEDS) are often packaged within leadframe packages. A leadframe package typically includes a molded or cast plastic body that encapsulates an LED, a lens portion, and thin metal leads connected to the LED and extending outside the body. The metal leads of the leadframe package serve as the conduit to supply the LED with electrical power and, at the same time, may act to draw heat away from the LED. Heat is generated by the LED when power is applied to the LED to produce light. A portion of the leads extends out from the package body for connection to circuits external to the leadframe package.
 [0004] Some of the heat generated by the LED is dissipated by the plastic package body; however, most of the heat is drawn away from the LED via the metal components of the package. The metal leads are typically very thin and has a small cross section. For this reason, capacity of the metal leads to remove heat from the LED is limited. This limits the amount of power that can be sent to the LED thereby limiting the amount of light that can be generated by the LED.
 [0005] To increase the capacity of an LED package to dissipate heat, in one LED package design, a heat sink slug is introduced into the package. The heat sink slug draws heat from the LED chip. Hence, it increases the capacity of the LED package to dissipate heat. However, this design introduces empty spaces within the package that is be filled with an encapsulant to protect the LED chip. Furthermore, due to significant differences in CTE (coefficient of thermal expansion) between various components inside the LED package, bubbles tend to form inside the encapsulant or the encapsulant tends to delaminate from various portions within the package. This adversely affects the light output and reliability of the product. In addition, this design includes a pair of flimsy leads which are typically soldered by a hot-iron. This manufacturing process is incompatible with convenient surface mounting technology (SMT) that is popular in the art of electronic board assembly.
 [0006] In another LED package design, the leads of the leadframe package have differing thicknesses extended (in various shapes and configurations) beyond the immediate edge of the LED package body. A thicker lead is utilized as a heat-spreader and the LED chip is mounted on it. This arrangement allows heat generated by the LED chip to dissipate through the thicker lead which is often connected to an external heat sink. This design is inherently unreliable due to significant difference in coefficient of thermal expansion (CTE) between the plastic body and the leadframe material. When subjected to temperature cycles, its rigid plastic body that adheres to the metal leads experiences high degree of thermal stresses in many directions. This potentially leads to various undesirable results such as cracking of the plastic body, separation of the plastic body from the LED chip, breaking of the bond wires, delaminating of the plastic body at the interfaces where it bonds to various parts, or resulting in a combination of these outcomes. In addition, the extended leads increase the package size and its footprint. For this reason, it is difficult to populate these LED packages in a dense cluster on a printed circuit board (PCB) to generate brighter light.
 [0007] Another disadvantage of the current leadframe design is that the thick lead cannot be made or stamped into a fine circuit for flip-chip mounting of a LED—which is commonly used by some manufacturers for cost-effective manufacturing and device pe


====================================================================================================
APPARENT SECTION HEADINGS
====================================================================================================

Most common apparent section headings:
  54  BRIEF DESCRIPTION OF THE DRAWINGS
  41  SUMMARY OF THE INVENTION
  41  BACKGROUND OF THE INVENTION
  21  BACKGROUND
  21  DETAILED DESCRIPTION OF THE INVENTION
  21  DETAILED DESCRIPTION
  20  FIELD OF THE INVENTION
  12  SUMMARY
   9  DETAILED DESCRIPTION OF THE PREFERRED EMBODIMENTS
   8  CROSS-REFERENCE TO RELATED APPLICATION
   6  CROSS REFERENCE TO RELATED APPLICATIONS
   6  CROSS-REFERENCE TO RELATED APPLICATIONS
   6  BRIEF SUMMARY OF THE INVENTION
   6  BRIEF DESCRIPTION OF DRAWINGS
   4  each R is independently hydrogen, alkyl or substituted alkyl,
   4  Dodecylbismaleimide
   4  DETAILED DESCRIPTION OF PREFERRED EMBODIMENTS
   4  BRIEF DESCRIPTION OF THE SEVERAL VIEWS OF THE DRAWINGS
   3  FIELD
   3  where
   3  X-BMI
   3  RICON 130
   3  Coupling agent
   3  BRIEF SUMMARY
   3  DETAILED DESCRIPTION OF THE EMBODIMENTS
   3  CROSS-REFERENCES TO RELATED APPLICATIONS
   2  TECHNICAL FIELD
   2  DESCRIPTION OF THE RELATED ART
   2  DETAILED DESCRIPTION OF THE PREFERRED EMBODIMENT
   2  CONCLUSION


====================================================================================================
PARAGRAPH MARKER CHECK
====================================================================================================
Documents with [0000]-style markers: 202
Total paragraph markers: 14809


====================================================================================================
LONGEST DOCUMENTS
====================================================================================================
     document_id                     category  description_words
1bc765dc24dc5424  semiconductor_manufacturing              36025
4d2b114a1cd76ef6                       memory              26940
1d05cc04c454c391    ai_advanced_semiconductor              26135
d1d573436c19f0ae  semiconductor_manufacturing              23219
09bee35e053c1254                    photonics              19515
b0d121e8f1149a6f                       memory              18496
778fce1420a792e0 transistor_device_technology              18108
f76d125c1bdeabc3  semiconductor_manufacturing              17462
1bf06fee96763105  semiconductor_manufacturing              15353
9e2bc3622813c613    ai_advanced_semiconductor              14803


====================================================================================================
INSPECTION COMPLETE
====================================================================================================
Documents: 500
Categories: 7
CPC sections: 2
Average description length: 5325 words
Median description length: 4638 words

In [11]:
# STEP 2 — Build RAG chunks

import re
import pandas as pd

CHUNK_SIZE = 500
CHUNK_OVERLAP = 75


# ---------------------------------------------------------
# 1. SECTION DETECTION
# ---------------------------------------------------------

HEADING_PATTERN = re.compile(
    r"(?im)^\s*([A-Z][A-Z0-9 ,/&()\-]{3,80})\s*$"
)

IGNORED_HEADINGS = {
    "ABSTRACT",
    "DESCRIPTION",
    "DETAILED DESCRIPTION",
}


def split_into_sections(text):

    matches = list(HEADING_PATTERN.finditer(text))

    if not matches:
        return [("DESCRIPTION", text.strip())]

    sections = []

    # Text before the first heading
    if matches[0].start() > 0:
        preamble = text[:matches[0].start()].strip()

        if preamble:
            sections.append(("DESCRIPTION", preamble))

    for i, match in enumerate(matches):

        heading = match.group(1).strip()

        if heading in IGNORED_HEADINGS:
            continue

        start = match.end()
        end = (
            matches[i + 1].start()
            if i + 1 < len(matches)
            else len(text)
        )

        section_text = text[start:end].strip()

        if section_text:
            sections.append((heading, section_text))

    if not sections:
        return [("DESCRIPTION", text.strip())]

    return sections


# ---------------------------------------------------------
# 2. CHUNK LONG SECTIONS
# ---------------------------------------------------------

def chunk_text(text, chunk_size=CHUNK_SIZE, overlap=CHUNK_OVERLAP):

    words = text.split()

    if len(words) <= chunk_size:
        return [text.strip()]

    chunks = []
    step = chunk_size - overlap

    for start in range(0, len(words), step):

        end = start + chunk_size

        chunk = " ".join(words[start:end]).strip()

        if chunk:
            chunks.append(chunk)

        if end >= len(words):
            break

    return chunks


# ---------------------------------------------------------
# 3. CREATE CHUNKS
# ---------------------------------------------------------

chunks = []

for _, row in normalized.iterrows():

    document_id = row["document_id"]
    abstract = row["abstract"].strip()

    # -----------------------------------------------------
    # ABSTRACT CHUNK
    # -----------------------------------------------------

    if abstract:

        chunks.append({
            "document_id": document_id,
            "category": row["category"],
            "cpc_section": row["cpc_section"],
            "source": row["source"],
            "section": "ABSTRACT",
            "chunk_index": 0,
            "abstract": abstract,
            "text": abstract,
            "word_count": len(abstract.split()),
        })

    # -----------------------------------------------------
    # DESCRIPTION CHUNKS
    # -----------------------------------------------------

    sections = split_into_sections(row["description"])

    chunk_index = 1

    for section_name, section_text in sections:

        section_chunks = chunk_text(section_text)

        for part_number, chunk in enumerate(section_chunks, start=1):

            chunks.append({
                "document_id": document_id,
                "category": row["category"],
                "cpc_section": row["cpc_section"],
                "source": row["source"],
                "section": section_name,
                "chunk_index": chunk_index,
                "part": part_number,
                "abstract": abstract,
                "text": chunk,
                "word_count": len(chunk.split()),
            })

            chunk_index += 1


# ---------------------------------------------------------
# 4. DATAFRAME
# ---------------------------------------------------------

chunks_df = pd.DataFrame(chunks)

chunks_df["chunk_id"] = (
    chunks_df["document_id"].astype(str)
    + "_"
    + chunks_df["chunk_index"].astype(str)
)


# ---------------------------------------------------------
# 5. SANITY CHECK
# ---------------------------------------------------------

print("Chunking complete")
print("-" * 50)
print("Documents:", normalized["document_id"].nunique())
print("Total chunks:", len(chunks_df))
print(
    "Average chunks/document:",
    round(len(chunks_df) / normalized["document_id"].nunique(), 1)
)
print(
    "Average words/chunk:",
    round(chunks_df["word_count"].mean(), 1)
)

print("\nChunk types:")
print(chunks_df["section"].value_counts().head(10))

print("\nColumns:")
print(chunks_df.columns.tolist())

print("\nSample:")
print(
    chunks_df[
        [
            "document_id",
            "category",
            "section",
            "word_count"
        ]
    ].head(5).to_string(index=False)
)

Chunking complete
--------------------------------------------------
Documents: 500
Total chunks: 6964
Average chunks/document: 13.9
Average words/chunk: 442.6

Chunk types:
section
DESCRIPTION                                          5641
ABSTRACT                                              500
DETAILED DESCRIPTION OF THE INVENTION                 144
BACKGROUND OF THE INVENTION                            84
SUMMARY OF THE INVENTION                               66
BRIEF DESCRIPTION OF THE DRAWINGS                      64
DETAILED DESCRIPTION OF THE PREFERRED EMBODIMENT       46
DETAILED DESCRIPTION OF THE PREFERRED EMBODIMENTS      39
BACKGROUND                                             29
DETAILED DESCRIPTION OF PREFERRED EMBODIMENTS          24
Name: count, dtype: int64

Columns:
['document_id', 'category', 'cpc_section', 'source', 'section', 'chunk_index', 'abstract', 'text', 'word_count', 'part', 'chunk_id']

Sample:
     document_id                    category     section  word_count
035ed7683a8cf2c3 semiconductor_manufacturing    ABSTRACT         104
035ed7683a8cf2c3 semiconductor_manufacturing DESCRIPTION         500
035ed7683a8cf2c3 semiconductor_manufacturing DESCRIPTION         500
035ed7683a8cf2c3 semiconductor_manufacturing DESCRIPTION         500
035ed7683a8cf2c3 semiconductor_manufacturing DESCRIPTION         500

In [12]:
# STEP 3A — Test embedding model

from sentence_transformers import SentenceTransformer
import numpy as np
import torch

MODEL_NAME = "BAAI/bge-base-en-v1.5"

# Detect available device
if torch.backends.mps.is_available():
    device = "mps"
elif torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

print("Device:", device)
print("Loading:", MODEL_NAME)

model = SentenceTransformer(
    MODEL_NAME,
    device=device
)

# Test with 10 real patent chunks
test_texts = chunks_df["text"].head(10).tolist()

test_embeddings = model.encode(
    test_texts,
    normalize_embeddings=True,
    show_progress_bar=False
)

print("\nEmbedding test passed")
print("Number of embeddings:", len(test_embeddings))
print("Embedding dimension:", test_embeddings.shape[1])
print("Data type:", test_embeddings.dtype)
print("Shape:", test_embeddings.shape)
print(
    "Norm of first embedding:",
    round(float(np.linalg.norm(test_embeddings[0])), 4)
)

/Users/jamesjr/anaconda3/envs/Genomics/lib/python3.8/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py:13: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange

Device: mps
Loading: BAAI/bge-base-en-v1.5

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding test passed
Number of embeddings: 10
Embedding dimension: 768
Data type: float32
Shape: (10, 768)
Norm of first embedding: 1.0

In [13]:
# STEP 3B — Embed the full patent corpus

import numpy as np

texts = chunks_df["text"].tolist()

print(f"Embedding {len(texts):,} chunks...")
print(f"Model: {MODEL_NAME}")
print(f"Device: {device}")

embeddings = model.encode(
    texts,
    batch_size=32,
    normalize_embeddings=True,
    show_progress_bar=True,
    convert_to_numpy=True,
)

# Store embeddings in memory
chunks_df["embedding"] = list(embeddings)

print("\nEmbedding complete")
print("-" * 50)
print("Chunks:", len(embeddings))
print("Dimensions:", embeddings.shape[1])
print("Shape:", embeddings.shape)
print("Dtype:", embeddings.dtype)

Embedding 6,964 chunks...
Model: BAAI/bge-base-en-v1.5
Device: mps

Batches:   0%|          | 0/218 [00:00<?, ?it/s]

Embedding complete
--------------------------------------------------
Chunks: 6964
Dimensions: 768
Shape: (6964, 768)
Dtype: float32

In [14]:
# STEP 4 — In-memory semantic retrieval

import numpy as np


def search_patents(query, top_k=5):
    """
    Semantic search directly against the in-memory embeddings.
    No database or vector store required.
    """

    # Embed query
    query_embedding = model.encode(
        query,
        normalize_embeddings=True,
        convert_to_numpy=True,
    )

    # Cosine similarity because embeddings are normalized
    scores = embeddings @ query_embedding

    # Top results
    top_indices = np.argsort(scores)[::-1][:top_k]

    results = chunks_df.iloc[top_indices].copy()
    results["similarity"] = scores[top_indices]

    return results.reset_index(drop=True)


# ---------------------------------------------------------
# TEST RETRIEVAL
# ---------------------------------------------------------

queries = [
    "advanced semiconductor packaging using through-silicon vias",
    "methods for improving transistor performance and reducing leakage",
    "DRAM memory cell architecture",
    "silicon photonics optical communication",
    "power semiconductor devices for high voltage applications",
]

for query in queries:

    print("\n" + "=" * 100)
    print("QUERY:", query)
    print("=" * 100)

    results = search_patents(query, top_k=3)

    for i, row in results.iterrows():

        print(f"\n[{i + 1}] Similarity: {row['similarity']:.4f}")
        print("Patent:", row["document_id"])
        print("Category:", row["category"])
        print("Section:", row["section"])
        print("Text:", row["text"][:500].replace("\n", " "))

====================================================================================================
QUERY: advanced semiconductor packaging using through-silicon vias
====================================================================================================

[1] Similarity: 0.7577
Patent: 6ebfa06f472a9c0d84bc
Category: advanced_packaging
Section: BACKGROUND
Text: [0001] Nanoscale technologies, similar to other technologies, face challenges in high power consumption and signal delay due to global interconnects, but due to their scope, addressing these challenges opens new areas of research. One research area is through silicon via (TSV) based 3D integrated chip (IC) technology, where each layer or stratum is fabricated separately and subsequently vertically integrated. With 3D ICs, the fabrication of disparate strata and the final system integration may b

[2] Similarity: 0.7358
Patent: 7003d3f3c5a05c13a5f5
Category: advanced_packaging
Section: BACKGROUND
Text: 1. Field of Invention   The present invention relates to integrated circuit packaging, and more particularly to multiple die packaging.   2. Related Art   Semiconductor die or chip packages are used to protect the semiconductor device (e.g., an integrated circuit chip) and allow the chip to be electrically connected to external circuitry. The chip typically has a surface containing active circuit elements that can be accessed via conductors on the chip, such as bonding pads. The chip can be pack

[3] Similarity: 0.7347
Patent: 03ca7ae1cca3f2ec2c26
Category: advanced_packaging
Section: BACKGROUND
Text: Semiconductor device is widely adopted in various applications. The geometry is trending down rapidly as user&#39;s demands increases on the performance and functionality. For example, a 3G mobile phone presented in the market is expected to be capable of telecommunicating, capturing images and processing high stream data. In order to fulfill the requirements, the 3G mobile phone needs to be equipped with different devices such as a processor, a memory and an image sensor in a limited space.   C

====================================================================================================
QUERY: methods for improving transistor performance and reducing leakage
====================================================================================================

[1] Similarity: 0.7758
Patent: 7a624e78d2ae6904
Category: semiconductor_manufacturing
Section: DESCRIPTION
Text: can be further reduced while completely intercepting the passage of current leakage at the D region. As described above, the black matrix is formed at the TFT array substrate with the pixel electrodes so that opening ratio of the device can be enhanced in a stable manner. The semiconductor pattern and the contact holes are formed together so that the processing steps can be simplified. Possible leakage of current can be prevented at the non-channel area using the black matrix. Furthermore, a buf

[2] Similarity: 0.7610
Patent: 5ef5ac357b2ad1cd
Category: transistor_device_technology
Section: DESCRIPTION
Text: ΔV BN , and hence more stable circuit operation can be obtained. The threshold voltage of the transistors 22 and 39 may be increased by, for instance, increasing the impurity concentration of the channel region through ion implantation. Alternatively, a method of making use of a short channel effect by making the channel length of the transistors 22 and 39 greater than that of the other transistors or a method in which the film thickness of the gate of the transistors 22 and 39 is made greater t

[3] Similarity: 0.7609
Patent: 20780eaa18a2d624
Category: transistor_device_technology
Section: DESCRIPTION
Text: FIELD OF THE INVENTION The present invention relates to circuit optimization generally and, more particularly, to cell library management for power optimization. BACKGROUND OF THE INVENTION Referring to FIG. 1 , a flow diagram of a conventional design optimization process 20 is shown. Conventional software tools 22 create a layout of a circuit using a design netlist 24 , timing constraints 26 and several cell libraries 28 (i.e., 28 a - 28 c ). The tools 22 can optimize an area and a performance

====================================================================================================
QUERY: DRAM memory cell architecture
====================================================================================================

[1] Similarity: 0.7974
Patent: ff2a72d0d72d60b0
Category: memory
Section: DESCRIPTION
Text: portions independently of each other. Any of these methods can be used and the invention is not to be limited to any particular method of using the DRAM and nonvolatile portions of the cell 100. FIGS. 8a and 8b are circuit diagrams illustrating SRAM cells 300, 350 constructed in accordance with an embodiment of the present invention. The cells 300, 350 are similar to the cells 200, 250 illustrated in FIGS. 3a and 3b with the exception that different transistors 308, 312 replace the transistors 2

[2] Similarity: 0.7825
Patent: ff2a72d0d72d60b0
Category: memory
Section: DESCRIPTION
Text: a DRAM device; FIGS. 3a and 3b are circuit diagrams illustrating conventional static random access memory (SRAM) cells; FIG. 4 is a block diagram illustrating a SRAM device; FIGS. 5a and 5b are circuit diagrams illustrating DRAM cells constructed in accordance with an embodiment of the present invention; FIG. 6 illustrates an exemplary process for sensing the state of the nonvolatile memory component of the DRAM cells illustrated in FIGS. 5a and 5b; FIGS. 7a and 7b illustrate a sense amplifier v

[3] Similarity: 0.7720
Patent: 7761f11c11977032
Category: memory
Section: DESCRIPTION
Text: of the logic connection between data and control byte. The memory according to this invention, (ASM: Application Specific Memory) guarantees a noticeable advantage during the manufacturing stage, in particular during the test stage of the memory chips. This is in comparison to DRAM memories. A single pass test is sufficient. Since the control bytes are all sequentially stored in a single row, the addressing operation can only be effected in the so-called &#34;page mode&#34; and an immediate logi

====================================================================================================
QUERY: silicon photonics optical communication
====================================================================================================

[1] Similarity: 0.7342
Patent: 93fe3300283c05e7
Category: photonics
Section: DESCRIPTION
Text: the need for a low value of surface roughness for high index waveguide systems such as silicon waveguides. The dependence on the correlation length L c is more complicated, but is still a significant parameter to be controlled. [0021] There is considerable motivation in silicon photonics for producing not only low-loss optical waveguides, but to also integrate actives devices such as sources, modulators, switches, tunable filters, detectors, etc., and all being compatible CMOS processing technol

[2] Similarity: 0.7187
Patent: 93fe3300283c05e7
Category: photonics
Section: DESCRIPTION
Text: has some permeability to allow oxidation to proceed to the underlying silicon. Further, while the various embodiments were described in terms of an SOI structure, other materials suitable for waveguide devices may be employed. Finally, it will be noted that the invention is especially useful for structures with a high contrast in index of refraction between the core and cladding (Δn in the range of 0.2 to 3) since such structures generally necessitate small dimensions for good optical confinemen

[3] Similarity: 0.7125
Patent: 93fe3300283c05e7
Category: photonics
Section: DESCRIPTION
Text: depletion, enhancement, or even injected carrier effects. Furthermore, by incorporating an optically active species (such as erbium, neodymium, ytterbium, praseodymium, holmium, etc, but not limited to these) in oxide layers surrounding, or possibly embedded in, the core of the waveguide (as an illustrative example), it may be possible to achieve optical gain and potentially laser operation through either electrical or optical pumping of the active species. This again highlights the desirability

====================================================================================================
QUERY: power semiconductor devices for high voltage applications
====================================================================================================

[1] Similarity: 0.7822
Patent: 98f85369e3a2b0e19f3f
Category: power_semiconductors
Section: BACKGROUND OF THE INVENTION
Text: EDL-6, No. 4, April 1985, pp. 161-163, and The Insulated Gate Transistor: A New Three-Terminal MOS-Controlled Bipolar Power Device, Baliga et al., IEEE Transactions on Electron Devices, Vol. ED-31, No. 6, June 1984, pp. 821-828, both of which are incorporated herein by reference in their entirety. Unfortunately, while these techniques have had varying measures of success in reducing latching susceptibility, the devices remain slower than MOSFETs operating at similar power levels. A power switchi

[2] Similarity: 0.7744
Patent: 98f85369e3a2b0e19f3f
Category: power_semiconductors
Section: BACKGROUND OF THE INVENTION
Text: The present invention relates to power switching devices. More specifically, the present invention relates to a power switching device for high frequency applications which has a relatively low “on resistance.” Metal-oxide semiconductor field effect transistors (MOSFETs) have become the standard power switching device because of their fast switching capabilities. Unfortunately, as the breakdown voltages of power MOSFETs increase, a correlative increase in device “on resistance,” R ON , is encoun

[3] Similarity: 0.7703
Patent: b548b777993f34e1
Category: power_semiconductors
Section: DESCRIPTION
Text: for operation at voltages of at least 100 volts, more preferably at least 300 volts, 400 volts, 500 volts or greater. Advantageously either IGBTs or MOSFETs may be employed. However, the skilled person will understand that other types of power device may also be employed including, for example, a high voltage diode, thyristor, Lilet (Lateral Inversion Layer Emitter Thyristor), SCR rectifier, LDMOSFET (Lateral Double Diffused MOSFET), Super Junction LDMOSFET and the like. Preferably, for ease of

In [15]:
# STEP 5 — Improved retrieval with document diversity

def search_patents(query, top_k=5, candidate_k=30):
    """
    Semantic retrieval with document-level diversification.
    No database/vector store required.
    """

    query_embedding = model.encode(
        query,
        normalize_embeddings=True,
        convert_to_numpy=True,
    )

    # Similarity against all chunks
    scores = embeddings @ query_embedding

    # Get a larger candidate pool first
    candidate_indices = np.argsort(scores)[::-1][:candidate_k]

    results = []

    seen_documents = set()

    for idx in candidate_indices:

        row = chunks_df.iloc[idx]
        document_id = row["document_id"]

        # Avoid returning multiple chunks from the same patent
        if document_id in seen_documents:
            continue

        seen_documents.add(document_id)

        results.append({
            "document_id": document_id,
            "category": row["category"],
            "cpc_section": row["cpc_section"],
            "section": row["section"],
            "similarity": float(scores[idx]),
            "abstract": row["abstract"],
            "text": row["text"],
        })

        if len(results) >= top_k:
            break

    return pd.DataFrame(results)


# ---------------------------------------------------------
# TEST
# ---------------------------------------------------------

query = "methods for reducing leakage and improving transistor performance"

results = search_patents(query, top_k=5)

print("QUERY:")
print(query)

print("\n" + "=" * 100)

for i, row in results.iterrows():

    print(f"\n[{i + 1}] Similarity: {row['similarity']:.4f}")
    print("Patent:", row["document_id"])
    print("Category:", row["category"])
    print("CPC:", row["cpc_section"])
    print("Section:", row["section"])

    print("\nAbstract:")
    print(row["abstract"][:500].replace("\n", " "))

    print("\nRetrieved passage:")
    print(row["text"][:700].replace("\n", " "))

    print("\n" + "-" * 80)

QUERY:
methods for reducing leakage and improving transistor performance

====================================================================================================

[1] Similarity: 0.7768
Patent: 7a624e78d2ae6904
Category: semiconductor_manufacturing
CPC:
Section: DESCRIPTION

Abstract:
In a method of fabricating a thin film transistor array substrate, a black matrix having separated portions is first formed on a substrate with an opaque conductive material. An insulation layer is formed to cover the black matrix. A gate line assembly and a data line assembly are formed over the black matrix and insulation layer. Buffer layers are formed to cover the gaps between the separate portions of the black matrix. The buffer conductive layers are formed at the same plane as the gate lin

Retrieved passage:
can be further reduced while completely intercepting the passage of current leakage at the D region. As described above, the black matrix is formed at the TFT array substrate with the pixel electrodes so that opening ratio of the device can be enhanced in a stable manner. The semiconductor pattern and the contact holes are formed together so that the processing steps can be simplified. Possible leakage of current can be prevented at the non-channel area using the black matrix. Furthermore, a buffer conductive layer is formed over the semiconductor pattern between the neighboring data lines, and an opening portion is formed at the common electrode over the semiconductor pattern so that curren

--------------------------------------------------------------------------------

[2] Similarity: 0.7617
Patent: 20780eaa18a2d624
Category: transistor_device_technology
CPC:
Section: DESCRIPTION

Abstract:
A method of managing a cell library regarding power optimization is disclosed. The method generally includes the steps of (A) reading a plurality of first modules within a first region of a circuit design stored in a design file, (B) calculating a first merit value indicating a relative sensitivity of the first region to a power consumption, the first merit value having a range from a static power dominated value to a dynamic power dominated value and (C) creating a constraint file configured to

Retrieved passage:
FIELD OF THE INVENTION The present invention relates to circuit optimization generally and, more particularly, to cell library management for power optimization. BACKGROUND OF THE INVENTION Referring to FIG. 1 , a flow diagram of a conventional design optimization process 20 is shown. Conventional software tools 22 create a layout of a circuit using a design netlist 24 , timing constraints 26 and several cell libraries 28 (i.e., 28 a - 28 c ). The tools 22 can optimize an area and a performance (speed) of the circuitry, but power optimization is neglected. Commonly, each cell in the cell libraries 28 is part of a family with different sized transistors for the same functionality. The cell va

--------------------------------------------------------------------------------

[3] Similarity: 0.7563
Patent: 5ef5ac357b2ad1cd
Category: transistor_device_technology
CPC:
Section: DESCRIPTION

Abstract:
Disclosed is a semiconductor integrated circuit device, which comprises at least one selection circuit including a first node, a first MOS transistor for periodically pre-charging the first node, second MOS transistors for determining the potential state of the first node in response to a state designating signal, a third MOS transistor connected to the first node and functioning as a barrier, a second node connected through the barrier MOS transistor to the first node, a fourth MOS transistor f

Retrieved passage:
to the transistors 24 1 to 24 m ) to enhance the barrier function and thus improve the breakdown voltage between the nodes N 21 and N 22 (or between the nodes N 25 and N 26 ) against punchthrough. Further, in the embodiment of FIG. 3, the threshold voltages V T1 , V T2 and V T4 of the transistors 21, 22 and 24 may be set such as to satisfy a relation: V.sub.T1 ≦V.sub.T4 ≦V.sub.T2 With this construction, the device can be less susceptible to the substrate potential fluctuations. The relation mentioned above may be realized by setting different channel lengths for the individual transistors 21, 22 and 24. In this case, it is desirable to set the channel lengths of the individual transistors 21

--------------------------------------------------------------------------------

[4] Similarity: 0.7554
Patent: e1b5fb2235c13a97
Category: transistor_device_technology
CPC:
Section: DESCRIPTION

Abstract:
A static RAM which features an inclusion of a word line driving circuit shared by all the memory cells in the static RAM is disclosed. The static RAM is comprised of a plurality of four-transistor memory cells arranged in an array. Each of the memory cells includes first and second FETs respectively coupled to bit lines and controlled by word line potential. Further, each of the memory cells further comprises third and fourth cross-coupled FETs respectively coupled in series with the first and s

Retrieved passage:
threshold voltage is lowered with the result of increase in the leak current. However, when the memory chip is designed, it might be possible to predict the upper and lower limits of scatter in the leak currents of the transistors of all the on-chip memory cells. The upper limit of leak current among the n-channel transistors is designated by I OFF-N(MAX) , and the lower limit of leak current among the p-channel transistors is designated by I OFF-P(MIN) . The word line driving circuit 50 comprises a monitor circuit 60 , a differential amplifier 62 , a p-channel transistor 64 , and an n-channel transistor 66 . The monitor circuit 60 consists of a p-channel transistor 68 and an n-channel trans

--------------------------------------------------------------------------------

[5] Similarity: 0.7364
Patent: 9ea45e3b200fe614
Category: transistor_device_technology
CPC:
Section: DESCRIPTION

Abstract:
A method for the design and layout for a patterned deep N-well. A Tile is specified as a fundamental building block for the deep N-well pattern. The tile comprises a first element on a first layer and may comprise a second element on a second layer. A two dimensional region is covered with an array of contiguous tiles, with the elements on each layer connecting with elements of adjacent tiles to form extended shapes. The array may be converted to a collection of sub-arrays through the removal of

Retrieved passage:
FIELD OF THE INVENTION Embodiments of the present invention relate to circuit design and layout in complementary metal-oxide semiconductor (CMOS) circuits. In particular, embodiments of the present invention relate to the design of body-bias voltage connections in CMOS circuits. BACKGROUND ART As the operating voltages for CMOS transistor circuits have decreased, variations in the threshold voltages for the transistors have become more significant. Although low operating voltages offer the potential for reduced power consumption, gate threshold voltage variations due to process and environmental variables often prevent optimum efficiency and performance from being achieved due to increased l

--------------------------------------------------------------------------------

In [16]:
# STEP 6 — Retrieval benchmark

benchmark_queries = [
    "How can through-silicon vias improve advanced semiconductor packaging?",
    "What techniques are used to reduce leakage current in transistor devices?",
    "What structures are used to improve DRAM memory cell performance?",
    "How are semiconductor devices fabricated using multiple material layers?",
    "What approaches improve thermal management in semiconductor packages?",
    "How are silicon photonic devices used for optical communication?",
    "What semiconductor structures are designed for high-voltage power applications?",
    "How can semiconductor devices improve computing performance using advanced architectures?",
    "What techniques improve transistor switching speed?",
    "What methods are used to improve semiconductor manufacturing yield?",
]

benchmark_results = []

for query in benchmark_queries:

    results = search_patents(
        query,
        top_k=5,
        candidate_k=50
    )

    print("\n" + "=" * 100)
    print("QUERY:", query)
    print("=" * 100)

    for rank, (_, row) in enumerate(results.iterrows(), start=1):

        print(
            f"{rank}. "
            f"{row['document_id']} | "
            f"{row['category']} | "
            f"{row['section']} | "
            f"{row['similarity']:.4f}"
        )

        print(
            "   ",
            row["text"][:250]
            .replace("\n", " ")
        )

        benchmark_results.append({
            "query": query,
            "rank": rank,
            "document_id": row["document_id"],
            "category": row["category"],
            "section": row["section"],
            "similarity": row["similarity"],
        })


benchmark_df = pd.DataFrame(benchmark_results)

print("\n\nBenchmark complete")
print("-" * 50)
print("Queries:", len(benchmark_queries))
print("Results/query:", 5)
print("Total retrievals:", len(benchmark_df))

====================================================================================================
QUERY: How can through-silicon vias improve advanced semiconductor packaging?
====================================================================================================
1. 6ebfa06f472a9c0d84bc | advanced_packaging | BACKGROUND | 0.7462
    [0001] Nanoscale technologies, similar to other technologies, face challenges in high power consumption and signal delay due to global interconnects, but due to their scope, addressing these challenges opens new areas of research. One research area i
2. a9961143e9743d4b | advanced_packaging | DESCRIPTION | 0.7415
    RELATED APPLICATIONS This application claims priority to U.S. Provisional Patent Application 61/722,738, entitled “METHOD AND STRUCTURE FOR PROVIDING REDUCED CONTACT TESTING AT WAFER SORT USING ELECTRON BEAM DEFLECTION” filed Nov. 5, 2012. FIELD OF T
3. f129a885d93007f261b9 | advanced_packaging | BACKGROUND | 0.7402
    [0001] The present invention relates to a semiconductor structure, and more specifically, to a protected through silicon via (TSV) for providing vertical interconnection in a semiconductor structure.   [0002] In semiconductor technology, a through-si
4. 2d43ab40fc0eb9178499 | advanced_packaging | SUMMARY OF THE INVENTION | 0.7397
    [0011] We have developed a process for integrating chips together that reduces or eliminates the problems present with the above processes.   [0012] Depending upon the particular variant, our approaches can provide one or more of the following benefi
5. a404be781c021e2050e3 | advanced_packaging | BACKGROUND OF THE INVENTION | 0.7344
    made of a semiconductor material close to the semiconductor chip 12 is provided so as to effectively overcome the above-described drawbacks. However, to form the TSVs 100 of the through silicon interposer 10 , a plurality of through holes need to be

====================================================================================================
QUERY: What techniques are used to reduce leakage current in transistor devices?
====================================================================================================
1. 7a624e78d2ae6904 | semiconductor_manufacturing | DESCRIPTION | 0.7685
    can be further reduced while completely intercepting the passage of current leakage at the D region. As described above, the black matrix is formed at the TFT array substrate with the pixel electrodes so that opening ratio of the device can be enhanc
2. 20780eaa18a2d624 | transistor_device_technology | DESCRIPTION | 0.7661
    FIELD OF THE INVENTION The present invention relates to circuit optimization generally and, more particularly, to cell library management for power optimization. BACKGROUND OF THE INVENTION Referring to FIG. 1 , a flow diagram of a conventional desig
3. e1b5fb2235c13a97 | transistor_device_technology | DESCRIPTION | 0.7630
    threshold voltage is lowered with the result of increase in the leak current. However, when the memory chip is designed, it might be possible to predict the upper and lower limits of scatter in the leak currents of the transistors of all the on-chip
4. 86a90198d1fc37dc | transistor_device_technology | DESCRIPTION | 0.7538
    CROSS-REFERENCE TO RELATED APPLICATIONS [0001] This application claims priority to provisional patent application Ser. No. 60/587,668, filed Jul. 14, 2004, the entirety of which is hereby incorporated by reference herein. [0002] This application is r
5. 407b6e9adbe4b02b | transistor_device_technology | DESCRIPTION | 0.7289
    indication. Ecker&#39;s device uses one of two possible input resistances, in parallel with the control element, either of which were considered necessary in design, in which electrons collecting at the grid could leak off to ground. Without a return

====================================================================================================
QUERY: What structures are used to improve DRAM memory cell performance?
====================================================================================================
1. ff2a72d0d72d60b0 | memory | DESCRIPTION | 0.7766
    portions independently of each other. Any of these methods can be used and the invention is not to be limited to any particular method of using the DRAM and nonvolatile portions of the cell 100. FIGS. 8a and 8b are circuit diagrams illustrating SRAM
2. 3332bcaa3a45eaad | memory | DESCRIPTION | 0.7501
    TECHNICAL FIELD The subject matter of this application relates to two dimensional random access memories. Specifically, a semiconductor random access memory having a second data transfer port is provided for improving the efficiency of data transfer
3. 7761f11c11977032 | memory | DESCRIPTION | 0.7471
    of the logic connection between data and control byte. The memory according to this invention, (ASM: Application Specific Memory) guarantees a noticeable advantage during the manufacturing stage, in particular during the test stage of the memory chip
4. 36942e7938662a25 | memory | DESCRIPTION | 0.7466
    embodiment, the memory banks are separated into discontiguous portions. Despite placing portions of the banks in separate locations, the columnar arrangement of sub-arrays, one from each bank, is retained, and the columns are rotated ninety degrees r
5. e1b5fb2235c13a97 | transistor_device_technology | DESCRIPTION | 0.7400
    BACKGROUND OF THE INVENTION 1. Field of the Invention The present invention relates generally to a static RAM (random access memory) for use in digital computer systems. More specifically, the present invention relates to a static RAM which features

====================================================================================================
QUERY: How are semiconductor devices fabricated using multiple material layers?
====================================================================================================
1. 035ed7683a8cf2c3 | semiconductor_manufacturing | DESCRIPTION | 0.7739
    FIELD OF THE INVENTION [0001] This invention generally relates to photoresist methods for forming semiconductor features and more particularly to a bi-layer photoresist dry development method for high resolution features. BACKGROUND OF THE INVENTION
2. 2cf1556a6b03be0b | semiconductor_manufacturing | DESCRIPTION | 0.7681
    the first substrate 100 and the second substrate 200 . [0026] First, the thin film transistor substrate 100 will be described below. [0027] As shown in FIG. 1 , a plurality of first substrates 100 are manufactured from a large mother substrate substa
3. 03ca7ae1cca3f2ec2c26 | advanced_packaging | BACKGROUND | 0.7663
    Semiconductor device is widely adopted in various applications. The geometry is trending down rapidly as user&#39;s demands increases on the performance and functionality. For example, a 3G mobile phone presented in the market is expected to be capab
4. d69c1632c9028e54 | transistor_device_technology | DESCRIPTION | 0.7571
    electrodes that will be formed later will be varied. Referring to FIG. 2E , the low resistance data metal layer 105 and ohmic contact layer 104 corresponding to the channel area of the thin film transistor are etched using the ashed second photoresis
5. 7a624e78d2ae6904 | semiconductor_manufacturing | DESCRIPTION | 0.7542
    line assembly has a double-layered structure with a chrome-based under-layer and an aluminum-based over-layer. Thereafter, the ohmic contact layer 50 exposed through the data line assembly is etched to be separated into ohmic contact patterns 55 and

====================================================================================================
QUERY: What approaches improve thermal management in semiconductor packages?
====================================================================================================
1. 6001024cc3df05a76add | advanced_packaging | BACKGROUND | 0.8095
    logic circuits, the package 110 may be a memory module, and the die 120 may comprise analog circuits. [0006] As more and more integration takes place in system-in-package technology, thermal management may present a challenge. Conventional thermal ma
2. e50c49015d5992d18558 | advanced_packaging | DETAILED DESCRIPTION OF THE INVENTION | 0.7496
    side of the package facing upwards with the exposed metal die paddle facing away from the PCB surface. An additional heatsink can also be attached to the metal die paddle for enhanced heat dissipation. Additionally the electronic packages can be stac
3. c61971e471702770 | semiconductor_manufacturing | DESCRIPTION | 0.7472
    thermally conditioned in manufacturing processes. It is a further object of this invention to reduce the overall required soak chamber size by reducing the time needed to bring the semiconductor ICs to the set-point temperature. It is a further objec
4. 23ebeda5c273212c3bcd | advanced_packaging | DESCRIPTION OF THE RELATED ART | 0.7470
    [0035] High-speed microprocessor packaging must be designed to provide increasingly small form-factors. Meeting end user performance requirements with minimal form-factors while increasing reliability and manufacturability presents significant challe
5. 0c30900aee0b5eb4018e | advanced_packaging | DESCRIPTION OF THE RELATED ART | 0.7469
    [0036] High-speed microprocessor packaging must be designed to provide increasingly small form-factors. Meeting end user performance requirements with minimal form-factors while increasing reliability and manufacturability presents significant challe

====================================================================================================
QUERY: How are silicon photonic devices used for optical communication?
====================================================================================================
1. 93fe3300283c05e7 | photonics | DESCRIPTION | 0.7612
    the need for a low value of surface roughness for high index waveguide systems such as silicon waveguides. The dependence on the correlation length L c is more complicated, but is still a significant parameter to be controlled. [0021] There is consid
2. 3bde202c85aee481 | photonics | DESCRIPTION | 0.7166
    RELATED APPLICATIONS [0001] This application is related to application SC11378TP, entitled “An Opto-Coupling Device Structure and Method Therefor,” and assigned to the assignee hereof. FIELD OF THE INVENTION [0002] The invention relates to optical de
3. 269632ad34ad43bc | semiconductor_manufacturing | DESCRIPTION | 0.7060
    RELATED APPLICATIONS This application is based on a Provisional Application, Serial No. 60/243,243, filed on Oct. 25, 2000, entitled “Optical Infrastructure on a wafer.” FIELD OF THE INVENTION This invention describes an optical communications infras
4. eefc1d7d4aa24261c904 | advanced_packaging | BACKGROUND OF THE INVENTION | 0.6935
    Vertical Cavity Surface Emitting Laser (VCSEL) arrays are often used in fiber optic communications. These VCSEL arrays are capable of transmitting large amounts of data over small optical fibers. A single ⅛ inch fiber bundle may carry an entire 12-20
5. b46c390350296b9a | power_semiconductors | DESCRIPTION | 0.6806
    can be. In this case, the quantum wells use gallium arsenide, but other materials can be used where excitonic levels are more strongly bound, leading to devices which can be operated at high temperatures. An important characteristic of the device of

====================================================================================================
QUERY: What semiconductor structures are designed for high-voltage power applications?
====================================================================================================
1. 98f85369e3a2b0e19f3f | power_semiconductors | BACKGROUND OF THE INVENTION | 0.7638
    The present invention relates to power switching devices. More specifically, the present invention relates to a power switching device for high frequency applications which has a relatively low “on resistance.” Metal-oxide semiconductor field effect
2. b548b777993f34e1 | power_semiconductors | DESCRIPTION | 0.7367
    for operation at voltages of at least 100 volts, more preferably at least 300 volts, 400 volts, 500 volts or greater. Advantageously either IGBTs or MOSFETs may be employed. However, the skilled person will understand that other types of power device
3. 6ebfa06f472a9c0d84bc | advanced_packaging | Introduction | 0.7285
    [0014] The plug-and-play approach described above may be driven in several ways. First, organizations may develop, and the industry adopts, guidelines to standardize the interface circuit properties (location and electrical characteristics of IO port
4. 0c30900aee0b5eb4018e | advanced_packaging | DESCRIPTION OF THE RELATED ART | 0.7137
    [0036] High-speed microprocessor packaging must be designed to provide increasingly small form-factors. Meeting end user performance requirements with minimal form-factors while increasing reliability and manufacturability presents significant challe
5. 23ebeda5c273212c3bcd | advanced_packaging | DESCRIPTION OF THE RELATED ART | 0.7131
    [0035] High-speed microprocessor packaging must be designed to provide increasingly small form-factors. Meeting end user performance requirements with minimal form-factors while increasing reliability and manufacturability presents significant challe

====================================================================================================
QUERY: How can semiconductor devices improve computing performance using advanced architectures?
====================================================================================================
1. 03ca7ae1cca3f2ec2c26 | advanced_packaging | BACKGROUND | 0.7182
    Semiconductor device is widely adopted in various applications. The geometry is trending down rapidly as user&#39;s demands increases on the performance and functionality. For example, a 3G mobile phone presented in the market is expected to be capab
2. 6ebfa06f472a9c0d84bc | advanced_packaging | BACKGROUND | 0.7113
    [0001] Nanoscale technologies, similar to other technologies, face challenges in high power consumption and signal delay due to global interconnects, but due to their scope, addressing these challenges opens new areas of research. One research area i
3. d4f2c961535767e1 | ai_advanced_semiconductor | DESCRIPTION | 0.6947
    FIELD OF THE INVENTION [0001] This invention relates in general to computer architecture and in particular to acceleration of nested loops in algorithms. BACKGROUND OF THE INVENTION [0002] Computing devices are becoming ubiquitous and many electronic
4. 03cea21e92af4a21 | transistor_device_technology | ABSTRACT | 0.6922
    A clock and data distribution network is proposed that distributes clock and data signals without buffers, thus achieving very low jitter, skew, loose timing requirements, and energy consumption. Such network uses resonant drivers and is generally ap
5. 6294fc102d314418 | ai_advanced_semiconductor | DESCRIPTION | 0.6816
    instructions to perform a simple and often repeated task. U.S. Pat. No. 4,739,474, to Holsztynski et al., represents a higher level of complexity, in which the logic gate is replaced by a full adder capable of performing both arithmetic and logical f

====================================================================================================
QUERY: What techniques improve transistor switching speed?
====================================================================================================
1. 98f85369e3a2b0e19f3f | power_semiconductors | BACKGROUND OF THE INVENTION | 0.7652
    EDL-6, No. 4, April 1985, pp. 161-163, and The Insulated Gate Transistor: A New Three-Terminal MOS-Controlled Bipolar Power Device, Baliga et al., IEEE Transactions on Electron Devices, Vol. ED-31, No. 6, June 1984, pp. 821-828, both of which are inc
2. d7aeb605e4adcc70 | transistor_device_technology | DESCRIPTION | 0.7406
    changeover timing of the input signal (IN) is delayed with respect to the changeover timing of the scanning circuit output (OT) and hence, it is expected that the penetration current hardly flows. [0128] That is, when the scanning lines are connected
3. 5ef5ac357b2ad1cd | transistor_device_technology | DESCRIPTION | 0.7256
    ΔV BN , and hence more stable circuit operation can be obtained. The threshold voltage of the transistors 22 and 39 may be increased by, for instance, increasing the impurity concentration of the channel region through ion implantation. Alternatively
4. 20780eaa18a2d624 | transistor_device_technology | DESCRIPTION | 0.7095
    FIELD OF THE INVENTION The present invention relates to circuit optimization generally and, more particularly, to cell library management for power optimization. BACKGROUND OF THE INVENTION Referring to FIG. 1 , a flow diagram of a conventional desig
5. 1e81f683906b557a | transistor_device_technology | DESCRIPTION | 0.7087
    at a high slew rate. The present invention is not limited to the first to third embodiments and may be modified as follows: (a) By controlling in level of electric currents of the current sources 51 , 52 , 91 , 92 , 101 , and 102 of the first and sec

====================================================================================================
QUERY: What methods are used to improve semiconductor manufacturing yield?
====================================================================================================
1. d3ead82de489632b | semiconductor_manufacturing | DESCRIPTION | 0.7792
    CROSS-REFERENCE: This continuation patent application claims priority under 35 U.S.C. §120 from U.S. patent application No. 11/166,960, filed Jun. 23, 2005, now issued as U.S. Pat. No.7,685,481 B2, the disclosure of which is incorporated by reference
2. 678e9b7f28681857 | semiconductor_manufacturing | DESCRIPTION | 0.7704
    BACKGROUND OF THE INVENTION 1. Field of the Invention This invention relates generally to the manufacturing of high performance semiconductor devices. More specifically, this invention relates to a method of isolating optical defect images that have
3. 1bc765dc24dc5424 | semiconductor_manufacturing | DESCRIPTION | 0.7657
    cases of the system can be raised. As a result, it is possible to construct a system having a high performance as a whole. FIG. 34 is a diagram showing a curve 30 representing changes in yield which are obtained during a build-up time of a mass produ
4. 705e4ab08d381edd | semiconductor_manufacturing | DESCRIPTION | 0.7400
    This application is a continuation of application Ser. No. 07/738,699, filed Jul. 31, 1991, now abandoned. FIELD OF THE INVENTION This invention generally relates to semiconductor devices and in particular for lithography methods. BACKGROUND OF THE I
5. 59a55217020f07d1 | transistor_device_technology | DESCRIPTION | 0.7368
    defect is detected is corrected. [0115] Here, a case where the defocus amount is acquired when the defect is detected has been described, but the defocus amount may be acquired irrespective of presence of detection of the defect. [0116] By constructi


Benchmark complete
--------------------------------------------------
Queries: 10
Results/query: 5
Total retrievals: 50

In [17]:
import subprocess

result = subprocess.run(
    ["ollama", "list"],
    capture_output=True,
    text=True
)

print(result.stdout)

NAME                       ID              SIZE      MODIFIED
gemma3:4b                  a2af6cc3eb7f    3.3 GB    2 days ago
qwen3:8b                   500a1f067a9f    5.2 GB    2 days ago
gemma3:1b                  8648f39daa8f    815 MB    3 days ago
llama3.2:1b                baf6a787fdff    1.3 GB    3 days ago
qwen2.5:0.5b               a8b0c5157701    397 MB    3 days ago
nomic-embed-text:latest    0a109f422b47    274 MB    3 days ago
qwen3.5:0.8b               f3817196d142    1.0 GB    4 days ago
llama3.1:8b                46e0c10c039e    4.9 GB    6 days ago

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [18]:
# STEP 7 — Connect Ollama to the RAG

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
LLM_MODEL = "qwen3:8b"


def ask_ollama(prompt, model=LLM_MODEL):
    """Send a prompt to the local Ollama model."""

    response = requests.post(
        OLLAMA_URL,
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
        },
        timeout=120,
    )

    response.raise_for_status()

    return response.json()["response"]


# Simple connectivity test
test_response = ask_ollama(
    "In one sentence, explain what a semiconductor is."
)

print("Ollama connection successful")
print("Model:", LLM_MODEL)
print("Response:", test_response)

Ollama connection successful
Model: qwen3:8b
Response: A semiconductor is a material with electrical conductivity between that of conductors and insulators, enabling it to control the flow of electric current in electronic devices.

In [19]:
def answer_with_context(question: str, context: str) -> str:
    """Generate an answer using retrieved RAG context."""

    prompt = f"""
You are a semiconductor patent research assistant.

Answer the user's question using ONLY the information provided
in the retrieved patent context below.

If the context does not contain enough information to answer,
say so explicitly.

Retrieved patent context:
-------------------------
{context}
-------------------------

User question:
{question}

Provide a concise, technically accurate answer.
"""

    return ask_ollama(prompt)

In [20]:
context = """
US Patent XXXXX describes a semiconductor manufacturing process
using a plasma etching step followed by deposition of a dielectric
layer...
"""

question = "What manufacturing process is described in this patent?"

answer = answer_with_context(question, context)

print(answer)

The patent describes a semiconductor manufacturing process involving a plasma etching step followed by the deposition of a dielectric layer.

In [23]:
# STEP 8 — RAG Prompt Component

def build_rag_prompt(question, retrieved_context):
    """
    Build a grounded prompt for the local Ollama model.
    """

    prompt = f"""
You are a semiconductor patent research assistant.

Use ONLY the retrieved patent information provided below
to answer the question.

If the retrieved information does not contain enough evidence,
say that the available patent context is insufficient.

Do not invent patent numbers, claims, inventors, technical details,
or conclusions that are not supported by the retrieved context.

RETRIEVED PATENT CONTEXT
========================

{retrieved_context}

========================

QUESTION
========

{question}

ANSWER
======

Provide a clear, technically accurate answer based only on
the retrieved patent context.
"""

    return prompt

In [25]:
# Create test context

test_context = """
Patent ID: US1234567B2

Title:
Semiconductor manufacturing process

Abstract:
The patent describes a semiconductor fabrication process
using plasma etching followed by deposition of a dielectric layer.

Claim 1:
A method comprising etching a semiconductor substrate using
plasma and subsequently depositing a dielectric material.
"""

test_question = "What manufacturing process is described?"

prompt = build_rag_prompt(
    test_question,
    test_context
)

print(prompt)

You are a semiconductor patent research assistant.

Use ONLY the retrieved patent information provided below
to answer the question.

If the retrieved information does not contain enough evidence,
say that the available patent context is insufficient.

Do not invent patent numbers, claims, inventors, technical details,
or conclusions that are not supported by the retrieved context.

RETRIEVED PATENT CONTEXT
========================


Patent ID: US1234567B2

Title:
Semiconductor manufacturing process

Abstract:
The patent describes a semiconductor fabrication process
using plasma etching followed by deposition of a dielectric layer.

Claim 1:
A method comprising etching a semiconductor substrate using
plasma and subsequently depositing a dielectric material.


========================

QUESTION
========

What manufacturing process is described?

ANSWER
======

Provide a clear, technically accurate answer based only on
the retrieved patent context.

In [26]:
# STEP 9 — Generate Answer from RAG Context

answer = ask_ollama(prompt)

print("RAG Answer:")
print(answer)

RAG Answer:
The manufacturing process described is a semiconductor fabrication method involving **plasma etching** of a semiconductor substrate followed by the **deposition of a dielectric material**. This is explicitly outlined in the patent's claims and abstract.

In [30]:
# STEP 10 — Inspect Existing RAG Components

print("Available RAG-related objects:\n")

for name, obj in sorted(globals().items()):
    if any(term in name.lower() for term in [
        "embed",
        "vector",
        "index",
        "chunk",
        "document",
        "retriev",
        "faiss",
        "chroma",
        "collection",
        "metadata",
        "patent",
    ]):
        print(f"{name:<30} {type(obj)}")

Available RAG-related objects:

CHUNK_OVERLAP                  <class 'int'>
CHUNK_SIZE                     <class 'int'>
chunk                          <class 'str'>
chunk_index                    <class 'int'>
chunk_text                     <class 'function'>
chunks                         <class 'list'>
chunks_df                      <class 'pandas.core.frame.DataFrame'>
document_id                    <class 'str'>
documents_with_markers         <class 'int'>
embeddings                     <class 'numpy.ndarray'>
search_patents                 <class 'function'>
section_chunks                 <class 'list'>
test_embeddings                <class 'numpy.ndarray'>

In [31]:
# Inspect imported libraries that may be relevant

print("\nRelevant modules:")

for name, obj in sorted(globals().items()):
    if name in ["faiss", "chromadb", "numpy", "np", "pandas", "pd"]:
        print(f"{name:<15} {type(obj)}")

Relevant modules:
np              <class 'module'>
pd              <class 'module'>

In [33]:
# ============================================================
# STEP 10 — Load Semiconductor Patent Corpus
# ============================================================

from pathlib import Path
import pandas as pd

# Your existing semiconductor patent corpus
CORPUS_ROOT = Path(
    "/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents"
)

METADATA_FILE = CORPUS_ROOT / "metadata.csv"

print("Corpus exists:", CORPUS_ROOT.exists())
print("Metadata exists:", METADATA_FILE.exists())

if not CORPUS_ROOT.exists():
    raise FileNotFoundError(
        f"Patent corpus not found: {CORPUS_ROOT}"
    )

if not METADATA_FILE.exists():
    raise FileNotFoundError(
        f"Metadata file not found: {METADATA_FILE}"
    )

# Load metadata
metadata = pd.read_csv(METADATA_FILE)

print("\nPatent metadata loaded successfully.")
print("Number of records:", len(metadata))

print("\nColumns:")
for column in metadata.columns:
    print(" -", column)

print("\nFirst 5 records:")
display(metadata.head())

Corpus exists: True
Metadata exists: True

Patent metadata loaded successfully.
Number of records: 500

Columns:
 - document_id
 - publication_number
 - title
 - abstract
 - claims
 - description
 - cpc_section
 - inventors
 - assignee
 - filing_date
 - publication_date
 - category
 - filename
 - source
 - word_count
 - character_count

First 5 records:

,document_id,publication_number,title,abstract,claims,description,cpc_section,inventors,assignee,filing_date,publication_date,category,filename,source,word_count,character_count
0,035ed7683a8cf2c3,NaN,NaN,A method for semiconductor device feature deve...,NaN,FIELD OF THE INVENTION [0001] This invention g...,NaN,NaN,NaN,NaN,NaN,semiconductor_manufacturing,patent_035ed7683a8cf2c3.txt,BIGPATENT,3538,22987
1,08064dc5e6a41c78,NaN,NaN,A pattern generator for integrated multilayer ...,NaN,BACKGROUND OF THE INVENTION 1. Field of the In...,NaN,NaN,NaN,NaN,NaN,semiconductor_manufacturing,patent_08064dc5e6a41c78.txt,BIGPATENT,6450,38272
2,095d694dbb617b65,NaN,NaN,The present invention has an object to provide...,NaN,BACKGROUND OF THE INVENTION [0001] 1. Field of...,NaN,NaN,NaN,NaN,NaN,semiconductor_manufacturing,patent_095d694dbb617b65.txt,BIGPATENT,12363,73608
3,0bf59cde519a6316,NaN,NaN,A technique for measuring the ion implant dosa...,NaN,BACKGROUND OF THE INVENTION 1. Field of the In...,NaN,NaN,NaN,NaN,NaN,semiconductor_manufacturing,patent_0bf59cde519a6316.txt,BIGPATENT,1957,11786
4,0c3c5540a4fd4e21,NaN,NaN,A method of and apparatus for measuring line p...,NaN,CROSS-REFERENCE TO RELATED APPLICATIONS This a...,NaN,NaN,NaN,NaN,NaN,semiconductor_manufacturing,patent_0c3c5540a4fd4e21.txt,BIGPATENT,6365,40359

In [34]:
# ============================================================
# STEP 10B — Inspect Patent Files
# ============================================================

all_files = [
    path for path in CORPUS_ROOT.rglob("*")
    if path.is_file()
]

print("Total files:", len(all_files))

print("\nFile types:")
file_types = {}

for path in all_files:
    suffix = path.suffix.lower() or "[no extension]"
    file_types[suffix] = file_types.get(suffix, 0) + 1

for suffix, count in sorted(file_types.items()):
    print(f"{suffix:15} {count}")

print("\nExample files:")
for path in all_files[:20]:
    print(path.relative_to(CORPUS_ROOT))

Total files: 501

File types:
.csv            1
.txt            500

Example files:
metadata.csv
advanced_packaging/patent_23ebeda5c273212c3bcd.txt
advanced_packaging/patent_d6b919ccb69b6b48ba28.txt
advanced_packaging/patent_77ef8db797ce48c60943.txt
advanced_packaging/patent_8f954a54fe074893c736.txt
advanced_packaging/patent_403a180868f181ccb1a0.txt
advanced_packaging/patent_da2d58c881907dcfe7fc.txt
advanced_packaging/patent_24a95eaf36a613e9a7ec.txt
advanced_packaging/patent_b1aaa836bc3709df1d70.txt
advanced_packaging/patent_6412ebaec693a0105f28.txt
advanced_packaging/patent_3d5e0281a6e4e66c129d.txt
advanced_packaging/patent_51de540a07c2efbb0473.txt
advanced_packaging/patent_c182265c4cd46ad5.txt
advanced_packaging/patent_5469465e8f806fc2b1fe.txt
advanced_packaging/patent_6001024cc3df05a76add.txt
advanced_packaging/patent_6c78e01a8516125d.txt
advanced_packaging/patent_a969f5fbe709d62ce477.txt
advanced_packaging/patent_de0145519ce9aacf.txt
advanced_packaging/patent_313810c0b6e6e16b1b9b.txt
advanced_packaging/patent_3afdad3d1f7343beec24.txt

In [35]:
# ============================================================
# STEP 11 — Load Patent Documents
# ============================================================

from pathlib import Path
import pandas as pd

# Reuse variables if they already exist
CORPUS_ROOT = Path(
    "/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents"
)

METADATA_FILE = CORPUS_ROOT / "metadata.csv"

metadata = pd.read_csv(METADATA_FILE)

print("Metadata records:", len(metadata))
print("Columns:", metadata.columns.tolist())

Metadata records: 500
Columns: ['document_id', 'publication_number', 'title', 'abstract', 'claims', 'description', 'cpc_section', 'inventors', 'assignee', 'filing_date', 'publication_date', 'category', 'filename', 'source', 'word_count', 'character_count']

In [36]:
# Show a representative record

display(
    metadata.head(3).T
)

,0,1,2
document_id,035ed7683a8cf2c3,08064dc5e6a41c78,095d694dbb617b65
publication_number,NaN,NaN,NaN
title,NaN,NaN,NaN
abstract,A method for semiconductor device feature deve...,A pattern generator for integrated multilayer ...,The present invention has an object to provide...
claims,NaN,NaN,NaN
description,FIELD OF THE INVENTION [0001] This invention g...,BACKGROUND OF THE INVENTION 1. Field of the In...,BACKGROUND OF THE INVENTION [0001] 1. Field of...
cpc_section,NaN,NaN,NaN
inventors,NaN,NaN,NaN
assignee,NaN,NaN,NaN
filing_date,NaN,NaN,NaN
publication_date,NaN,NaN,NaN
category,semiconductor_manufacturing,semiconductor_manufacturing,semiconductor_manufacturing
filename,patent_035ed7683a8cf2c3.txt,patent_08064dc5e6a41c78.txt,patent_095d694dbb617b65.txt
source,BIGPATENT,BIGPATENT,BIGPATENT
word_count,3538,6450,12363
character_count,22987,38272,73608

In [37]:
# ============================================================
# STEP 11B — Find Patent Text Files
# ============================================================

text_extensions = {
    ".txt",
    ".text",
    ".md",
    ".xml",
    ".json",
}

patent_files = [
    path
    for path in CORPUS_ROOT.rglob("*")
    if path.is_file()
    and path.suffix.lower() in text_extensions
    and path.name != "metadata.csv"
]

print("Patent text files found:", len(patent_files))

print("\nExamples:")
for path in patent_files[:10]:
    print(path.relative_to(CORPUS_ROOT))

Patent text files found: 500

Examples:
advanced_packaging/patent_23ebeda5c273212c3bcd.txt
advanced_packaging/patent_d6b919ccb69b6b48ba28.txt
advanced_packaging/patent_77ef8db797ce48c60943.txt
advanced_packaging/patent_8f954a54fe074893c736.txt
advanced_packaging/patent_403a180868f181ccb1a0.txt
advanced_packaging/patent_da2d58c881907dcfe7fc.txt
advanced_packaging/patent_24a95eaf36a613e9a7ec.txt
advanced_packaging/patent_b1aaa836bc3709df1d70.txt
advanced_packaging/patent_6412ebaec693a0105f28.txt
advanced_packaging/patent_3d5e0281a6e4e66c129d.txt

In [38]:
# ============================================================
# STEP 11C — Inspect One Patent
# ============================================================

if not patent_files:
    raise FileNotFoundError(
        "No patent text files were found."
    )

sample_file = patent_files[0]

print("Sample file:")
print(sample_file)

print("\nFile contents:\n")
print(sample_file.read_text(
    encoding="utf-8",
    errors="ignore"
)[:5000])

Sample file:
/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/advanced_packaging/patent_23ebeda5c273212c3bcd.txt

File contents:

PATENT DOCUMENT
================

DOCUMENT ID: 23ebeda5c273212c3bcd
CPC SECTION: H
CATEGORY: advanced_packaging
SOURCE: BIGPATENT

ABSTRACT
========

A power interconnection system comprising a plurality of z-axis compliant connectors passing power and ground signals between a first circuit board to a second circuit board is disclosed. The interconnection system provides for an extremely low impedance through a broad range of frequencies and allows for large amounts of current to pass from one substrate to the next either statically or dynamically. The interconnection system may be located close to the die or may be further away depending upon the system requirements. The interconnection may also be used to take up mechanical tolerances between the two substrates while providing a low impedance. interconnect.

DETAILED DESCRIPTION
====================

CROSS-REFERENCE TO RELATED APPLICATIONS
 [0001] This application is a division of U.S. patent application Ser. No. 10/401,103, entitled System And Method For Processor Power Delivery And Thermal Management.
 [0002] Application 10/401,103 is a continuation of U.S. patent application Ser. No. 10/036,957, entitled “ULTRA-LOW IMPEDANCE POWER INTERCONNECTION SYSTEM FOR ELECTRONIC PACKAGES,” filed Dec. 20, 2001, hereby incorporated herein by reference.
 [0003] Application Ser. No. 10/036,957 is a continuation in part of U.S. patent application Ser. No. 09/885,780, entitled “INTER-CIRCUIT ENCAPSULATED PACKAGING,” filed Jun. 19, 2001, now abandoned, which is a continuation of U.S. patent application Ser. No. 09/353,428, entitled “INTER-CIRCUIT ENCAPSULATED PACKAGING,” filed Jul. 15, 1999, now U.S. Pat. No. 6,304,450.
 [0004] Application Ser. No. 10/036,957 is a continuation in part of U.S. patent application Ser. No. 09/432,878, entitled “INTER-CIRCUIT ENCAPSULATED PACKAGING FOR POWER DELIVERY,” filed Nov. 2, 1999, now U.S. Pat. No. 6,356,448.
 [0005] Application Ser. No. 10/036,957 is a continuation in part of U.S. patent application Ser. No. 09/785,892, entitled “APPARATUS FOR PROVIDING POWER TO A MICROPROCESSOR WITH INTEGRATED THERMAL AND EMI MANAGEMENT,” filed Feb. 16, 2001, now U.S. Pat. No. 6,452,113.
 [0006] Application Ser. No. 10/036,957 is a continuation in part of U.S. patent application Ser. No. 09/727,016, entitled “EMI CONTAINMENT USING INTER-CIRCUIT ENCAPSULATED PACKAGING TECHNOLOGY,” filed Nov. 28, 2000, now abandoned, which claims the benefit of the following applications:
 [0007] Provisional Patent Application No. 60/167,792, entitled “EMI CONTAINMENT USING INTER-CIRCUIT ENCAPSULATED PACKAGING TECHNOLOGY,” filed Nov. 29, 1999;
 [0008] Provisional Patent Application No. 60/171,065, entitled “INTER-CIRCUIT ENCAPSULATED PACKAGING TECHNOLOGY,” filed Dec. 16, 1999;
 [0009] Provisional Patent Application No. 60/183,474, entitled “DIRECT ATTACH POWER/THERMAL WITH INCEP TECHNOLOGY,” filed Feb. 18, 2000;
 [0010] Provisional Patent Application No. 60/187,777, entitled “NEXT GENERATION PACKAGING FOR EMI CONTAINMENT, POWER DELIVERY, AND THERMAL DISSIPATION USING INTER-CIRCUIT ENCAPSULATED PACKAGING TECHNOLOGY,” filed Mar. 8, 2000;
 [0011] Provisional Patent Application No. 60/196,059, entitled “EMI FRAME WITH POWER FEED-THROUGHS AND THERMAL INTERFACE MATERIAL IN AN AGGREGATE DIAMOND MIXTURE,” filed Apr. 10, 2000;
 [0012] Provisional Patent Application No. 60/219,813, entitled “HIGH-CURRENT MICROPROCESSOR POWER DELIVERY SYSTEMS,” filed Jul. 21, 2000; and
 [0013] Provisional Patent Application No. 60/232,971, entitled “INTEGRATED POWER DISTRIBUTION AND SEMICONDUCTOR PACKAGE,” filed Sep. 14, 2000.
 [0014] Application Ser. No. 10/036,957 is a continuation in part of U.S. patent application Ser. No. 09/798,541, entitled “THERMAL/MECHANICAL SPRINGBEAM MECHANISM FOR HEAT TRANSFER FROM HEAT SOURCE TO HEAT DISSIPATING DEVICE,” filed Mar. 2, 2001, now abandoned, which claims the benefit of Provisional Patent Application No. 60/186,769, entitled “THERMACEP SPRING BEAM,” filed Mar. 3, 2000.
 [0015] Application Ser. No. 10/036,957 is a continuation in part of U.S. patent application Ser. No. 09/910,524, entitled “HIGH PERFORMANCE THERMAL/MECHANICAL INTERFACE FOR FIXED GAP REFERENCES FOR HIGH HEAT FLUX AND POWER SEMICONDUCTOR APPLICATIONS,” filed Jul. 20, 2001, now abandoned, which claims the benefit of Provisional Patent Application No. 60/219,506, entitled “HIGH PERFORMANCE THERMAL/MECHANICAL INTERFACE,” filed Jul. 20, 2000.
 [0016] Application Ser. No. 10/036,957 is a continuation in part of U.S. patent application Ser. No. 09/921,153, entitled “VAPOR CHAMBER WITH INTEGRATED PIN ARRAY,” filed Aug. 2, 2001, now U.S. Pat. No. 6,490,160, which claims the benefit of the following applications:
 [0017] Provisional Patent Application No. 60/222,386, entitled “HIGH DENSITY CIRCULAR ‘PIN’ CONNECTOR FOR HIGH SPEED SIGNAL INTERCONNECT,” filed Aug. 2, 2000; and
 [0018] Provisional Patent Application No. 60/222,407, entitled “VAPOR HEATSINK COMBINATION FOR HIGH EFFI

In [39]:
# ============================================================
# STEP 12 — Parse and Chunk Patent Documents
# ============================================================

from pathlib import Path
import re
import pandas as pd


def parse_patent_file(file_path):
    """
    Parse a semiconductor patent text file and preserve
    its metadata and major sections.
    """

    text = file_path.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    # --------------------------------------------------------
    # Extract document metadata
    # --------------------------------------------------------

    document_id = re.search(
        r"DOCUMENT ID:\s*(.+)",
        text
    )

    cpc_section = re.search(
        r"CPC SECTION:\s*(.+)",
        text
    )

    category = re.search(
        r"CATEGORY:\s*(.+)",
        text
    )

    source = re.search(
        r"SOURCE:\s*(.+)",
        text
    )

    document_id = (
        document_id.group(1).strip()
        if document_id else file_path.stem
    )

    cpc_section = (
        cpc_section.group(1).strip()
        if cpc_section else None
    )

    category = (
        category.group(1).strip()
        if category else None
    )

    source = (
        source.group(1).strip()
        if source else None
    )

    # --------------------------------------------------------
    # Extract abstract
    # --------------------------------------------------------

    abstract_match = re.search(
        r"ABSTRACT\s*=+\s*(.*?)(?=\n[A-Z][A-Z\s]+={3,}|\Z)",
        text,
        flags=re.DOTALL
    )

    abstract = (
        abstract_match.group(1).strip()
        if abstract_match else ""
    )

    # --------------------------------------------------------
    # Extract detailed description
    # --------------------------------------------------------

    description_match = re.search(
        r"DETAILED DESCRIPTION\s*=+\s*(.*)",
        text,
        flags=re.DOTALL
    )

    description = (
        description_match.group(1).strip()
        if description_match else ""
    )

    # --------------------------------------------------------
    # Extract claims if present
    # --------------------------------------------------------

    claims_match = re.search(
        r"CLAIMS?\s*=+\s*(.*)",
        text,
        flags=re.DOTALL | re.IGNORECASE
    )

    claims = (
        claims_match.group(1).strip()
        if claims_match else ""
    )

    return {
        "document_id": document_id,
        "cpc_section": cpc_section,
        "category": category,
        "source": source,
        "abstract": abstract,
        "description": description,
        "claims": claims,
        "file_path": str(file_path),
    }

In [40]:
# ============================================================
# STEP 12B — Test Patent Parser
# ============================================================

parsed_patent = parse_patent_file(sample_file)

for key, value in parsed_patent.items():
    if key not in {"description", "claims"}:
        print(f"{key}: {value}")

print("\nDescription characters:", len(parsed_patent["description"]))
print("Claims characters:", len(parsed_patent["claims"]))

document_id: 23ebeda5c273212c3bcd
cpc_section: H
category: advanced_packaging
source: BIGPATENT
abstract: A power interconnection system comprising a plurality of z-axis compliant connectors passing power and ground signals between a first circuit board to a second circuit board is disclosed. The interconnection system provides for an extremely low impedance through a broad range of frequencies and allows for large amounts of current to pass from one substrate to the next either statically or dynamically. The interconnection system may be located close to the die or may be further away depending upon the system requirements. The interconnection may also be used to take up mechanical tolerances between the two substrates while providing a low impedance. interconnect.
file_path: /Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/advanced_packaging/patent_23ebeda5c273212c3bcd.txt

Description characters: 78512
Claims characters: 0

In [41]:
# ============================================================
# STEP 12C — Create Patent Chunks
# ============================================================

def chunk_text(text, chunk_size=1500, overlap=250):
    """
    Split text into overlapping chunks.

    chunk_size:
        Approximate number of characters per chunk.

    overlap:
        Number of characters shared between adjacent chunks.
    """

    if not text:
        return []

    chunks = []

    start = 0

    while start < len(text):

        end = start + chunk_size

        chunk = text[start:end].strip()

        if chunk:
            chunks.append(chunk)

        if end >= len(text):
            break

        start = end - overlap

    return chunks

In [42]:
# ============================================================
# STEP 12D — Build Structured Patent Chunks
# ============================================================

def create_patent_chunks(parsed_patent, chunk_size=1500, overlap=250):
    """
    Convert a parsed patent into RAG-ready chunks while
    preserving patent metadata.
    """

    chunks = []

    sections = {
        "abstract": parsed_patent["abstract"],
        "description": parsed_patent["description"],
        "claims": parsed_patent["claims"],
    }

    chunk_id = 0

    for section_name, section_text in sections.items():

        section_chunks = chunk_text(
            section_text,
            chunk_size=chunk_size,
            overlap=overlap,
        )

        for chunk in section_chunks:

            chunks.append({
                "chunk_id": chunk_id,
                "document_id": parsed_patent["document_id"],
                "category": parsed_patent["category"],
                "cpc_section": parsed_patent["cpc_section"],
                "source": parsed_patent["source"],
                "section": section_name,
                "text": chunk,
                "file_path": parsed_patent["file_path"],
            })

            chunk_id += 1

    return chunks

In [43]:
# ============================================================
# STEP 12E — Test Chunking
# ============================================================

patent_chunks = create_patent_chunks(parsed_patent)

print("Document:", parsed_patent["document_id"])
print("Number of chunks:", len(patent_chunks))

print("\nFirst chunk:")
print(patent_chunks[0])

Document: 23ebeda5c273212c3bcd
Number of chunks: 64

First chunk:
{'chunk_id': 0, 'document_id': '23ebeda5c273212c3bcd', 'category': 'advanced_packaging', 'cpc_section': 'H', 'source': 'BIGPATENT', 'section': 'abstract', 'text': 'A power interconnection system comprising a plurality of z-axis compliant connectors passing power and ground signals between a first circuit board to a second circuit board is disclosed. The interconnection system provides for an extremely low impedance through a broad range of frequencies and allows for large amounts of current to pass from one substrate to the next either statically or dynamically. The interconnection system may be located close to the die or may be further away depending upon the system requirements. The interconnection may also be used to take up mechanical tolerances between the two substrates while providing a low impedance. interconnect.', 'file_path': '/Users/jamesjr/Documents/SemiconductorPatentRAG/semiconductor_patents/advanced_packaging/patent_23ebeda5c273212c3bcd.txt'}

In [44]:
# ============================================================
# STEP 13 — Process Entire Semiconductor Patent Corpus
# ============================================================

from pathlib import Path
import pandas as pd

# Find all patent text files
patent_files = [
    path
    for path in CORPUS_ROOT.rglob("*.txt")
    if path.name != "metadata.csv"
]

print("Patent files found:", len(patent_files))

# ------------------------------------------------------------
# Parse and chunk every patent
# ------------------------------------------------------------

all_chunks = []

failed_files = []

for i, file_path in enumerate(patent_files, start=1):

    try:
        parsed = parse_patent_file(file_path)

        chunks = create_patent_chunks(
            parsed,
            chunk_size=1500,
            overlap=250,
        )

        all_chunks.extend(chunks)

    except Exception as e:
        failed_files.append({
            "file": str(file_path),
            "error": str(e),
        })

    if i % 50 == 0 or i == len(patent_files):
        print(
            f"Processed {i}/{len(patent_files)} patents | "
            f"Chunks: {len(all_chunks)}"
        )


print("\n========================================")
print("PROCESSING COMPLETE")
print("========================================")

print("Patents processed:", len(patent_files))
print("Total chunks:", len(all_chunks))
print("Failed files:", len(failed_files))

Patent files found: 500
Processed 50/500 patents | Chunks: 1103
Processed 100/500 patents | Chunks: 1605
Processed 150/500 patents | Chunks: 1656
Processed 200/500 patents | Chunks: 1708
Processed 250/500 patents | Chunks: 1758
Processed 300/500 patents | Chunks: 1809
Processed 350/500 patents | Chunks: 1860
Processed 400/500 patents | Chunks: 1910
Processed 450/500 patents | Chunks: 1960
Processed 500/500 patents | Chunks: 2093

========================================
PROCESSING COMPLETE
========================================
Patents processed: 500
Total chunks: 2093
Failed files: 0

In [45]:
# ============================================================
# STEP 13B — Create RAG Chunk DataFrame
# ============================================================

chunks_df = pd.DataFrame(all_chunks)

print("Shape:", chunks_df.shape)

print("\nColumns:")
print(chunks_df.columns.tolist())

display(chunks_df.head())

Shape: (2093, 8)

Columns:
['chunk_id', 'document_id', 'category', 'cpc_section', 'source', 'section', 'text', 'file_path']

,chunk_id,document_id,category,cpc_section,source,section,text,file_path
0,0,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,abstract,A power interconnection system comprising a pl...,/Users/jamesjr/Documents/SemiconductorPatentRA...
1,1,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description,CROSS-REFERENCE TO RELATED APPLICATIONS \n [00...,/Users/jamesjr/Documents/SemiconductorPatentRA...
2,2,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description,"RMAL AND EMI MANAGEMENT,” filed Feb. 16, 2001,...",/Users/jamesjr/Documents/SemiconductorPatentRA...
3,3,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description,"ation No. 60/219,813, entitled “HIGH-CURRENT M...",/Users/jamesjr/Documents/SemiconductorPatentRA...
4,4,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description,"ARRAY,” filed Aug. 2, 2001, now U.S. Pat. No. ...",/Users/jamesjr/Documents/SemiconductorPatentRA...

In [46]:
# ============================================================
# STEP 13C — Inspect Chunk Distribution
# ============================================================

print("Chunks by section:")
display(
    chunks_df["section"]
    .value_counts()
    .to_frame("count")
)

print("\nChunks by category:")
display(
    chunks_df["category"]
    .value_counts()
    .to_frame("count")
)

Chunks by section:

             count
section
description   1588
abstract       505

Chunks by category:

                              count
category
advanced_packaging             1580
power_semiconductors            133
transistor_device_technology    101
semiconductor_manufacturing     101
memory                           76
ai_advanced_semiconductor        52
photonics                        50

In [47]:
# ============================================================
# STEP 13D — Verify Patent Metadata
# ============================================================

print("Unique patents:", chunks_df["document_id"].nunique())

print("\nExample patent IDs:")
display(
    chunks_df[
        [
            "document_id",
            "category",
            "cpc_section",
            "source",
            "section",
        ]
    ].head(10)
)

Unique patents: 500

Example patent IDs:

,document_id,category,cpc_section,source,section
0,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,abstract
1,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
2,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
3,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
4,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
5,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
6,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
7,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
8,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description
9,23ebeda5c273212c3bcd,advanced_packaging,H,BIGPATENT,description

In [48]:
# ============================================================
# STEP 13E — Data Quality Check
# ============================================================

empty_text = chunks_df["text"].isna() | (
    chunks_df["text"].str.strip() == ""
)

print("Empty chunks:", empty_text.sum())

print(
    "Average chunk length:",
    chunks_df["text"].str.len().mean()
)

print(
    "Minimum chunk length:",
    chunks_df["text"].str.len().min()
)

print(
    "Maximum chunk length:",
    chunks_df["text"].str.len().max()
)

Empty chunks: 0
Average chunk length: 1287.583850931677
Minimum chunk length: 193
Maximum chunk length: 1500

In [49]:
# ============================================================
# STEP 14 — Connect Ollama Embeddings
# ============================================================

import requests
import numpy as np

OLLAMA_EMBED_URL = "http://localhost:11434/api/embeddings"
EMBED_MODEL = "nomic-embed-text"


def embed_text(text, model=EMBED_MODEL):
    """Create a local embedding using Ollama."""

    response = requests.post(
        OLLAMA_EMBED_URL,
        json={
            "model": model,
            "prompt": text,
        },
        timeout=120,
    )

    response.raise_for_status()

    return response.json()["embedding"]

In [50]:
# ============================================================
# STEP 14B — Test Embedding
# ============================================================

test_text = chunks_df.iloc[0]["text"]

test_embedding = embed_text(test_text)

print("Embedding model:", EMBED_MODEL)
print("Embedding dimensions:", len(test_embedding))
print("First 10 values:")
print(test_embedding[:10])

Embedding model: nomic-embed-text
Embedding dimensions: 768
First 10 values:
[0.9271228313446045, 0.7600730657577515, -3.2690510749816895, -1.303018569946289, 0.4443703889846802, -0.3875020742416382, 0.7055721282958984, 0.06263209134340286, -0.8916878700256348, -0.9662848711013794]

In [51]:
# ============================================================
# STEP 14C — Embed All Patent Chunks
# ============================================================

embeddings = []

total = len(chunks_df)

for i, text in enumerate(chunks_df["text"], start=1):

    embedding = embed_text(text)

    embeddings.append(embedding)

    if i % 50 == 0 or i == total:
        print(f"Embedded {i}/{total} chunks")

Embedded 50/2093 chunks
Embedded 100/2093 chunks
Embedded 150/2093 chunks
Embedded 200/2093 chunks
Embedded 250/2093 chunks
Embedded 300/2093 chunks
Embedded 350/2093 chunks
Embedded 400/2093 chunks
Embedded 450/2093 chunks
Embedded 500/2093 chunks
Embedded 550/2093 chunks
Embedded 600/2093 chunks
Embedded 650/2093 chunks
Embedded 700/2093 chunks
Embedded 750/2093 chunks
Embedded 800/2093 chunks
Embedded 850/2093 chunks
Embedded 900/2093 chunks
Embedded 950/2093 chunks
Embedded 1000/2093 chunks
Embedded 1050/2093 chunks
Embedded 1100/2093 chunks
Embedded 1150/2093 chunks
Embedded 1200/2093 chunks
Embedded 1250/2093 chunks
Embedded 1300/2093 chunks
Embedded 1350/2093 chunks
Embedded 1400/2093 chunks
Embedded 1450/2093 chunks
Embedded 1500/2093 chunks
Embedded 1550/2093 chunks
Embedded 1600/2093 chunks
Embedded 1650/2093 chunks
Embedded 1700/2093 chunks
Embedded 1750/2093 chunks
Embedded 1800/2093 chunks
Embedded 1850/2093 chunks
Embedded 1900/2093 chunks
Embedded 1950/2093 chunks
Embedded 2000/2093 chunks
Embedded 2050/2093 chunks
Embedded 2093/2093 chunks

In [52]:
# ============================================================
# STEP 14D — Create Embedding Matrix
# ============================================================

embedding_matrix = np.array(
    embeddings,
    dtype=np.float32
)

print("Embedding matrix shape:")
print(embedding_matrix.shape)

print("Data type:")
print(embedding_matrix.dtype)

Embedding matrix shape:
(2093, 768)
Data type:
float32

In [53]:
# ============================================================
# STEP 14E — Normalize Embeddings
# ============================================================

norms = np.linalg.norm(
    embedding_matrix,
    axis=1,
    keepdims=True
)

embedding_matrix_normalized = (
    embedding_matrix / np.maximum(norms, 1e-12)
)

print(
    "Normalized embedding matrix:",
    embedding_matrix_normalized.shape
)

Normalized embedding matrix: (2093, 768)

In [54]:
# ============================================================
# STEP 15 — Semantic Patent Retrieval
# ============================================================

def retrieve_patents(query, top_k=5):
    """
    Retrieve the most semantically similar patent chunks
    for a natural-language query.
    """

    # Embed the query using the same embedding model
    query_embedding = np.array(
        embed_text(query),
        dtype=np.float32
    )

    # Normalize query embedding
    query_norm = np.linalg.norm(query_embedding)

    query_embedding = (
        query_embedding / max(query_norm, 1e-12)
    )

    # Cosine similarity because both vectors are normalized
    similarities = embedding_matrix_normalized @ query_embedding

    # Get indices of highest similarity
    top_indices = np.argsort(similarities)[::-1][:top_k]

    # Build structured results
    results = chunks_df.iloc[top_indices].copy()

    results["similarity"] = similarities[top_indices]

    # Reset index for cleaner inspection
    results = results.reset_index(drop=True)

    return results

In [57]:
# ============================================================
# STEP 15C — Display Retrieved Patents
# ============================================================

def display_retrieval_results(results):
    """
    Display retrieved patent chunks safely.

    Only displays metadata columns that actually exist.
    """

    for i, row in results.iterrows():

        print("=" * 80)
        print(f"RESULT {i + 1}")
        print("=" * 80)

        # Core metadata
        print("Patent ID :", row.get("document_id", "N/A"))
        print("Category  :", row.get("category", "N/A"))
        print("Section   :", row.get("section", "N/A"))

        # Optional metadata
        if "source" in results.columns:
            print("Source    :", row["source"])

        if "cpc_section" in results.columns:
            print("CPC       :", row["cpc_section"])

        if "similarity" in results.columns:
            print(
                "Similarity:",
                round(float(row["similarity"]), 4)
            )

        print("\nText:")
        print(row.get("text", ""))

        print()

In [58]:
display_retrieval_results(results)

================================================================================
RESULT 1
================================================================================
Patent ID : d3ead82de489632b
Category  : semiconductor_manufacturing
Section   : DESCRIPTION
CPC       :
Similarity: 0.7792

Text:
CROSS-REFERENCE: This continuation patent application claims priority under 35 U.S.C. §120 from U.S. patent application No. 11/166,960, filed Jun. 23, 2005, now issued as U.S. Pat. No.7,685,481 B2, the disclosure of which is incorporated by reference herein in its entirety. BACKGROUND OF THE INVENTION 1. Field of the Invention The present invention relates generally to a system and method for quality control of integrated circuits manufactured by a semiconductor manufacturing process and, more particularly, to a system and method for analyzing defects in integrated circuits manufactured using a semiconductor fabrication process. 2. Description of the Prior Art The semiconductor manufacturing industry is continually evolving its fabrication processes and developing new processes to produce smaller and smaller geometries of the semiconductor devices being manufactured, because smaller devices typically generate less heat and operate at higher speeds than larger devices. Currently, a single integrated circuit chip may contain over one billion patterns. The occurrence of defects may cause lower yield in the final semiconductor product, where yield may be defined as the number of functional devices produced by the process as compared to the theoretical number of devices that could be produced assuming no bad devices. Improving yield is a critical problem in the semiconductor manufacturing industry and has a direct economic impact on it. In particular, a higher yield translates into more devices that may be sold by the manufacturer, and greater profits. Typically, semiconductor manufacturers collect data about various defects and analyze the data and, based on data analysis, adjust the integrated circuit design or process steps or tool specifications in an attempt to improve the yield of the process. This has created a need for a new generation of tools and techniques for defect analysis for semiconductor yield management. U.S. Pat. No. 6,470,229 B1 assigned to the same assignee as the present application discloses a yield management system and technique to generate a yield model. The system can also accept user input to modify the generated model. Additionally, a Genesis™ Bitmap Analysis product module is commercially available from the assignee of U.S. Pat. No. 6,470,229 B1 to extend the capabilities of the yield management system to direct bitmap-level analysis. The Bitmap Analysis product module suite allows a user to graph and analyze bitmap data. Bit failures are revealed to the user visually with interactive bitmaps. Analysis is performed on classified bitmap pattern information imported into a data sheet. Patterns may consist of single-bit fails, dual bits, rows, columns, etc. A general instance of a fail is described internally preferably using a list of one or more bounding rectangles to specify the set of bits that failed. Each bounding rectangle is specified by the bit coordinates of the lower-left and upper-right corners of the rectangle. Information on each of a die&#39;s bit failures can be viewed by toggling an “N of (total number of bit fails)” list in a Bit-Fail Browser. The following information may be displayed for each bit failure: Array—the array where the bit failure occurred. Block—the block

================================================================================
RESULT 2
================================================================================
Patent ID : 678e9b7f28681857
Category  : semiconductor_manufacturing
Section   : DESCRIPTION
CPC       :
Similarity: 0.7704

Text:
BACKGROUND OF THE INVENTION 1. Field of the Invention This invention relates generally to the manufacturing of high performance semiconductor devices. More specifically, this invention relates to a method of isolating optical defect images that have been captured during inspection for defects. 2. Discussion of the Related Art In order to remain competitive, a semiconductor manufacturer must continually increase the performance of the semiconductor integrated circuits being manufactured and at the same time, reduce the cost of the semiconductor integrated circuits. Part of the increase in performance and the reduction in cost of the semiconductor integrated circuits is accomplished by shrinking the device dimensions and by increasing the number of circuits per unit area on an integrated circuit chip. Another part of reducing the cost of a semiconductor chip is to increase the yield. As is known in the semiconductor manufacturing art, the yield of chips (also known as die) from each wafer is not 100% because of defects occurring during the manufacturing process. The number of good chips obtained from a wafer determines the yield. As can be appreciated, chips that must be discarded because of a defect increases the cost of the remaining usable chips. Each semiconductor chip requires numerous process steps such as oxidation, etching, metallization and wet chemical cleaning. In order to etch metal lines, for example, a layer of photoresist is formed on the surface of the semiconductor chips and patterned by developing the photoresist and washing away the unwanted portion of the photoresist. Because the metal lines and other metal structures have “critical” dimensions, that is, dimensions that can affect the performance of the semiconductor chip, the process of forming the photoresist pattern for each layer is examined during the manufacturing process. Some of these process steps involve placing the wafer on which the semiconductor chips are being manufactured into different tools during the manufacturing process. The optimization of each of these process steps requires an understanding of a variety of chemical reactions and physical processes in order to produce high performance, high yield circuits. The ability to view and characterize the surface and interface layers of a semiconductor chip in terms of their morphology, chemical composition and distribution is an invaluable aid to those involved in research and development, process, problem solving, and failure analysis of integrated circuits. In the course of modern semiconductor manufacturing, semiconductor wafers are routinely inspected using “scanning” tools to find defects. The scanning tool determines the location and other information concerning defects that are caught and this information is stored in a data file for later recapture and inspection of any of the defects. These data files are stored in a relational database that has the ability to generate wafer maps with defects shown in their relative positions. The data database typically has the ability to send these wafer map files to various review tools within the manufacturing plant. This is very useful as it allows for re-inspection on various after-scan inspection tools within the manufacturing plant. These

================================================================================
RESULT 3
================================================================================
Patent ID : 1bc765dc24dc5424
Category  : semiconductor_manufacturing
Section   : DESCRIPTION
CPC       :
Similarity: 0.7657

Text:
cases of the system can be raised. As a result, it is possible to construct a system having a high performance as a whole. FIG. 34 is a diagram showing a curve 30 representing changes in yield which are obtained during a build-up time of a mass production. The diagram also shows a curve 31 representing changes in detected-defect count. As shown in the Figure, as the yield increases, the number of detected defects decreases. Even in a build-up state of the yield, however, the number of detected defects may increase all of a sudden, decreasing the yield. In such a case, the generation of the defects is recognized quickly and production based on fabrication processes causing the defects needs to be halted temporarily in order to determine a countermeasure for causes of the generation of the defects. That is why the defect inspecting apparatus provided by the present invention is required. As described above, according to the present invention, the efficiency of illumination can be increased and the intensity of a diffraction light generated by a pattern on a substrate such as an LSI pattern can be reduced by using a spatial filter and adjusting the direction of the illumination. In addition, it is possible to decrease a threshold value at each of positions on a chip with variations different from each other. As a result, there is exhibited an effect of a capability of inspecting a substrate such as an LSI wafer for a foreign particle or a defect existing on the substrate with a high degree of sensitivity at a high throughput. In addition, according to the present invention, by using an ordinary TDI image sensor with a high sensitivity, there is exhibited an effect of a capability of detecting an infinitesimal foreign particle and a defect existing on an inspected substrate, on which repetitive and non-repetitive patterns coexist with each other, with a high degree of sensitivity at a high speed.

================================================================================
RESULT 4
================================================================================
Patent ID : 705e4ab08d381edd
Category  : semiconductor_manufacturing
Section   : DESCRIPTION
CPC       :
Similarity: 0.74

Text:
This application is a continuation of application Ser. No. 07/738,699, filed Jul. 31, 1991, now abandoned. FIELD OF THE INVENTION This invention generally relates to semiconductor devices and in particular for lithography methods. BACKGROUND OF THE INVENTION The semiconductor industry is constantly striving to achieve higher density electronic devices. As the industry has moved into micron, submicron and even sub-half-micron sized features to achieve higher densities, the need for improved lithography methods to create such minute features has increased. Among the problems associated with conventional lithography techniques are the lack of uniformity of exposure of resist through a thick layer of resist and scattered light within the layer of resist due to reflective metallized surfaces under the resist. These problems tend to compound the loss of resolution problem by creating ill-defined patterns at the onset. Standard methods for image development, in the exposed etch resist, fall short of the requirements for sub-half-micron feature generation. Wet development of the etch resist often produces a positive-grade slope on the feature sidewall that degrades the contrast of image transfer into the underlying thin film during the dry etch process. This is due to the less than infinite etch rate selectivity between the resist and the film material. Thus, there is a need for a method for forming high resolution submicron and sub-half-micron sized features on a semiconductor device. SUMMARY OF THE INVENTION This is a method for forming patterned features. The method comprises: forming a single layer of resist on a substrate, the layer having a thickness; patterning the resist by selective exposure to a first energy source to modify the developing properties of portions of the resist, leaving an amount of the thickness unexposed; and developing the resist. Preferably, the developing is done with a second energy source and a developing reagent; the first and second energy sources are both ultraviolet light; the resist is acrylic-based; a dye is incorporated into the resist to prevent exposure of the amount of the thickness to be left unexposed; the developing reagent includes oxygen or hydrogen; the patterning step occurs in an oxygen-free environment; a nitrogen purge is used to create the oxygen-free environment; and the substrate has multiple layers. A diffusion reagent may be diffused into unmodified regions of the resist before the developing step. The diffusion reagent may contain silicon or may contain titanium. This is also a device which comprises: a substrate; a layer of resist over the substrate; and an energy absorbing dye in the resist. BRIEF DESCRIPTION OF THE DRAWINGS In the drawings: FIG. 1 is a cross-sectional view of forming a resist layer on a substrate; FIG. 2 is a cross-sectional view of formation of crosslinked regions; FIG. 3 is a cross-sectional view of reagent exposure in a first preferred embodiment of the present invention; FIG. 4 is a cross-sectional view of patterning a first preferred embodiment of the present invention; FIG. 5 is a cross-sectional view of patterning a second preferred embodiment of the present invention. Corresponding numerals

================================================================================
RESULT 5
================================================================================
Patent ID : 59a55217020f07d1
Category  : transistor_device_technology
Section   : DESCRIPTION
CPC       :
Similarity: 0.7368

Text:
defect is detected is corrected. [0115] Here, a case where the defocus amount is acquired when the defect is detected has been described, but the defocus amount may be acquired irrespective of presence of detection of the defect. [0116] By constructing a database of a wafer history including the device pattern and the defocus amount, a cause for an inadvertently generated yield reduction can be easily investigated, and the reduction of the yield can be prevented beforehand. [0117] Examples of the semiconductor device include a liquid crystal display (LCD) and devices using LCD (e.g., a cellular phone, liquid crystal television, personal computer, PDA) in addition to a DRAM, logic LSI, and system LSI (DRAM embedded LSI). [0118] As described above, the photo mask in which the line width ratio of the shielding portion, transmitting portion, and phase grooved portion is 2:1:1 and a phase difference between the lights transmitted through the transmitting portion and the phase grooved portion is 90° is a most ideal photo mask for focus measuring. However, even by the use of the photo mask of the embodiment in which the phase difference and the line width ratio satisfy [Equation 2] instead of the above-described ideal photo mask, the high precision focus measuring substantially similar to that by the ideal photo mask is possible. Accordingly, for example, even when the asymmetrical diffraction grating is formed on a usual alternating type phase shift mask, a grooved amount can be set with respect to the phase difference having few loads on the mask manufacturing, and a high precision focus measuring technique equivalent to a conventional technique can be realized even in various exposure masks. [0119] Additional advantages and modifications will readily occur to those skilled in the art. Therefore, the invention in its broader aspects is not limited to the specific details and representative embodiments shown and described herein. Accordingly, various modifications may be made without departing from the spirit or scope of the general inventive concept as defined by the appended claims and their equivalents.

In [59]:
# STEP 15D — Inspect Actual Retrieval Schema

print("Result columns:")
print(results.columns.tolist())

print("\nChunk DataFrame columns:")
print(chunks_df.columns.tolist())

print("\nExample retrieved record:")
display(results.head(1).T)

Result columns:
['document_id', 'category', 'cpc_section', 'section', 'similarity', 'abstract', 'text']

Chunk DataFrame columns:
['chunk_id', 'document_id', 'category', 'cpc_section', 'source', 'section', 'text', 'file_path']

Example retrieved record:

                                                             0
document_id                                   d3ead82de489632b
category                           semiconductor_manufacturing
cpc_section
section                                            DESCRIPTION
similarity                                            0.779211
abstract     A system and method for defect analysis are di...
text         CROSS-REFERENCE: This continuation patent appl...

In [60]:
# ============================================================
# STEP 15E — Finalize Patent Retrieval Results
# ============================================================

def retrieve_patents(query, top_k=5):
    """
    Retrieve the most semantically similar patent chunks.

    Returns the original patent metadata together with
    the similarity score.
    """

    # Embed query
    query_embedding = np.array(
        embed_text(query),
        dtype=np.float32
    )

    # Normalize query
    query_norm = np.linalg.norm(query_embedding)

    query_embedding = (
        query_embedding / max(query_norm, 1e-12)
    )

    # Calculate cosine similarity
    similarities = (
        embedding_matrix_normalized @ query_embedding
    )

    # Top-k indices
    top_indices = np.argsort(similarities)[::-1][:top_k]

    # Retrieve original records
    results = chunks_df.iloc[top_indices].copy()

    # Add similarity
    results["similarity"] = similarities[top_indices]

    # Reset index
    results = results.reset_index(drop=True)

    return results

In [61]:
# ============================================================
# STEP 15F — Verify Retrieval Schema
# ============================================================

question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

results = retrieve_patents(
    question,
    top_k=5
)

print("Retrieved:", len(results))
print("\nColumns:")
print(results.columns.tolist())

display(
    results[
        [
            "document_id",
            "category",
            "section",
            "similarity",
            "text",
        ]
    ]
)

Retrieved: 5

Columns:
['chunk_id', 'document_id', 'category', 'cpc_section', 'source', 'section', 'text', 'file_path', 'similarity']

,document_id,category,section,similarity,text
0,01ea3f6e9244856597cb,advanced_packaging,description,0.739352,TECHNICAL FIELD \n The invention described her...
1,f2ada019c57f2835065e,advanced_packaging,description,0.732492,"technology that, in the future, may particular..."
2,a969f5fbe709d62ce477,advanced_packaging,description,0.727849,BACKGROUND \n [0001] The present invention rel...
3,01ea3f6e9244856597cb,advanced_packaging,description,0.727297,ine without damage the packaged is “qualified”...
4,b8ead524636a26d39526,advanced_packaging,description,0.726091,wherein the wafer is severed into individual s...

In [62]:
# ============================================================
# STEP 16 — Build Context from Retrieved Patents
# ============================================================

def build_retrieved_context(results):
    """
    Convert retrieved patent chunks into structured
    context for the LLM.
    """

    context_parts = []

    for i, row in results.iterrows():

        context_parts.append(
            f"""
PATENT RESULT {i + 1}

Patent ID: {row["document_id"]}
Category: {row["category"]}
CPC Section: {row["cpc_section"]}
Section: {row["section"]}
Similarity: {row["similarity"]:.4f}

PATENT TEXT:
{row["text"]}
"""
        )

    return "\n".join(context_parts)

In [63]:
# ============================================================
# STEP 16B — Create Real RAG Context
# ============================================================

context = build_retrieved_context(results)

print(context)

PATENT RESULT 1

Patent ID: 01ea3f6e9244856597cb
Category: advanced_packaging
CPC Section: H
Section: description
Similarity: 0.7394

PATENT TEXT:
TECHNICAL FIELD
 The invention described herein relates generally to semiconductor device packaging. In particular, the invention relates to a method and package for a semiconductor device that is resistant to electrostatic discharge that can be caused by various factors.
 BACKGROUND
 The semiconductor industry makes wide use of standard BGA (ball grid array) type semiconductor packages. Such packages generally include a BT (bismaleimide triazine) core having various metallization and solder mask layers to form the substrate. A semiconductor die is attached to the substrate and electrically connected to various electrical connections of the substrate using ball attach or wire-bonding techniques. The wire bonds and the die are typically encapsulated with a protective layer of encapsulant. Such packages and the methods of their construction are well known to persons having ordinary skill in the semiconductor packaging arts. Additionally, ball attach arrangements are provided with an underfill encapsulant to protect the bonding arrangements of the solder balls.
 Commonly, the packages are then provided with a stiffener and a heat spreader to complete the packages. These completed packages are then subject to a series of tests used to qualify the packages to insure they meet all the necessary specifications prior to shipping.
 One such test subjects the package to a series of electrostatic discharge (ESD) events to determine the packages robustness and resistance to these ES


PATENT RESULT 2

Patent ID: f2ada019c57f2835065e
Category: advanced_packaging
CPC Section: H
Section: description
Similarity: 0.7325

PATENT TEXT:
technology that, in the future, may particularly benefit from such an advancement includes the art of semiconductor packaging. Semiconductor devices, such as memory devices and processors, are generally fabricated in very large numbers. Typically, several semiconductor devices are fabricated on a wafer or other large-scale substrate that includes a layer of semiconductor material (e.g., silicon, gallium arsenide, or indium phosphide). The semiconductor devices are then singulated, or diced, from the wafer or other large-scale substrate to provide semiconductor “chips” or dice.
 [0012] Conventionally, semiconductor dice have been packaged for protection and to facilitate the formation of electrical connections to the small bond pads thereof. Conventional semiconductor device packages typically include an assembly of a semiconductor die and a higher level substrate board (e.g., a circuit board) or leads. Bond pads of the semiconductor die are electrically connected (e.g., by wire bonds or otherwise) to contact pads of a higher level substrate or to leads. The assembly may then be packaged. For example, assemblies that include a semiconductor die with leads connected to the bond pads thereof are typically packaged by use of transfer molding techniques to secure the leads in place and to protect the active surface of the semiconductor die and the wire bonds or other intermediate conductive elements. Assemblies including a semiconductor die and a higher level substrate may be pa


PATENT RESULT 3

Patent ID: a969f5fbe709d62ce477
Category: advanced_packaging
CPC Section: H
Section: description
Similarity: 0.7278

PATENT TEXT:
BACKGROUND
 [0001] The present invention relates to semiconductor fabrication and, in particular, to semiconductor packages having a semiconductor element mounted thereon, for transferring a high-speed signal, and particularly to the wiring configuration on an interposer substrate of the device package.
 [0002] Integrated circuit (“IC”) packaging is the final stage of semiconductor device fabrication per se, followed by IC testing. Contemporary electronic apparatuses include components that transmit very high-speed signals having a pulse width that corresponds, after being converted to frequency domain, to several hundreds of megahertz to one gigahertz. As technology advances, these signal speeds have been increased even more, and there is a demand for the transmission of a signal that corresponds to a frequency of several gigahertz or higher.
 [0003] Further, multifunctional ICs and IC modules have been developed that are like system large scale integration (“LSI”) chips, and these ICs are mounted in multi-terminal packages, such as ball grid arrays (“BGA”) or chip scale packages (“CSP”). That is, an IC having a high-speed signal transmission interface tends to be mounted in a multi-terminal semiconductor package, such as a BGA or a CSP. Ball grid array packages and their variants have existed since the 1970s. The BGA is descended from the pin grid array (“PGA”), which is a package with one face covered (or partly covered) with pins in a grid pattern. These pins are used


PATENT RESULT 4

Patent ID: 01ea3f6e9244856597cb
Category: advanced_packaging
CPC Section: H
Section: description
Similarity: 0.7273

PATENT TEXT:
ine without damage the packaged is “qualified”.
 This commonly constructed package has provided satisfactory ESD protection until recently. Now, with increasing scaling of circuit elements formed on the die, smaller less ESD resistant devices and elements are becoming more common. These devices have increased vulnerability to ESD events. Thus, the traditional package format is increasingly lacking in the ability to protect these vulnerable elements from ESD events. Accordingly, the incidence of ESD induced package failure has been rising and is expected to continue to do so as circuitry and device sizes continue to shrink.
 Accordingly, what is needed is a packaging design and approach that provides increased resistance to ESD induced package failure.
 SUMMARY OF THE INVENTION
 In accordance with the principles of the present invention, an improved semiconductor package and methods for its fabrication are disclosed.
 In general, the present invention is directed toward methods and packages that increase the package impedance of a semiconductor package thereby increasing the resistance of the overall package to ESD associated package failures.
 One embodiment of the invention comprises a semiconductor integrated circuit package having a substrate with a die attached to the front side thereof. The package includes a die electrically connected with the substrate. The package further including a discharge shield configured to protect the die from electrostatic discharge eve


PATENT RESULT 5

Patent ID: b8ead524636a26d39526
Category: advanced_packaging
CPC Section: H
Section: description
Similarity: 0.7261

PATENT TEXT:
wherein the wafer is severed into individual semiconductor devices. While integrated packages may be formed of two or more chips, the integration of multiple functional circuits on single chips has also become common, leading to chips with a large number of input/output (I/O) terminals for signal transmission, power supply, ground (or bias), and testing. There has been a continuing effort in the industry to enhance the functional density of semiconductor devices while simultaneously decreasing their size. Densification in chip fabrication has many advantages, including overall reduction in cost, reduction in package volume, and enhanced electrical efficiency due to shorter signal transmission paths. Moreover, increased miniaturization has enabled the formation of complex integrated circuits on a single chip or die, such as a so-called “computer on a chip.”
 [0006] In general, the circuits on a chip or die terminate in conductive bond pads arrayed on the die&#39;s active surface, typically in one or more rows about the die periphery or across a central portion of the die. These bond pads are generally formed of aluminum or an aluminum alloy and are designed to be conductively connected to terminals of a carrier substrate such as an interposer or circuit board, the pattern of terminals on which may not correspond to the locations of the corresponding bond pads on the die. In addition, the lateral bond pad-to-bond pad separation (pitch) may be too close for satisfactory direct

In [64]:
# ============================================================
# STEP 16C — Real RAG Query
# ============================================================

question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

results = retrieve_patents(
    question,
    top_k=5
)

context = build_retrieved_context(results)

prompt = build_rag_prompt(
    question,
    context
)

answer = ask_ollama(prompt)

print("=" * 80)
print("RAG ANSWER")
print("=" * 80)
print(answer)

================================================================================
RAG ANSWER
================================================================================
The available patent context is insufficient to determine techniques used to reduce impedance in semiconductor packaging. The retrieved patents primarily focus on enhancing electrostatic discharge (ESD) resistance, improving high-speed signal transmission, and optimizing packaging structures (e.g., BGA/CSP configurations, encapsulation methods). None of the texts explicitly mention techniques for reducing impedance, such as specific material choices, design modifications, or circuit configurations aimed at lowering electrical resistance. The emphasis is on increasing impedance for ESD protection or managing signal integrity in high-speed applications, not on impedance reduction.

In [65]:
# ============================================================
# STEP 16D — Show Sources
# ============================================================

print("\n")
print("=" * 80)
print("PATENTS USED")
print("=" * 80)

for i, row in results.iterrows():

    print(
        f"{i + 1}. "
        f"{row['document_id']} | "
        f"{row['category']} | "
        f"{row['section']} | "
        f"similarity={row['similarity']:.4f}"
    )

================================================================================
PATENTS USED
================================================================================
1. 01ea3f6e9244856597cb | advanced_packaging | description | similarity=0.7394
2. f2ada019c57f2835065e | advanced_packaging | description | similarity=0.7325
3. a969f5fbe709d62ce477 | advanced_packaging | description | similarity=0.7278
4. 01ea3f6e9244856597cb | advanced_packaging | description | similarity=0.7273
5. b8ead524636a26d39526 | advanced_packaging | description | similarity=0.7261

In [66]:
# STEP 17 — Deduplicated Semantic Retrieval

def retrieve_patents(query, top_k=5):
    """
    Retrieve semantically similar patent chunks while ensuring
    that each patent appears only once.

    The highest-similarity chunk is retained for each patent.
    """

    query_embedding = np.array(
        embed_text(query),
        dtype=np.float32
    )

    query_norm = np.linalg.norm(query_embedding)

    query_embedding = (
        query_embedding / max(query_norm, 1e-12)
    )

    similarities = (
        embedding_matrix_normalized @ query_embedding
    )

    # Rank all chunks by similarity
    ranked_indices = np.argsort(similarities)[::-1]

    selected_indices = []
    seen_patents = set()

    for idx in ranked_indices:

        patent_id = chunks_df.iloc[idx]["document_id"]

        if patent_id in seen_patents:
            continue

        seen_patents.add(patent_id)
        selected_indices.append(idx)

        if len(selected_indices) == top_k:
            break

    results = chunks_df.iloc[selected_indices].copy()

    results["similarity"] = similarities[selected_indices]

    results = results.reset_index(drop=True)

    return results

In [67]:
question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

results = retrieve_patents(
    question,
    top_k=5
)

display_retrieval_results(results)

================================================================================
RESULT 1
================================================================================
Patent ID : 01ea3f6e9244856597cb
Category  : advanced_packaging
Section   : description
Source    : BIGPATENT
CPC       : H
Similarity: 0.7394

Text:
TECHNICAL FIELD
 The invention described herein relates generally to semiconductor device packaging. In particular, the invention relates to a method and package for a semiconductor device that is resistant to electrostatic discharge that can be caused by various factors.
 BACKGROUND
 The semiconductor industry makes wide use of standard BGA (ball grid array) type semiconductor packages. Such packages generally include a BT (bismaleimide triazine) core having various metallization and solder mask layers to form the substrate. A semiconductor die is attached to the substrate and electrically connected to various electrical connections of the substrate using ball attach or wire-bonding techniques. The wire bonds and the die are typically encapsulated with a protective layer of encapsulant. Such packages and the methods of their construction are well known to persons having ordinary skill in the semiconductor packaging arts. Additionally, ball attach arrangements are provided with an underfill encapsulant to protect the bonding arrangements of the solder balls.
 Commonly, the packages are then provided with a stiffener and a heat spreader to complete the packages. These completed packages are then subject to a series of tests used to qualify the packages to insure they meet all the necessary specifications prior to shipping.
 One such test subjects the package to a series of electrostatic discharge (ESD) events to determine the packages robustness and resistance to these ES

================================================================================
RESULT 2
================================================================================
Patent ID : f2ada019c57f2835065e
Category  : advanced_packaging
Section   : description
Source    : BIGPATENT
CPC       : H
Similarity: 0.7325

Text:
technology that, in the future, may particularly benefit from such an advancement includes the art of semiconductor packaging. Semiconductor devices, such as memory devices and processors, are generally fabricated in very large numbers. Typically, several semiconductor devices are fabricated on a wafer or other large-scale substrate that includes a layer of semiconductor material (e.g., silicon, gallium arsenide, or indium phosphide). The semiconductor devices are then singulated, or diced, from the wafer or other large-scale substrate to provide semiconductor “chips” or dice.
 [0012] Conventionally, semiconductor dice have been packaged for protection and to facilitate the formation of electrical connections to the small bond pads thereof. Conventional semiconductor device packages typically include an assembly of a semiconductor die and a higher level substrate board (e.g., a circuit board) or leads. Bond pads of the semiconductor die are electrically connected (e.g., by wire bonds or otherwise) to contact pads of a higher level substrate or to leads. The assembly may then be packaged. For example, assemblies that include a semiconductor die with leads connected to the bond pads thereof are typically packaged by use of transfer molding techniques to secure the leads in place and to protect the active surface of the semiconductor die and the wire bonds or other intermediate conductive elements. Assemblies including a semiconductor die and a higher level substrate may be pa

================================================================================
RESULT 3
================================================================================
Patent ID : a969f5fbe709d62ce477
Category  : advanced_packaging
Section   : description
Source    : BIGPATENT
CPC       : H
Similarity: 0.7278

Text:
BACKGROUND
 [0001] The present invention relates to semiconductor fabrication and, in particular, to semiconductor packages having a semiconductor element mounted thereon, for transferring a high-speed signal, and particularly to the wiring configuration on an interposer substrate of the device package.
 [0002] Integrated circuit (“IC”) packaging is the final stage of semiconductor device fabrication per se, followed by IC testing. Contemporary electronic apparatuses include components that transmit very high-speed signals having a pulse width that corresponds, after being converted to frequency domain, to several hundreds of megahertz to one gigahertz. As technology advances, these signal speeds have been increased even more, and there is a demand for the transmission of a signal that corresponds to a frequency of several gigahertz or higher.
 [0003] Further, multifunctional ICs and IC modules have been developed that are like system large scale integration (“LSI”) chips, and these ICs are mounted in multi-terminal packages, such as ball grid arrays (“BGA”) or chip scale packages (“CSP”). That is, an IC having a high-speed signal transmission interface tends to be mounted in a multi-terminal semiconductor package, such as a BGA or a CSP. Ball grid array packages and their variants have existed since the 1970s. The BGA is descended from the pin grid array (“PGA”), which is a package with one face covered (or partly covered) with pins in a grid pattern. These pins are used

================================================================================
RESULT 4
================================================================================
Patent ID : b8ead524636a26d39526
Category  : advanced_packaging
Section   : description
Source    : BIGPATENT
CPC       : H
Similarity: 0.7261

Text:
wherein the wafer is severed into individual semiconductor devices. While integrated packages may be formed of two or more chips, the integration of multiple functional circuits on single chips has also become common, leading to chips with a large number of input/output (I/O) terminals for signal transmission, power supply, ground (or bias), and testing. There has been a continuing effort in the industry to enhance the functional density of semiconductor devices while simultaneously decreasing their size. Densification in chip fabrication has many advantages, including overall reduction in cost, reduction in package volume, and enhanced electrical efficiency due to shorter signal transmission paths. Moreover, increased miniaturization has enabled the formation of complex integrated circuits on a single chip or die, such as a so-called “computer on a chip.”
 [0006] In general, the circuits on a chip or die terminate in conductive bond pads arrayed on the die&#39;s active surface, typically in one or more rows about the die periphery or across a central portion of the die. These bond pads are generally formed of aluminum or an aluminum alloy and are designed to be conductively connected to terminals of a carrier substrate such as an interposer or circuit board, the pattern of terminals on which may not correspond to the locations of the corresponding bond pads on the die. In addition, the lateral bond pad-to-bond pad separation (pitch) may be too close for satisfactory direct

================================================================================
RESULT 5
================================================================================
Patent ID : a412f1b3ea8b5836df4b
Category  : advanced_packaging
Section   : description
Source    : BIGPATENT
CPC       : H
Similarity: 0.7229

Text:
FIELD OF THE DISCLOSURE
 [0001] The present disclosure is in the field of semiconductor packaging and more particularly in the field of copper pillar interconnects in semiconductor packaging.
 BACKGROUND
 [0002] Integrated circuit (IC) fabrication processes have produced ICs with reduced node spacing in the range of 48 nm and 28 nm nodes, for example. Material having an extremely low dielectric constant (ELK) has been used to accommodate the reduced node spacing and to enhance electrical performance of the ICs that are produced with such small node spacing. The ELK material may include relatively porous material which may be susceptible to cracking in response to certain stresses.
 [0003] Interconnect pillars constructed from more rigid conductive materials such as copper have been used along with solder in certain solder bump connections between a semiconductor die and a substrate. In electronic packaging, for example, a flip chip can include a pillar that extends from a contact on a die or wafer to a solder connection on a substrate. The solder connection can be a solder on pad (SOP) connection, for example.
 [0004] The use of pillars provides an improvement over earlier semiconductor interconnect techniques by allowing a very high density of interconnects. The metallurgical properties of the pillars compared to earlier solder structures allow the smaller pitch connections to maintain an appropriate standoff distance between a semiconductor die and a substrate to which

In [68]:
print("\n")
print("=" * 80)
print("PATENTS USED")
print("=" * 80)

for i, row in results.iterrows():

    print(
        f"{i + 1}. "
        f"{row['document_id']} | "
        f"{row['category']} | "
        f"{row['section']} | "
        f"similarity={row['similarity']:.4f}"
    )

================================================================================
PATENTS USED
================================================================================
1. 01ea3f6e9244856597cb | advanced_packaging | description | similarity=0.7394
2. f2ada019c57f2835065e | advanced_packaging | description | similarity=0.7325
3. a969f5fbe709d62ce477 | advanced_packaging | description | similarity=0.7278
4. b8ead524636a26d39526 | advanced_packaging | description | similarity=0.7261
5. a412f1b3ea8b5836df4b | advanced_packaging | description | similarity=0.7229

In [69]:
# STEP 18A — Build Patent-Level Metadata

patent_metadata = []

for file_path in patent_files:

    try:
        parsed = parse_patent_file(file_path)

        patent_metadata.append({
            "document_id": parsed["document_id"],
            "category": parsed["category"],
            "cpc_section": parsed["cpc_section"],
            "source": parsed["source"],
            "abstract": parsed["abstract"],
            "claims": parsed["claims"],
            "file_path": parsed["file_path"],
        })

    except Exception as e:
        print(f"Failed to parse {file_path}: {e}")


patent_metadata_df = pd.DataFrame(patent_metadata)

print("Patent metadata loaded")
print("Patents:", len(patent_metadata_df))
print("Columns:")
print(patent_metadata_df.columns.tolist())

Patent metadata loaded
Patents: 500
Columns:
['document_id', 'category', 'cpc_section', 'source', 'abstract', 'claims', 'file_path']

In [70]:
# STEP 18B — Check Claims Coverage

claims_available = patent_metadata_df["claims"].fillna("").str.strip().ne("")

print("=" * 80)
print("PATENT CLAIMS COVERAGE")
print("=" * 80)

print("Total patents :", len(patent_metadata_df))
print("With claims   :", claims_available.sum())
print("Without claims:", (~claims_available).sum())

print(
    "Coverage      :",
    round(claims_available.mean() * 100, 2),
    "%"
)

================================================================================
PATENT CLAIMS COVERAGE
================================================================================
Total patents : 500
With claims   : 0
Without claims: 500
Coverage      : 0.0 %

In [71]:
# STEP 18C — Enrich Retrieved Results with Patent Evidence

def enrich_retrieval_results(results):
    """
    Add patent-level metadata, abstracts, and claims
    to semantic retrieval results.
    """

    enriched = results.copy()

    metadata_lookup = patent_metadata_df.set_index(
        "document_id"
    )

    enriched["abstract"] = ""
    enriched["claims"] = ""

    for idx, row in enriched.iterrows():

        patent_id = row["document_id"]

        if patent_id in metadata_lookup.index:

            patent_info = metadata_lookup.loc[patent_id]

            enriched.at[idx, "abstract"] = patent_info["abstract"]
            enriched.at[idx, "claims"] = patent_info["claims"]

    return enriched

In [72]:
enriched_results = enrich_retrieval_results(results)

print(enriched_results.columns.tolist())

['chunk_id', 'document_id', 'category', 'cpc_section', 'source', 'section', 'text', 'file_path', 'similarity', 'abstract', 'claims']

In [73]:
# STEP 18D — Inspect Patent Evidence

for i, row in enriched_results.iterrows():

    print("=" * 80)
    print(f"PATENT {i + 1}")
    print("=" * 80)

    print("Patent ID :", row["document_id"])
    print("Category  :", row["category"])
    print("CPC       :", row["cpc_section"])
    print("Source    :", row["source"])
    print("Similarity:", round(float(row["similarity"]), 4))

    print("\nABSTRACT")
    print("-" * 80)
    print(row["abstract"][:1500])

    print("\nCLAIMS")
    print("-" * 80)

    if row["claims"]:
        print(row["claims"][:2500])
    else:
        print("No claims available.")

    print("\nRETRIEVED DESCRIPTION CHUNK")
    print("-" * 80)
    print(row["text"][:1500])

    print()

================================================================================
PATENT 1
================================================================================
Patent ID : 01ea3f6e9244856597cb
Category  : advanced_packaging
CPC       : H
Source    : BIGPATENT
Similarity: 0.7394

ABSTRACT
--------------------------------------------------------------------------------
Embodiments of the invention include a semiconductor integrated circuit package that includes a substrate having an integrated circuit die attached thereto. The package includes a ESD shield attached to the substrate. The ESD shield configured to increase the ESD hardness of the package. The ESD shield can further serve to stiffen the package to prevent warping and operate as a heat spreader.

CLAIMS
--------------------------------------------------------------------------------
No claims available.

RETRIEVED DESCRIPTION CHUNK
--------------------------------------------------------------------------------
TECHNICAL FIELD
 The invention described herein relates generally to semiconductor device packaging. In particular, the invention relates to a method and package for a semiconductor device that is resistant to electrostatic discharge that can be caused by various factors.
 BACKGROUND
 The semiconductor industry makes wide use of standard BGA (ball grid array) type semiconductor packages. Such packages generally include a BT (bismaleimide triazine) core having various metallization and solder mask layers to form the substrate. A semiconductor die is attached to the substrate and electrically connected to various electrical connections of the substrate using ball attach or wire-bonding techniques. The wire bonds and the die are typically encapsulated with a protective layer of encapsulant. Such packages and the methods of their construction are well known to persons having ordinary skill in the semiconductor packaging arts. Additionally, ball attach arrangements are provided with an underfill encapsulant to protect the bonding arrangements of the solder balls.
 Commonly, the packages are then provided with a stiffener and a heat spreader to complete the packages. These completed packages are then subject to a series of tests used to qualify the packages to insure they meet all the necessary specifications prior to shipping.
 One such test subjects the package to a series of electrostatic discharge (ESD) events to determine the packages robustness and resistance to these ES

================================================================================
PATENT 2
================================================================================
Patent ID : f2ada019c57f2835065e
Category  : advanced_packaging
CPC       : H
Source    : BIGPATENT
Similarity: 0.7325

ABSTRACT
--------------------------------------------------------------------------------
A selective deposition system and method for initiating deposition of an unconsolidated material at a defined starting surface are disclosed. The system includes a sensor system for measuring an upper surface of a workpiece and a surface level of the unconsolidated material as deposited on the upper surface of the workpiece. The deposition process and measurement of the upper surface of the material on the workpiece are continuously performed as the material is applied in a layer by layer deposition process resulting in a substantially uniform material of a predetermined thickness beginning at the upper surface of the workpiece.

CLAIMS
--------------------------------------------------------------------------------
No claims available.

RETRIEVED DESCRIPTION CHUNK
--------------------------------------------------------------------------------
technology that, in the future, may particularly benefit from such an advancement includes the art of semiconductor packaging. Semiconductor devices, such as memory devices and processors, are generally fabricated in very large numbers. Typically, several semiconductor devices are fabricated on a wafer or other large-scale substrate that includes a layer of semiconductor material (e.g., silicon, gallium arsenide, or indium phosphide). The semiconductor devices are then singulated, or diced, from the wafer or other large-scale substrate to provide semiconductor “chips” or dice.
 [0012] Conventionally, semiconductor dice have been packaged for protection and to facilitate the formation of electrical connections to the small bond pads thereof. Conventional semiconductor device packages typically include an assembly of a semiconductor die and a higher level substrate board (e.g., a circuit board) or leads. Bond pads of the semiconductor die are electrically connected (e.g., by wire bonds or otherwise) to contact pads of a higher level substrate or to leads. The assembly may then be packaged. For example, assemblies that include a semiconductor die with leads connected to the bond pads thereof are typically packaged by use of transfer molding techniques to secure the leads in place and to protect the active surface of the semiconductor die and the wire bonds or other intermediate conductive elements. Assemblies including a semiconductor die and a higher level substrate may be pa

================================================================================
PATENT 3
================================================================================
Patent ID : a969f5fbe709d62ce477
Category  : advanced_packaging
CPC       : H
Source    : BIGPATENT
Similarity: 0.7278

ABSTRACT
--------------------------------------------------------------------------------
Packages and methods for mitigating plating stub effects. The semiconductor package includes an interposer substrate having a first side, a second side, a peripheral edge connecting the first side with the second side, a signal line on the first side, and an electrode pad on the first side. A semiconductor element is mounted on the first side of the interposer substrate. The semiconductor element is connected with the electrode pad by the signal line. A terminating resistor is mounted on the interposer substrate. A plating stub, which is located on the interposer substrate, has a first end portion that terminates near the peripheral edge of the interposer substrate and a second end portion that is electrically connected to the electrode. The first end portion is electrically connected through the terminating resistor to an electrical ground.

CLAIMS
--------------------------------------------------------------------------------
No claims available.

RETRIEVED DESCRIPTION CHUNK
--------------------------------------------------------------------------------
BACKGROUND
 [0001] The present invention relates to semiconductor fabrication and, in particular, to semiconductor packages having a semiconductor element mounted thereon, for transferring a high-speed signal, and particularly to the wiring configuration on an interposer substrate of the device package.
 [0002] Integrated circuit (“IC”) packaging is the final stage of semiconductor device fabrication per se, followed by IC testing. Contemporary electronic apparatuses include components that transmit very high-speed signals having a pulse width that corresponds, after being converted to frequency domain, to several hundreds of megahertz to one gigahertz. As technology advances, these signal speeds have been increased even more, and there is a demand for the transmission of a signal that corresponds to a frequency of several gigahertz or higher.
 [0003] Further, multifunctional ICs and IC modules have been developed that are like system large scale integration (“LSI”) chips, and these ICs are mounted in multi-terminal packages, such as ball grid arrays (“BGA”) or chip scale packages (“CSP”). That is, an IC having a high-speed signal transmission interface tends to be mounted in a multi-terminal semiconductor package, such as a BGA or a CSP. Ball grid array packages and their variants have existed since the 1970s. The BGA is descended from the pin grid array (“PGA”), which is a package with one face covered (or partly covered) with pins in a grid pattern. These pins are used

================================================================================
PATENT 4
================================================================================
Patent ID : b8ead524636a26d39526
Category  : advanced_packaging
CPC       : H
Source    : BIGPATENT
Similarity: 0.7261

ABSTRACT
--------------------------------------------------------------------------------
Methods and apparatus for eliminating wire sweep and shorting while avoiding the use of under-bump metallization and high cost attendant to the use of conventional redistribution layers. An anisotropically conductive (z-axis) conductive layer in the form of a film or tape is applied to the active surface of a die and used as a base for conductive redistribution bumps formed on the anisotropically conductive layer, bonded to the ends of conductive columns thereof and wire bonded to the bond pads of the die. Packages so formed may be connected to substrates either with additional wire bonds extending from the conductive redistribution bumps to terminal pads or by flip-chip bonding using conductive bumps formed on the conductive redistribution bumps to connect to the terminal pads. The acts of the methods may be performed at the wafer level. Semiconductor die assemblies using the present invention are also disclosed.

CLAIMS
--------------------------------------------------------------------------------
No claims available.

RETRIEVED DESCRIPTION CHUNK
--------------------------------------------------------------------------------
wherein the wafer is severed into individual semiconductor devices. While integrated packages may be formed of two or more chips, the integration of multiple functional circuits on single chips has also become common, leading to chips with a large number of input/output (I/O) terminals for signal transmission, power supply, ground (or bias), and testing. There has been a continuing effort in the industry to enhance the functional density of semiconductor devices while simultaneously decreasing their size. Densification in chip fabrication has many advantages, including overall reduction in cost, reduction in package volume, and enhanced electrical efficiency due to shorter signal transmission paths. Moreover, increased miniaturization has enabled the formation of complex integrated circuits on a single chip or die, such as a so-called “computer on a chip.”
 [0006] In general, the circuits on a chip or die terminate in conductive bond pads arrayed on the die&#39;s active surface, typically in one or more rows about the die periphery or across a central portion of the die. These bond pads are generally formed of aluminum or an aluminum alloy and are designed to be conductively connected to terminals of a carrier substrate such as an interposer or circuit board, the pattern of terminals on which may not correspond to the locations of the corresponding bond pads on the die. In addition, the lateral bond pad-to-bond pad separation (pitch) may be too close for satisfactory direct

================================================================================
PATENT 5
================================================================================
Patent ID : a412f1b3ea8b5836df4b
Category  : advanced_packaging
CPC       : H
Source    : BIGPATENT
Similarity: 0.7229

ABSTRACT
--------------------------------------------------------------------------------
Pillars having a directed compliance geometry are arranged to couple a semiconductor die to a substrate. The direction of maximum compliance of each pillar may be aligned with the direction of maximum stress caused by unequal thermal expansion and contraction of the semiconductor die and substrate. Pillars may be designed and constructed with various shapes having particular compliance characteristics and particular directions of maximum compliance. The shape and orientation of the pillars may be selected as a function of their location on a die to accommodate the direction and magnitude of stress at their location. A method includes fabricating pillars with particular shapes by patterning to increase surface of materials upon which the pillar is plated or deposited.

CLAIMS
--------------------------------------------------------------------------------
No claims available.

RETRIEVED DESCRIPTION CHUNK
--------------------------------------------------------------------------------
FIELD OF THE DISCLOSURE
 [0001] The present disclosure is in the field of semiconductor packaging and more particularly in the field of copper pillar interconnects in semiconductor packaging.
 BACKGROUND
 [0002] Integrated circuit (IC) fabrication processes have produced ICs with reduced node spacing in the range of 48 nm and 28 nm nodes, for example. Material having an extremely low dielectric constant (ELK) has been used to accommodate the reduced node spacing and to enhance electrical performance of the ICs that are produced with such small node spacing. The ELK material may include relatively porous material which may be susceptible to cracking in response to certain stresses.
 [0003] Interconnect pillars constructed from more rigid conductive materials such as copper have been used along with solder in certain solder bump connections between a semiconductor die and a substrate. In electronic packaging, for example, a flip chip can include a pillar that extends from a contact on a die or wafer to a solder connection on a substrate. The solder connection can be a solder on pad (SOP) connection, for example.
 [0004] The use of pillars provides an improvement over earlier semiconductor interconnect techniques by allowing a very high density of interconnects. The metallurgical properties of the pillars compared to earlier solder structures allow the smaller pitch connections to maintain an appropriate standoff distance between a semiconductor die and a substrate to which

In [74]:
# STEP 18E — Build Evidence-Aware RAG Context

def build_evidence_context(results):
    """
    Build structured evidence context for the LLM.

    Each result contains:
    - patent metadata
    - abstract
    - claims
    - retrieved description chunk
    - similarity score
    """

    context_parts = []

    for i, row in results.iterrows():

        abstract = row.get("abstract", "")
        claims = row.get("claims", "")

        if not abstract:
            abstract = "No abstract available."

        if not claims:
            claims = "No claims available."

        context_parts.append(
            f"""
PATENT EVIDENCE {i + 1}
======================

Patent ID:
{row["document_id"]}

Category:
{row["category"]}

CPC Section:
{row["cpc_section"]}

Source:
{row["source"]}

Semantic Similarity:
{row["similarity"]:.4f}


ABSTRACT
--------
{abstract[:2000]}


CLAIMS
------
{claims[:3000]}


RETRIEVED PATENT TEXT
---------------------
{row["text"][:3000]}

"""
        )

    return "\n".join(context_parts)

In [78]:
# STEP 19A — Citation-Aware RAG Prompt

def build_citation_rag_prompt(question, retrieved_context):
    """
    Build a RAG prompt that requires patent-level citations.
    """

    prompt = f"""
You are a semiconductor patent research assistant.

Answer the user's question using ONLY the retrieved patent
evidence provided below.

IMPORTANT RULES
===============

1. Do not use outside knowledge.
2. Do not invent patent IDs.
3. Every technical statement must be supported by the
   retrieved patent evidence.
4. Cite the patent ID immediately after the statement it supports.
5. Use this citation format:

   [Patent: DOCUMENT_ID]

6. If multiple patents support a statement, cite them all:

   [Patent: ID1, ID2]

7. If the retrieved evidence is insufficient, say:

   "The retrieved patent evidence is insufficient to answer this."

8. Do not claim that something is covered by a patent claim,
   because this corpus does not contain claims.
9. Do not provide legal opinions about patent validity,
   infringement, novelty, or claim coverage.

RETRIEVED PATENT EVIDENCE
=========================

{retrieved_context}

=========================

USER QUESTION
=============

{question}

=========================

ANSWER REQUIREMENTS
===================

Provide:

1. A concise answer.
2. The main technical approaches found in the retrieved patents.
3. A patent citation after each relevant technical statement.
4. A short Sources section listing the patent IDs used.

ANSWER
======
"""

    return prompt

In [79]:
# STEP 19B — Citation-Aware Evidence Context

def build_citation_context(results):
    """
    Build evidence context where each patent is clearly
    identified for citation.
    """

    context_parts = []

    for i, row in results.iterrows():

        abstract = row.get("abstract", "")

        if not abstract:
            abstract = "No abstract available."

        context_parts.append(
            f"""
SOURCE {i + 1}
============

PATENT ID:
{row["document_id"]}

CATEGORY:
{row["category"]}

CPC SECTION:
{row["cpc_section"]}

SOURCE:
{row["source"]}

SIMILARITY:
{row["similarity"]:.4f}

ABSTRACT:
{abstract[:2000]}

RETRIEVED DESCRIPTION:
{row["text"][:3500]}

END SOURCE
==========
"""
        )

    return "\n".join(context_parts)

In [80]:
# STEP 19C — Citation-Aware RAG Query

question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

results = retrieve_patents(
    question,
    top_k=5
)

enriched_results = enrich_retrieval_results(
    results
)

context = build_citation_context(
    enriched_results
)

prompt = build_citation_rag_prompt(
    question,
    context
)

answer = ask_ollama(prompt)

print("=" * 80)
print("CITATION-AWARE RAG ANSWER")
print("=" * 80)
print(answer)

================================================================================
CITATION-AWARE RAG ANSWER
================================================================================
The retrieved patent evidence mentions techniques to reduce impedance in semiconductor packaging, primarily through the use of a terminating resistor connected to ground to mitigate plating stub effects. This resistor helps control signal reflections in high-speed interconnects, thereby reducing impedance issues caused by plating stubs. [Patent: a969f5fbe709d62ce477]

**Sources**
a969f5fbe709d62ce477, f2ada019c57f2835065e, 01ea3f6e9244856597cb, b8ead524636a26d39526, a412f1b3ea8b5836df4b

In [81]:
# STEP 19D — Show Retrieved Patent Sources

print("\n")
print("=" * 80)
print("PATENTS USED")
print("=" * 80)

for i, row in enriched_results.iterrows():

    print(
        f"{i + 1}. "
        f"{row['document_id']} | "
        f"{row['category']} | "
        f"{row['section']} | "
        f"similarity={row['similarity']:.4f}"
    )

================================================================================
PATENTS USED
================================================================================
1. 01ea3f6e9244856597cb | advanced_packaging | description | similarity=0.7394
2. f2ada019c57f2835065e | advanced_packaging | description | similarity=0.7325
3. a969f5fbe709d62ce477 | advanced_packaging | description | similarity=0.7278
4. b8ead524636a26d39526 | advanced_packaging | description | similarity=0.7261
5. a412f1b3ea8b5836df4b | advanced_packaging | description | similarity=0.7229

In [82]:
# STEP 20A — Two-Stage Retrieval

def retrieve_patents_two_stage(
    query,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
):
    """
    Two-stage patent retrieval.

    Stage 1:
        Retrieve the most similar chunks.

    Stage 2:
        Select the strongest distinct patents and retain
        multiple relevant chunks from each patent.
    """

    query_embedding = np.array(
        embed_text(query),
        dtype=np.float32
    )

    query_norm = np.linalg.norm(query_embedding)

    query_embedding = (
        query_embedding / max(query_norm, 1e-12)
    )

    similarities = (
        embedding_matrix_normalized @ query_embedding
    )

    # --------------------------------------------------------
    # Stage 1 — Retrieve broad candidate pool
    # --------------------------------------------------------

    ranked_indices = np.argsort(similarities)[::-1]

    candidate_indices = ranked_indices[:candidate_k]

    candidates = chunks_df.iloc[candidate_indices].copy()

    candidates["similarity"] = similarities[candidate_indices]

    candidates = candidates.sort_values(
        "similarity",
        ascending=False
    )

    # --------------------------------------------------------
    # Stage 2 — Select distinct patents
    # --------------------------------------------------------

    selected_patents = []

    for patent_id in candidates["document_id"]:

        if patent_id not in selected_patents:

            selected_patents.append(patent_id)

        if len(selected_patents) >= top_patents:
            break

    # --------------------------------------------------------
    # Keep multiple chunks from selected patents
    # --------------------------------------------------------

    final_results = []

    for patent_id in selected_patents:

        patent_chunks = candidates[
            candidates["document_id"] == patent_id
        ].head(chunks_per_patent)

        final_results.append(patent_chunks)

    if not final_results:
        return pd.DataFrame(
            columns=list(chunks_df.columns) + ["similarity"]
        )

    results = pd.concat(
        final_results,
        ignore_index=True
    )

    # Highest similarity first
    results = results.sort_values(
        "similarity",
        ascending=False
    ).reset_index(drop=True)

    return results

In [83]:
# STEP 20B — Test Two-Stage Retrieval

question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

results = retrieve_patents_two_stage(
    question,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
)

print("=" * 80)
print("TWO-STAGE RETRIEVAL")
print("=" * 80)

print("Results:", len(results))
print(
    "Unique patents:",
    results["document_id"].nunique()
)

print()

for i, row in results.iterrows():

    print(
        f"{i + 1}. "
        f"{row['document_id']} | "
        f"{row['section']} | "
        f"similarity={row['similarity']:.4f}"
    )

================================================================================
TWO-STAGE RETRIEVAL
================================================================================
Results: 7
Unique patents: 5

1. 01ea3f6e9244856597cb | description | similarity=0.7394
2. f2ada019c57f2835065e | description | similarity=0.7325
3. a969f5fbe709d62ce477 | description | similarity=0.7278
4. 01ea3f6e9244856597cb | description | similarity=0.7273
5. b8ead524636a26d39526 | description | similarity=0.7261
6. a412f1b3ea8b5836df4b | description | similarity=0.7229
7. a969f5fbe709d62ce477 | abstract | similarity=0.7220

In [84]:
# STEP 20C — Enrich Two-Stage Results

enriched_results = enrich_retrieval_results(
    results
)

print(enriched_results.columns.tolist())

['chunk_id', 'document_id', 'category', 'cpc_section', 'source', 'section', 'text', 'file_path', 'similarity', 'abstract', 'claims']

In [85]:
# STEP 20D — Build Multi-Chunk Evidence Context

def build_citation_context(results):

    context_parts = []

    grouped = results.groupby("document_id")

    source_number = 1

    for patent_id, patent_group in grouped:

        first_row = patent_group.iloc[0]

        abstract = first_row.get(
            "abstract",
            ""
        )

        if not abstract:
            abstract = "No abstract available."

        chunks = []

        for j, (_, row) in enumerate(
            patent_group.iterrows(),
            start=1
        ):

            chunks.append(
                f"""
RELEVANT TEXT CHUNK {j}
Similarity: {row["similarity"]:.4f}

{row["text"]}
"""
            )

        context_parts.append(
            f"""
SOURCE {source_number}
=====================

PATENT ID:
{patent_id}

CATEGORY:
{first_row["category"]}

CPC SECTION:
{first_row["cpc_section"]}

SOURCE:
{first_row["source"]}

ABSTRACT:
{abstract[:2000]}

RELEVANT PATENT TEXT:
{"".join(chunks)}

END SOURCE
==========
"""
        )

        source_number += 1

    return "\n".join(context_parts)

In [86]:
# STEP 20E — Two-Stage Citation-Aware RAG

question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

results = retrieve_patents_two_stage(
    question,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
)

enriched_results = enrich_retrieval_results(
    results
)

context = build_citation_context(
    enriched_results
)

prompt = build_citation_rag_prompt(
    question,
    context
)

answer = ask_ollama(prompt)

print("=" * 80)
print("TWO-STAGE RAG ANSWER")
print("=" * 80)

print(answer)

================================================================================
TWO-STAGE RAG ANSWER
================================================================================
**Answer:**
Techniques to reduce impedance in semiconductor packaging include:
1. **Using an ESD shield** to increase package impedance, enhancing resistance to electrostatic discharge (ESD) failures. This approach improves impedance management for ESD protection. (Patent: 01ea3f6e9244856597cb)
2. **Employing terminating resistors** connected to ground to mitigate plating stub effects in high-speed signal paths. This technique reduces impedance mismatches and minimizes signal reflections. (Patent: a969f5fbe709d62ce477)

**Sources:**
- 01ea3f6e9244856597cb
- a969f5fbe709d62ce477

In [87]:
# STEP 20F — Display Patent Sources

print("\n")
print("=" * 80)
print("PATENTS USED")
print("=" * 80)

for patent_id, group in enriched_results.groupby(
    "document_id"
):

    best_similarity = group["similarity"].max()

    print(
        f"{patent_id} | "
        f"chunks={len(group)} | "
        f"best_similarity={best_similarity:.4f}"
    )

================================================================================
PATENTS USED
================================================================================
01ea3f6e9244856597cb | chunks=2 | best_similarity=0.7394
a412f1b3ea8b5836df4b | chunks=1 | best_similarity=0.7229
a969f5fbe709d62ce477 | chunks=2 | best_similarity=0.7278
b8ead524636a26d39526 | chunks=1 | best_similarity=0.7261
f2ada019c57f2835065e | chunks=1 | best_similarity=0.7325

In [88]:
# STEP 21A — Retrieval Evaluation Questions

evaluation_questions = [
    "What techniques are used to reduce impedance in semiconductor packaging?",
    
    "What methods are used for semiconductor wafer defect detection?",
    
    "How are thermal management problems addressed in semiconductor packages?",
    
    "What techniques are used to improve semiconductor interconnect reliability?",
    
    "What methods are used to improve semiconductor manufacturing yield?",
    
    "How are semiconductor devices packaged to reduce signal loss?",
    
    "What techniques are used for wafer-level packaging?",
    
    "How are semiconductor manufacturing defects identified?",
    
    "What methods are used to improve heat dissipation in semiconductor devices?",
    
    "What approaches are used to improve electrical performance in advanced semiconductor packaging?",
]

print("Evaluation questions:", len(evaluation_questions))

Evaluation questions: 10

In [89]:
# STEP 21B — Run Retrieval Evaluation

evaluation_results = []

for question in evaluation_questions:

    results = retrieve_patents_two_stage(
        question,
        candidate_k=20,
        top_patents=5,
        chunks_per_patent=2,
    )

    unique_patents = results["document_id"].unique()

    for rank, patent_id in enumerate(unique_patents, start=1):

        patent_rows = results[
            results["document_id"] == patent_id
        ]

        best_similarity = patent_rows["similarity"].max()

        category = patent_rows.iloc[0]["category"]

        evaluation_results.append({
            "question": question,
            "rank": rank,
            "document_id": patent_id,
            "category": category,
            "similarity": best_similarity,
        })

evaluation_df = pd.DataFrame(evaluation_results)

print(
    "Evaluation completed:",
    len(evaluation_df),
    "patent/question results"
)

Evaluation completed: 50 patent/question results

In [90]:
# STEP 21C — Inspect Retrieval Results

for question in evaluation_questions:

    print("=" * 100)
    print("QUESTION")
    print(question)
    print("=" * 100)

    subset = evaluation_df[
        evaluation_df["question"] == question
    ]

    for _, row in subset.iterrows():

        print(
            f"{int(row['rank'])}. "
            f"{row['document_id']} | "
            f"{row['category']} | "
            f"similarity={row['similarity']:.4f}"
        )

    print()

====================================================================================================
QUESTION
What techniques are used to reduce impedance in semiconductor packaging?
====================================================================================================
1. 01ea3f6e9244856597cb | advanced_packaging | similarity=0.7394
2. f2ada019c57f2835065e | advanced_packaging | similarity=0.7325
3. a969f5fbe709d62ce477 | advanced_packaging | similarity=0.7278
4. b8ead524636a26d39526 | advanced_packaging | similarity=0.7261
5. a412f1b3ea8b5836df4b | advanced_packaging | similarity=0.7229

====================================================================================================
QUESTION
What methods are used for semiconductor wafer defect detection?
====================================================================================================
1. patent_eccc29daa65f9d0d | transistor_device_technology | similarity=0.7784
2. patent_678e9b7f28681857 | semiconductor_manufacturing | similarity=0.7644
3. patent_1bc765dc24dc5424 | semiconductor_manufacturing | similarity=0.7294
4. patent_5857feba838ea63a | advanced_packaging | similarity=0.7079
5. be1f8e667484e2e2008a | advanced_packaging | similarity=0.7075

====================================================================================================
QUESTION
How are thermal management problems addressed in semiconductor packages?
====================================================================================================
1. 6001024cc3df05a76add | advanced_packaging | similarity=0.7370
2. 4f2d66a8ff98850380a6 | advanced_packaging | similarity=0.7071
3. 9fc9b5878271526481ab | advanced_packaging | similarity=0.7044
4. 348bc72dabfda8c4f30d | advanced_packaging | similarity=0.6897
5. 95a68ed21542fb897275 | advanced_packaging | similarity=0.6819

====================================================================================================
QUESTION
What techniques are used to improve semiconductor interconnect reliability?
====================================================================================================
1. 26ba5ba2e4e5840b16e8 | advanced_packaging | similarity=0.7088
2. ef83713cbacd7d14b148 | advanced_packaging | similarity=0.6969
3. 8b663cb7916ad2149bb5 | advanced_packaging | similarity=0.6959
4. 4850350772e589a84c1d | advanced_packaging | similarity=0.6902
5. 44549d7b90b0b802940b | advanced_packaging | similarity=0.6882

====================================================================================================
QUESTION
What methods are used to improve semiconductor manufacturing yield?
====================================================================================================
1. 26ba5ba2e4e5840b16e8 | advanced_packaging | similarity=0.7252
2. patent_678e9b7f28681857 | semiconductor_manufacturing | similarity=0.6991
3. 44549d7b90b0b802940b | advanced_packaging | similarity=0.6924
4. 95a68ed21542fb897275 | advanced_packaging | similarity=0.6923
5. f2ada019c57f2835065e | advanced_packaging | similarity=0.6898

====================================================================================================
QUESTION
How are semiconductor devices packaged to reduce signal loss?
====================================================================================================
1. a969f5fbe709d62ce477 | advanced_packaging | similarity=0.7632
2. f2ada019c57f2835065e | advanced_packaging | similarity=0.7459
3. 01ea3f6e9244856597cb | advanced_packaging | similarity=0.7280
4. 403a180868f181ccb1a0 | advanced_packaging | similarity=0.7150
5. b8ead524636a26d39526 | advanced_packaging | similarity=0.7137

====================================================================================================
QUESTION
What techniques are used for wafer-level packaging?
====================================================================================================
1. 9bf8debd8e7fba4596e4 | advanced_packaging | similarity=0.7946
2. f2ada019c57f2835065e | advanced_packaging | similarity=0.7680
3. 6b565ef605bd2c8e8fb1 | advanced_packaging | similarity=0.7678
4. 2d43ab40fc0eb9178499 | advanced_packaging | similarity=0.7568
5. 56abec052abdcddc1635 | advanced_packaging | similarity=0.7322

====================================================================================================
QUESTION
How are semiconductor manufacturing defects identified?
====================================================================================================
1. patent_678e9b7f28681857 | semiconductor_manufacturing | similarity=0.8216
2. patent_eccc29daa65f9d0d | transistor_device_technology | similarity=0.7978
3. be1f8e667484e2e2008a | advanced_packaging | similarity=0.7185
4. patent_1bc765dc24dc5424 | semiconductor_manufacturing | similarity=0.6973
5. 403a180868f181ccb1a0 | advanced_packaging | similarity=0.6835

====================================================================================================
QUESTION
What methods are used to improve heat dissipation in semiconductor devices?
====================================================================================================
1. 1d665cb5eebdc0f2cea0 | advanced_packaging | similarity=0.7690
2. 0628719951bb1c732427 | advanced_packaging | similarity=0.7333
3. 95a68ed21542fb897275 | advanced_packaging | similarity=0.7244
4. be1f8e667484e2e2008a | advanced_packaging | similarity=0.7164
5. 26ba5ba2e4e5840b16e8 | advanced_packaging | similarity=0.7140

====================================================================================================
QUESTION
What approaches are used to improve electrical performance in advanced semiconductor packaging?
====================================================================================================
1. f2ada019c57f2835065e | advanced_packaging | similarity=0.7526
2. 01ea3f6e9244856597cb | advanced_packaging | similarity=0.7397
3. a969f5fbe709d62ce477 | advanced_packaging | similarity=0.7370
4. 5c06202f88b554e8144b | advanced_packaging | similarity=0.7306
5. 23ebeda5c273212c3bcd | advanced_packaging | similarity=0.7146

In [91]:
# STEP 21D — Expected Categories

expected_categories = {
    "What techniques are used to reduce impedance in semiconductor packaging?":
        ["advanced_packaging"],

    "What methods are used for semiconductor wafer defect detection?":
        ["semiconductor_manufacturing"],

    "How are thermal management problems addressed in semiconductor packages?":
        ["advanced_packaging"],

    "What techniques are used to improve semiconductor interconnect reliability?":
        ["advanced_packaging", "semiconductor_manufacturing"],

    "What methods are used to improve semiconductor manufacturing yield?":
        ["semiconductor_manufacturing"],

    "How are semiconductor devices packaged to reduce signal loss?":
        ["advanced_packaging"],

    "What techniques are used for wafer-level packaging?":
        ["advanced_packaging"],

    "How are semiconductor manufacturing defects identified?":
        ["semiconductor_manufacturing"],

    "What methods are used to improve heat dissipation in semiconductor devices?":
        ["advanced_packaging"],

    "What approaches are used to improve electrical performance in advanced semiconductor packaging?":
        ["advanced_packaging"],
}

In [92]:
# STEP 21E — Calculate Category Hit Rate

evaluation_summary = []

for question in evaluation_questions:

    expected = expected_categories[question]

    subset = evaluation_df[
        evaluation_df["question"] == question
    ]

    retrieved_categories = set(
        subset["category"].dropna()
    )

    hit = any(
        category in retrieved_categories
        for category in expected
    )

    top1_category = (
        subset.iloc[0]["category"]
        if len(subset) > 0
        else None
    )

    evaluation_summary.append({
        "question": question,
        "expected_categories": ", ".join(expected),
        "top1_category": top1_category,
        "top5_categories": ", ".join(
            sorted(retrieved_categories)
        ),
        "category_hit": hit,
    })

evaluation_summary_df = pd.DataFrame(
    evaluation_summary
)

print(evaluation_summary_df)

                                            question  \
0  What techniques are used to reduce impedance i...
1  What methods are used for semiconductor wafer ...
2  How are thermal management problems addressed ...
3  What techniques are used to improve semiconduc...
4  What methods are used to improve semiconductor...
5  How are semiconductor devices packaged to redu...
6  What techniques are used for wafer-level packa...
7  How are semiconductor manufacturing defects id...
8  What methods are used to improve heat dissipat...
9  What approaches are used to improve electrical...

                               expected_categories  \
0                               advanced_packaging
1                      semiconductor_manufacturing
2                               advanced_packaging
3  advanced_packaging, semiconductor_manufacturing
4                      semiconductor_manufacturing
5                               advanced_packaging
6                               advanced_packaging
7                      semiconductor_manufacturing
8                               advanced_packaging
9                               advanced_packaging

                  top1_category  \
0            advanced_packaging
1  transistor_device_technology
2            advanced_packaging
3            advanced_packaging
4            advanced_packaging
5            advanced_packaging
6            advanced_packaging
7   semiconductor_manufacturing
8            advanced_packaging
9            advanced_packaging

                                     top5_categories  category_hit
0                                 advanced_packaging          True
1  advanced_packaging, semiconductor_manufacturin...          True
2                                 advanced_packaging          True
3                                 advanced_packaging          True
4    advanced_packaging, semiconductor_manufacturing          True
5                                 advanced_packaging          True
6                                 advanced_packaging          True
7  advanced_packaging, semiconductor_manufacturin...          True
8                                 advanced_packaging          True
9                                 advanced_packaging          True

In [93]:
# STEP 21F — Overall Retrieval Score

category_hit_rate = (
    evaluation_summary_df["category_hit"].mean()
)

print("=" * 80)
print("RETRIEVAL EVALUATION")
print("=" * 80)

print(
    "Category hit rate:",
    round(category_hit_rate * 100, 2),
    "%"
)

================================================================================
RETRIEVAL EVALUATION
================================================================================
Category hit rate: 100.0 %

In [102]:
# STEP 22 — Lightweight Reranking Prompt

def build_reranking_prompt(question, candidates):
    """
    Build a compact reranking prompt for Qwen3.
    """

    candidate_text = []

    for i, row in candidates.iterrows():

        candidate_text.append(
            f"""
[{i}]
Patent: {row["document_id"]}
Text: {row["text"][:900]}
"""
        )

    candidates_text = "\n".join(candidate_text)

    prompt = f"""
Rank these patent passages for the question below.

QUESTION:
{question}

CANDIDATES:
{candidates_text}

Return ONLY the candidate numbers from most relevant
to least relevant.

Example:
3, 1, 0, 4, 2
"""

    return prompt

In [103]:
# STEP 22B — Parse Reranking Output

import re


def parse_ranking(response, candidate_count):
    """
    Extract candidate numbers from the Qwen3 response.
    """

    numbers = re.findall(
        r"\b\d+\b",
        response
    )

    ranking = []

    for number in numbers:

        index = int(number)

        if 0 <= index < candidate_count:
            if index not in ranking:
                ranking.append(index)

    return ranking

In [104]:
# STEP 22C — Qwen3 Reranker

def rerank_candidates(question, candidates):
    """
    Rerank semantic-search candidates using Qwen3.
    """

    if candidates.empty:
        return candidates

    prompt = build_reranking_prompt(
        question,
        candidates
    )

    response = ask_ollama(prompt)

    ranking = parse_ranking(
        response,
        len(candidates)
    )

    # If Qwen3 produced an invalid ranking,
    # preserve the original similarity ordering.
    if not ranking:
        return candidates.copy()

    ranked_rows = []

    for index in ranking:
        ranked_rows.append(
            candidates.iloc[index]
        )

    # Add candidates that Qwen3 failed to mention
    for index in range(len(candidates)):

        if index not in ranking:
            ranked_rows.append(
                candidates.iloc[index]
            )

    reranked = pd.DataFrame(
        ranked_rows
    ).reset_index(drop=True)

    reranked["rerank_position"] = (
        range(1, len(reranked) + 1)
    )

    return reranked

In [105]:
# STEP 22D — Test Reranking

question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

candidate_results = retrieve_patents_two_stage(
    question,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
)

reranked_results = rerank_candidates(
    question,
    candidate_results
)

print("=" * 80)
print("RERANKED RESULTS")
print("=" * 80)

for i, row in reranked_results.iterrows():

    print(
        f"{i + 1}. "
        f"{row['document_id']} | "
        f"similarity={row['similarity']:.4f}"
    )

================================================================================
RERANKED RESULTS
================================================================================
1. a969f5fbe709d62ce477 | similarity=0.7220
2. a969f5fbe709d62ce477 | similarity=0.7278
3. a412f1b3ea8b5836df4b | similarity=0.7229
4. f2ada019c57f2835065e | similarity=0.7325
5. b8ead524636a26d39526 | similarity=0.7261
6. 01ea3f6e9244856597cb | similarity=0.7394
7. 01ea3f6e9244856597cb | similarity=0.7273

In [106]:
# STEP 23A — Complete Reranked RAG Pipeline

def run_reranked_rag(
    question,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
):
    """
    Complete patent RAG pipeline:

    1. Semantic candidate retrieval
    2. Patent-level selection
    3. Qwen3 reranking
    4. Patent evidence enrichment
    5. Citation-aware context construction
    6. Grounded answer generation
    """

    # --------------------------------------------------------
    # Stage 1 — Retrieve candidates
    # --------------------------------------------------------

    candidate_results = retrieve_patents_two_stage(
        question,
        candidate_k=candidate_k,
        top_patents=top_patents,
        chunks_per_patent=chunks_per_patent,
    )

    if candidate_results.empty:
        return {
            "question": question,
            "answer": "No relevant patent evidence was retrieved.",
            "results": candidate_results,
        }

    # --------------------------------------------------------
    # Stage 2 — Rerank candidates
    # --------------------------------------------------------

    reranked_results = rerank_candidates(
        question,
        candidate_results,
    )

    # --------------------------------------------------------
    # Stage 3 — Enrich with patent metadata
    # --------------------------------------------------------

    enriched_results = enrich_retrieval_results(
        reranked_results
    )

    # --------------------------------------------------------
    # Stage 4 — Build evidence context
    # --------------------------------------------------------

    context = build_citation_context(
        enriched_results
    )

    # --------------------------------------------------------
    # Stage 5 — Build grounded prompt
    # --------------------------------------------------------

    prompt = build_citation_rag_prompt(
        question,
        context
    )

    # --------------------------------------------------------
    # Stage 6 — Generate answer
    # --------------------------------------------------------

    answer = ask_ollama(prompt)

    return {
        "question": question,
        "answer": answer,
        "results": enriched_results,
        "context": context,
        "prompt": prompt,
    }

In [107]:
# STEP 23B — Run Complete Reranked RAG

question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

rag_result = run_reranked_rag(
    question
)

print("=" * 80)
print("RERANKED RAG ANSWER")
print("=" * 80)

print(rag_result["answer"])

================================================================================
RERANKED RAG ANSWER
================================================================================
The retrieved patent evidence indicates that techniques to reduce impedance in semiconductor packaging include the use of a terminating resistor connected to an electrical ground to mitigate plating stub effects. This resistor is electrically connected to the first end portion of a plating stub, which terminates near the peripheral edge of the interposer substrate, thereby managing impedance in high-speed signal transmission. [Patent: a969f5fbe709d62ce477]

**Sources**
- a969f5fbe709d62ce477

In [108]:
# STEP 23C — Display Reranked Evidence

results = rag_result["results"]

print("\n")
print("=" * 80)
print("RERANKED PATENT EVIDENCE")
print("=" * 80)

for i, row in results.iterrows():

    print(
        f"{i + 1}. "
        f"{row['document_id']} | "
        f"similarity={row['similarity']:.4f} | "
        f"rerank_position={row['rerank_position']}"
    )

    print(
        f"   Category: {row['category']}"
    )

    print(
        f"   Section: {row['section']}"
    )

    print()

================================================================================
RERANKED PATENT EVIDENCE
================================================================================
1. a969f5fbe709d62ce477 | similarity=0.7220 | rerank_position=1
   Category: advanced_packaging
   Section: abstract

2. a412f1b3ea8b5836df4b | similarity=0.7229 | rerank_position=2
   Category: advanced_packaging
   Section: description

3. a969f5fbe709d62ce477 | similarity=0.7278 | rerank_position=3
   Category: advanced_packaging
   Section: description

4. b8ead524636a26d39526 | similarity=0.7261 | rerank_position=4
   Category: advanced_packaging
   Section: description

5. f2ada019c57f2835065e | similarity=0.7325 | rerank_position=5
   Category: advanced_packaging
   Section: description

6. 01ea3f6e9244856597cb | similarity=0.7394 | rerank_position=6
   Category: advanced_packaging
   Section: description

7. 01ea3f6e9244856597cb | similarity=0.7273 | rerank_position=7
   Category: advanced_packaging
   Section: description

In [109]:
# STEP 23D — Inspect Evidence Used by the LLM

for i, row in results.iterrows():

    print("=" * 80)
    print(
        f"EVIDENCE {i + 1} — "
        f"{row['document_id']}"
    )
    print("=" * 80)

    print(
        "Similarity:",
        round(float(row["similarity"]), 4)
    )

    print(
        "Rerank position:",
        row["rerank_position"]
    )

    print("\nPatent text:")
    print(row["text"])

    print()

================================================================================
EVIDENCE 1 — a969f5fbe709d62ce477
================================================================================
Similarity: 0.722
Rerank position: 1

Patent text:
Packages and methods for mitigating plating stub effects. The semiconductor package includes an interposer substrate having a first side, a second side, a peripheral edge connecting the first side with the second side, a signal line on the first side, and an electrode pad on the first side. A semiconductor element is mounted on the first side of the interposer substrate. The semiconductor element is connected with the electrode pad by the signal line. A terminating resistor is mounted on the interposer substrate. A plating stub, which is located on the interposer substrate, has a first end portion that terminates near the peripheral edge of the interposer substrate and a second end portion that is electrically connected to the electrode. The first end portion is electrically connected through the terminating resistor to an electrical ground.

================================================================================
EVIDENCE 2 — a412f1b3ea8b5836df4b
================================================================================
Similarity: 0.7229
Rerank position: 2

Patent text:
FIELD OF THE DISCLOSURE
 [0001] The present disclosure is in the field of semiconductor packaging and more particularly in the field of copper pillar interconnects in semiconductor packaging.
 BACKGROUND
 [0002] Integrated circuit (IC) fabrication processes have produced ICs with reduced node spacing in the range of 48 nm and 28 nm nodes, for example. Material having an extremely low dielectric constant (ELK) has been used to accommodate the reduced node spacing and to enhance electrical performance of the ICs that are produced with such small node spacing. The ELK material may include relatively porous material which may be susceptible to cracking in response to certain stresses.
 [0003] Interconnect pillars constructed from more rigid conductive materials such as copper have been used along with solder in certain solder bump connections between a semiconductor die and a substrate. In electronic packaging, for example, a flip chip can include a pillar that extends from a contact on a die or wafer to a solder connection on a substrate. The solder connection can be a solder on pad (SOP) connection, for example.
 [0004] The use of pillars provides an improvement over earlier semiconductor interconnect techniques by allowing a very high density of interconnects. The metallurgical properties of the pillars compared to earlier solder structures allow the smaller pitch connections to maintain an appropriate standoff distance between a semiconductor die and a substrate to which

================================================================================
EVIDENCE 3 — a969f5fbe709d62ce477
================================================================================
Similarity: 0.7278
Rerank position: 3

Patent text:
BACKGROUND
 [0001] The present invention relates to semiconductor fabrication and, in particular, to semiconductor packages having a semiconductor element mounted thereon, for transferring a high-speed signal, and particularly to the wiring configuration on an interposer substrate of the device package.
 [0002] Integrated circuit (“IC”) packaging is the final stage of semiconductor device fabrication per se, followed by IC testing. Contemporary electronic apparatuses include components that transmit very high-speed signals having a pulse width that corresponds, after being converted to frequency domain, to several hundreds of megahertz to one gigahertz. As technology advances, these signal speeds have been increased even more, and there is a demand for the transmission of a signal that corresponds to a frequency of several gigahertz or higher.
 [0003] Further, multifunctional ICs and IC modules have been developed that are like system large scale integration (“LSI”) chips, and these ICs are mounted in multi-terminal packages, such as ball grid arrays (“BGA”) or chip scale packages (“CSP”). That is, an IC having a high-speed signal transmission interface tends to be mounted in a multi-terminal semiconductor package, such as a BGA or a CSP. Ball grid array packages and their variants have existed since the 1970s. The BGA is descended from the pin grid array (“PGA”), which is a package with one face covered (or partly covered) with pins in a grid pattern. These pins are used

================================================================================
EVIDENCE 4 — b8ead524636a26d39526
================================================================================
Similarity: 0.7261
Rerank position: 4

Patent text:
wherein the wafer is severed into individual semiconductor devices. While integrated packages may be formed of two or more chips, the integration of multiple functional circuits on single chips has also become common, leading to chips with a large number of input/output (I/O) terminals for signal transmission, power supply, ground (or bias), and testing. There has been a continuing effort in the industry to enhance the functional density of semiconductor devices while simultaneously decreasing their size. Densification in chip fabrication has many advantages, including overall reduction in cost, reduction in package volume, and enhanced electrical efficiency due to shorter signal transmission paths. Moreover, increased miniaturization has enabled the formation of complex integrated circuits on a single chip or die, such as a so-called “computer on a chip.”
 [0006] In general, the circuits on a chip or die terminate in conductive bond pads arrayed on the die&#39;s active surface, typically in one or more rows about the die periphery or across a central portion of the die. These bond pads are generally formed of aluminum or an aluminum alloy and are designed to be conductively connected to terminals of a carrier substrate such as an interposer or circuit board, the pattern of terminals on which may not correspond to the locations of the corresponding bond pads on the die. In addition, the lateral bond pad-to-bond pad separation (pitch) may be too close for satisfactory direct

================================================================================
EVIDENCE 5 — f2ada019c57f2835065e
================================================================================
Similarity: 0.7325
Rerank position: 5

Patent text:
technology that, in the future, may particularly benefit from such an advancement includes the art of semiconductor packaging. Semiconductor devices, such as memory devices and processors, are generally fabricated in very large numbers. Typically, several semiconductor devices are fabricated on a wafer or other large-scale substrate that includes a layer of semiconductor material (e.g., silicon, gallium arsenide, or indium phosphide). The semiconductor devices are then singulated, or diced, from the wafer or other large-scale substrate to provide semiconductor “chips” or dice.
 [0012] Conventionally, semiconductor dice have been packaged for protection and to facilitate the formation of electrical connections to the small bond pads thereof. Conventional semiconductor device packages typically include an assembly of a semiconductor die and a higher level substrate board (e.g., a circuit board) or leads. Bond pads of the semiconductor die are electrically connected (e.g., by wire bonds or otherwise) to contact pads of a higher level substrate or to leads. The assembly may then be packaged. For example, assemblies that include a semiconductor die with leads connected to the bond pads thereof are typically packaged by use of transfer molding techniques to secure the leads in place and to protect the active surface of the semiconductor die and the wire bonds or other intermediate conductive elements. Assemblies including a semiconductor die and a higher level substrate may be pa

================================================================================
EVIDENCE 6 — 01ea3f6e9244856597cb
================================================================================
Similarity: 0.7394
Rerank position: 6

Patent text:
TECHNICAL FIELD
 The invention described herein relates generally to semiconductor device packaging. In particular, the invention relates to a method and package for a semiconductor device that is resistant to electrostatic discharge that can be caused by various factors.
 BACKGROUND
 The semiconductor industry makes wide use of standard BGA (ball grid array) type semiconductor packages. Such packages generally include a BT (bismaleimide triazine) core having various metallization and solder mask layers to form the substrate. A semiconductor die is attached to the substrate and electrically connected to various electrical connections of the substrate using ball attach or wire-bonding techniques. The wire bonds and the die are typically encapsulated with a protective layer of encapsulant. Such packages and the methods of their construction are well known to persons having ordinary skill in the semiconductor packaging arts. Additionally, ball attach arrangements are provided with an underfill encapsulant to protect the bonding arrangements of the solder balls.
 Commonly, the packages are then provided with a stiffener and a heat spreader to complete the packages. These completed packages are then subject to a series of tests used to qualify the packages to insure they meet all the necessary specifications prior to shipping.
 One such test subjects the package to a series of electrostatic discharge (ESD) events to determine the packages robustness and resistance to these ES

================================================================================
EVIDENCE 7 — 01ea3f6e9244856597cb
================================================================================
Similarity: 0.7273
Rerank position: 7

Patent text:
ine without damage the packaged is “qualified”.
 This commonly constructed package has provided satisfactory ESD protection until recently. Now, with increasing scaling of circuit elements formed on the die, smaller less ESD resistant devices and elements are becoming more common. These devices have increased vulnerability to ESD events. Thus, the traditional package format is increasingly lacking in the ability to protect these vulnerable elements from ESD events. Accordingly, the incidence of ESD induced package failure has been rising and is expected to continue to do so as circuitry and device sizes continue to shrink.
 Accordingly, what is needed is a packaging design and approach that provides increased resistance to ESD induced package failure.
 SUMMARY OF THE INVENTION
 In accordance with the principles of the present invention, an improved semiconductor package and methods for its fabrication are disclosed.
 In general, the present invention is directed toward methods and packages that increase the package impedance of a semiconductor package thereby increasing the resistance of the overall package to ESD associated package failures.
 One embodiment of the invention comprises a semiconductor integrated circuit package having a substrate with a die attached to the front side thereof. The package includes a die electrically connected with the substrate. The package further including a discharge shield configured to protect the die from electrostatic discharge eve

In [110]:
# STEP 23E — Multi-Question RAG Test

test_questions = [
    "What techniques are used to reduce impedance in semiconductor packaging?",
    
    "What methods are used for semiconductor wafer defect detection?",
    
    "How are thermal management problems addressed in semiconductor packages?",
    
    "What techniques are used to improve semiconductor interconnect reliability?",
    
    "What methods are used to improve semiconductor manufacturing yield?",
]

In [112]:
results = result["results"]

print("=" * 80)
print("TOP PATENTS")
print("=" * 80)

if results.empty:
    print("No patents retrieved.")
else:
    top_patents = (
        results
        .groupby("document_id", sort=False)
        .first()
        .reset_index()
    )

    for _, row in top_patents.iterrows():
        print(
            f"- {row['document_id']} "
            f"(similarity={row['similarity']:.4f})"
        )

print("\n")
rag_test_results.append(result)

================================================================================
TOP PATENTS
================================================================================
- a969f5fbe709d62ce477 (similarity=0.7220)
- a412f1b3ea8b5836df4b (similarity=0.7229)
- b8ead524636a26d39526 (similarity=0.7261)
- f2ada019c57f2835065e (similarity=0.7325)
- 01ea3f6e9244856597cb (similarity=0.7394)

In [119]:
def run_reranked_rag(
    question,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
    rerank_k=10,
):
    """
    Complete semiconductor patent RAG pipeline:

    1. Vector retrieval
    2. Patent-level candidate selection
    3. Qwen3 reranking
    4. Patent metadata enrichment
    5. Citation-aware answer generation
    """

    # --------------------------------------------------------
    # 1. Retrieve candidates
    # --------------------------------------------------------

    candidate_results = retrieve_patents_two_stage(
        question,
        candidate_k=candidate_k,
        top_patents=top_patents,
        chunks_per_patent=chunks_per_patent,
    )

    if candidate_results.empty:
        return {
            "question": question,
            "answer": (
                "No relevant patent evidence was retrieved."
            ),
            "results": candidate_results,
        }

    # --------------------------------------------------------
    # 2. Rerank with Qwen3
    # --------------------------------------------------------

    reranked_results = rerank_candidates(
        question,
        candidate_results,
        rerank_k=rerank_k,
    )

    # --------------------------------------------------------
    # 3. Enrich with patent-level metadata
    # --------------------------------------------------------

    enriched_results = enrich_retrieval_results(
        reranked_results
    )

    # --------------------------------------------------------
    # 4. Build citation-aware context
    # --------------------------------------------------------

    context = build_citation_context(
        enriched_results
    )

    # --------------------------------------------------------
    # 5. Generate grounded answer
    # --------------------------------------------------------

    prompt = build_citation_rag_prompt(
        question,
        context
    )

    answer = ask_ollama(prompt)

    return {
        "question": question,
        "answer": answer,
        "results": enriched_results,
        "context": context,
        "prompt": prompt,
    }

In [121]:
def run_reranked_rag(
    question,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
    rerank_k=10,
):
    """
    Complete semiconductor patent RAG pipeline:

    1. Vector retrieval
    2. Patent-level candidate selection
    3. Qwen3 reranking
    4. Patent metadata enrichment
    5. Citation-aware answer generation
    """

    # --------------------------------------------------------
    # 1. Retrieve candidates
    # --------------------------------------------------------

    candidate_results = retrieve_patents_two_stage(
        question,
        candidate_k=candidate_k,
        top_patents=top_patents,
        chunks_per_patent=chunks_per_patent,
    )

    if candidate_results.empty:
        return {
            "question": question,
            "answer": (
                "No relevant patent evidence was retrieved."
            ),
            "results": candidate_results,
        }

    # --------------------------------------------------------
    # 2. Rerank with Qwen3
    # --------------------------------------------------------

    reranked_results = rerank_candidates(
        question,
        candidate_results,
        rerank_k=rerank_k,
    )

    # --------------------------------------------------------
    # 3. Enrich with patent-level metadata
    # --------------------------------------------------------

    enriched_results = enrich_retrieval_results(
        reranked_results
    )

    # --------------------------------------------------------
    # 4. Build citation-aware context
    # --------------------------------------------------------

    context = build_citation_context(
        enriched_results
    )

    # --------------------------------------------------------
    # 5. Generate grounded answer
    # --------------------------------------------------------

    prompt = build_citation_rag_prompt(
        question,
        context
    )

    answer = ask_ollama(prompt)

    return {
        "question": question,
        "answer": answer,
        "results": enriched_results,
        "context": context,
        "prompt": prompt,
    }

In [122]:
question = (
    "What techniques are used to reduce impedance "
    "in semiconductor packaging?"
)

candidate_results = retrieve_patents_two_stage(
    question,
    candidate_k=20,
    top_patents=5,
    chunks_per_patent=2,
)

print("=" * 80)
print("VECTOR CANDIDATES")
print("=" * 80)

for i, row in candidate_results.iterrows():
    print(
        f"{i}. {row['document_id']} | "
        f"{row['section']} | "
        f"similarity={row['similarity']:.4f}"
    )

reranked_results = rerank_candidates(
    question,
    candidate_results,
    rerank_k=10,
)

print("\n")
print("=" * 80)
print("RERANKED RESULTS")
print("=" * 80)

for i, row in reranked_results.iterrows():
    print(
        f"{i + 1}. {row['document_id']} | "
        f"similarity={row['similarity']:.4f} | "
        f"rerank={row['rerank_position']}"
    )

================================================================================
VECTOR CANDIDATES
================================================================================
0. 01ea3f6e9244856597cb | description | similarity=0.7394
1. f2ada019c57f2835065e | description | similarity=0.7325
2. a969f5fbe709d62ce477 | description | similarity=0.7278
3. 01ea3f6e9244856597cb | description | similarity=0.7273
4. b8ead524636a26d39526 | description | similarity=0.7261
5. a412f1b3ea8b5836df4b | description | similarity=0.7229
6. a969f5fbe709d62ce477 | abstract | similarity=0.7220

TypeError: rerank_candidates() got an unexpected keyword argument 'rerank_k'